communication/AMT203_model.h File Reference
#include <stdint.h>
*
#include `spi.h`
*
Data Structures
struct amt203_t
Macros
#define AMT203_CMD_NOP 0x00
#define AMT203_CMD_RD_POS 0x10
#define AMT203_CMD_SET_ZERO 0x70
#define AMT203_CMD_EEPROM_WR 0x80
#define AMT203_CMD_EEPROM_RD 0x90
#define AMT203_RES_WAIT 0xa5
Functions
int amt203_init (amt203_t *amt203, spi_t *spi, void(*chip_select)(int on))
int amt203_position_read (amt203_t *amt203, uint16_t *position)
int amt203_zero_set (amt203_t *amt203)
int amt203_eeprom_write (amt203_t *amt203, uint8_t addr, uint8_t data)
int amt203_eeprom_read (amt203_t *amt203, uint8_t addr, uint8_t *data)
Macro Definition Documentation
#define AMT203_CMD_EEPROM_RD 0x90
Definition at line 32 of file AMT203_model.h.
Referenced by amt203_eeprom_read().
#define AMT203_CMD_EEPROM_WR 0x80
Definition at line 31 of file AMT203_model.h.
Referenced by amt203_eeprom_write(), and amt203_zero_set().
#define AMT203_CMD_NOP 0x00
Definition at line 28 of file AMT203_model.h.
Referenced by amt203_eeprom_read(), amt203_init(), and amt203_position_read().
#define AMT203_CMD_RD_POS 0x10
Definition at line 29 of file AMT203_model.h.
Referenced by amt203_position_read().
#define AMT203_CMD_SET_ZERO 0x70
Definition at line 30 of file AMT203_model.h.
Referenced by amt203_zero_set().
#define AMT203_RES_WAIT 0xa5
Definition at line 35 of file AMT203_model.h.
Referenced by amt203_wait_for_ack().
Function Documentation
int amt203_eeprom_read (amt203_t * amt203, uint8_t addr, uint8_t * data)
Definition at line 136 of file AMT203_model.c.
References AMT203_CMD_EEPROM_RD, AMT203_CMD_NOP, amt203_wait_for_ack(), and amt203_xfer_byte().
{
    uint8_t cmd = AMT203_CMD_EEPROM_RD;
    uint8_t res = 0;
    assert(amt203 != NULL);
    
    /* Send command */
    amt203_xfer_byte(amt203, cmd, &res);
    amt203_xfer_byte(amt203, addr, &res);
    amt203_xfer_byte(amt203, 0x01, &res);
    if (amt203_wait_for_ack(amt203, cmd, 5) != 0) { return -
      1; }
    
    /* Get data */
    amt203_xfer_byte(amt203, AMT203_CMD_NOP, &res
      );
    *data = res;
    
    return 0;
}
int amt203_eeprom_write (amt203_t * amt203, uint8_t addr, uint8_t data)
Definition at line 121 of file AMT203_model.c.
References AMT203_CMD_EEPROM_WR, amt203_wait_for_ack(), and amt203_xfer_byte().
{
    uint8_t cmd = AMT203_CMD_EEPROM_WR;
    uint8_t res = 0;
    assert(amt203 != NULL);
    
    /* Send command */
    amt203_xfer_byte(amt203, cmd, &res);
    amt203_xfer_byte(amt203, addr, &res);
    amt203_xfer_byte(amt203, data, &res);
    if (amt203_wait_for_ack(amt203, cmd, 5) != 0) { return -
      1; }
    
    return 0;
}
int amt203_init (amt203_t * amt203, spi_t * spi, void(*)(int on) chip_select)
Definition at line 65 of file AMT203_model.c.
References AMT203_CMD_NOP, amt203_xfer_byte(), amt203_t::chip_select, and amt203_t::spi.
{
    uint8_t res = 0;
    int i=0;
    assert(amt203 != NULL);
    assert(spi != NULL);
    assert(chip_select != NULL);
    memset(amt203, 0, sizeof(amt203_t));
    amt203->spi = spi;
    amt203->chip_select = chip_select;
    
    for (i=0; i<5; i++) { amt203_xfer_byte(amt203,
      AMT203_CMD_NOP, &res); }
    return 0;
}
int amt203_position_read (amt203_t * amt203, uint16_t * position)
Definition at line 81 of file AMT203_model.c.
References AMT203_CMD_NOP, AMT203_CMD_RD_POS, amt203_wait_for_ack(), and amt203_xfer_byte().
{
    uint8_t cmd = AMT203_CMD_RD_POS;
    uint8_t res = 0;
    assert(amt203 != NULL);
    /* Send command */
    amt203_xfer_byte(amt203, cmd, &res);
    if (amt203_wait_for_ack(amt203, cmd, 5) != 0) { return -
      1; }
    
    /* Get high byte */
    amt203_xfer_byte(amt203, AMT203_CMD_NOP, &res
      );
    *position |= ((uint16_t)res << 8);
    
    /* Get low byte */
    amt203_xfer_byte(amt203, AMT203_CMD_NOP, &res
      );
    *position |= (uint16_t)res;
       
    return (*position > 0x0fff);
}
int amt203_zero_set (amt203_t * amt203)
Definition at line 102 of file AMT203_model.c.
References AMT203_CMD_EEPROM_WR, AMT203_CMD_SET_ZERO, amt203_wait_for_ack(), amt203_xfer_byte(), and INT_MAX.
{
    uint8_t cmd = AMT203_CMD_SET_ZERO;
    uint8_t res = 0;
    assert(amt203 != NULL);
    
    /* Send command */
    amt203_xfer_byte(amt203, cmd, &res);
    if (amt203_wait_for_ack(amt203, AMT203_CMD_EEPROM_WR
      , INT_MAX) != 0) {
        return -1;
    }
    /* Note:
     * From datasheet, the encoder must be power-cycled after this command
     * for the new zero position to be used in the position calculation. */
    return 0;
}