schunk_high/src/cartesian_pose_controller.cpp File Reference
#include <ros/ros.h>
*
#include <ros/callback_queue.h>
*
#include <schunk_msgs/Velocities.h>
*
#include <schunk_msgs/Positions.h>
*
#include <schunk_low/GetPosVel.h>
*
#include <schunk_low/ControlMode.h>
*
#include <schunk_low/Stop.h>
*
#include <stdlib.h>
*
#include <stdio.h>
*
#include <schunk_high/cartesian_pose_controller.h>
*
#include <schunk_low/schunk_low_control.h>
*
#include <schunk_high/gmatrix.h>
*
#include <schunk_high/gmatrix_plus.h>
*
#include <schunk_high/gmatrix_linalg.h>
*
#include <schunk_high/robot.h>
*
#include <schunk_high/dualquaternion.h>
*
Functions
int main (int argc, char **argv)
Variables
const double pi = 3.141592654
Internal.
const double pi2 = 1.57079632679489655
Function Documentation
int main (int argc, char ** argv)
Schunk's DH
Definition at line 35 of file cartesian_pose_controller.cpp.
References Cartesian_pose_controller::control(), pi2, Robot_addLink(), and Robot_create().
                               {
        ros::init(argc, argv, "schunk_cartesian_pose_controller");
        //KINEMATIC PID VALUES
        double Kpv[8] = {1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5};
        double Kiv[8] = {0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0};
        double Kdv[8] = {0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0};
        //SAMPLE TIME
        double T = 0.04;
        //Set schunk's initial joint's positions.
        std::vector<double> initialPositions;
        for(int i=0;i<8;i++){initialPositions.push_back(0);}
        //Initial position = [0 , pi2, 0, 0, 0, pi2, 0, 0]
        initialPositions[1] = pi2;
        initialPositions[5] = pi2;
        //Memory Alloc
        Robot* r = Robot_create();
        // theta d a alpha
        Robot_addLink(r, 0, 0.300 ,0, -pi2);
        Robot_addLink(r, 0, 0 ,0, pi2);
        Robot_addLink(r, 0, 0.328 ,0, -pi2);
        Robot_addLink(r, 0, 0 ,0, pi2);
        Robot_addLink(r, 0, 0.2765 ,0, -pi2);
        Robot_addLink(r, 0, 0 ,0, pi2);
        Robot_addLink(r, 0, 0.40049 ,0, 0);
        Cartesian_pose_controller cartesian_pose_Controller(initialPositions, r,
      Kpv, Kiv, Kdv, T);
        cartesian_pose_Controller.control();
}
Variable Documentation
const double pi = 3.141592654
Internal.
Definition at line 32 of file cartesian_pose_controller.cpp.
const double pi2 = 1.57079632679489655
Definition at line 33 of file cartesian_pose_controller.cpp.
Referenced by main().