schunk_high/src/cartesian_velocity_controller.cpp File Reference
#include <ros/ros.h>
*
#include <ros/callback_queue.h>
*
#include <schunk_msgs/Velocities.h>
*
#include <schunk_low/GetVelocities.h>
*
#include <schunk_low/GetPositions.h>
*
#include <schunk_low/ControlMode.h>
*
#include <schunk_low/Stop.h>
*
#include <stdlib.h>
*
#include <stdio.h>
*
#include <schunk_high/cartesian_velocity_controller.h>
*
#include <schunk_high/cartesian_controller.h>
*
#include <schunk_low/schunk_low_control.h>
*
#include <schunk_high/gmatrix.h>
*
#include <schunk_high/gmatrix_plus.h>
*
#include <schunk_high/gmatrix_linalg.h>
*
#include <schunk_high/robot.h>
*
#include <schunk_high/dualquaternion.h>
*
Functions
int main (int argc, char **argv)
Variables
const double pi = 3.141592654
Internal.
const double pi2 = 1.57079632679489655
Function Documentation
int main (int argc, char ** argv)
Schunk's DH
Definition at line 36 of file cartesian_velocity_controller.cpp.
References Cartesian_velocity_controller::control(), pi2, Robot_addLink(), and Robot_create().
                               {
        ros::init(argc, argv, "schunk_Cartesian_velocity_controller");
        //KINEMATIC PID VALUES
        double Kpv[6] = {0.6,0.6,0.6,0.6,0.6,0.6};
        double Kiv[6] = {0.0,0.0,0.0,0.0,0.0,0.0};
        double Kdv[6] = {0.0,0.0,0.0,0.0,0.0,0.0};
        //SAMPLE TIME
        double T = 0.04;
        //Memory Alloc
        Robot* r = Robot_create();
        // theta d a alpha
        Robot_addLink(r, 0, 0.300 ,0, -pi2);
        Robot_addLink(r, 0, 0 ,0, pi2);
        Robot_addLink(r, 0, 0.328 ,0, -pi2);
        Robot_addLink(r, 0, 0 ,0, pi2);
        Robot_addLink(r, 0, 0.2765 ,0, -pi2);
        Robot_addLink(r, 0, 0 ,0, pi2);
        Robot_addLink(r, 0, 0.40049 ,0, 0);
        Cartesian_velocity_controller
      Cartesian_velocity_controller(r, Kpv, Kiv, Kdv, T)
      ;
        Cartesian_velocity_controller.control
      ();
}
Variable Documentation
const double pi = 3.141592654
Internal.
Definition at line 33 of file cartesian_velocity_controller.cpp.
const double pi2 = 1.57079632679489655
Definition at line 34 of file cartesian_velocity_controller.cpp.