Cartesian_pose_controller Class Reference
#include `cartesian_pose_controller.h`
Public Member Functions
Cartesian_pose_controller (std::vector< double > initialPositions, Robot *r, double KP[], double KI[], double KD[], double T)
~Cartesian_pose_controller ()
void control ()
void updateReferencesCallback (const schunk_msgs::Positions::ConstPtr &msg)
Receive schunk_msgs::Velocities and updates this Cartesian_controller's internal variables.
Private Member Functions
bool printPose ()
void updateReferences (double ref_gain)
Calls the last velocity callback and updates the PGMATRIX D_ref with the updated values.
Private Attributes
ros::NodeHandle reference_updater_nh
ros::CallbackQueue reference_updater_queue
ros::Subscriber reference_updater_subscriber
ros::Publisher schunk_posePublisher
ros::NodeHandle schunk_pose_nh
ros::CallbackQueue schunk_pose_queue
schunk_msgs::Positions schunk_pose
std::vector< double > initialPositions
Additional Inherited Members
Detailed Description
Definition at line 5 of file cartesian_pose_controller.h.
Constructor & Destructor Documentation
Cartesian_pose_controller::Cartesian_pose_controller (std::vector< double > initialPositions, Robot * r, double KP[], double KI[], double KD[], double T)
Definition at line 289 of file cartesian_pose_controller.cpp.
References initialPositions, reference_updater_nh, reference_updater_queue, reference_updater_subscriber, Cartesian_controller::ros_pub_buffer, schunk_pose, schunk_pose_nh, schunk_pose_queue, schunk_posePublisher, and updateReferencesCallback().
                                                                               
                                                                        :
      Cartesian_controller(r,8,KP,KI,KD,T){
        this->initialPositions = initialPositions
      ;
        /******************************
                 PUBLIC VARIABLES
        *******************************/
        //Positiosn vector
        for(int j=0;j<8;j++){
                this->schunk_pose.positions.push_back(0.0);
        }
        /******************************
                  ROS VARIABLES
        *******************************/
        //Set Queues
        this->reference_updater_nh.setCallbackQueue(&this->
      reference_updater_queue);
        this->schunk_pose_nh.setCallbackQueue(&this->
      schunk_pose_queue);
        //Subscriber and queue init.
        this->reference_updater_subscriber
      = this->reference_updater_nh.subscribe("
      schunk_reference_positions", ros_pub_buffer, &
      Cartesian_pose_controller::updateReferencesCallback
      , this);
        //Publisher
        this->schunk_posePublisher = this->schunk_pose_nh
      .advertise<schunk_msgs::Positions>("schunk_endeffector_pose", ros_pub_buffer
      );
}
Cartesian_pose_controller::~Cartesian_pose_controller ()
Definition at line 285 of file cartesian_pose_controller.cpp.
                                                     {
}
Member Function Documentation
void Cartesian_pose_controller::control () [virtual]
Measure Position and Speed
Recalculation of measured data.
Implements Cartesian_controller.
Definition at line 72 of file cartesian_pose_controller.cpp.
References Cartesian_controller::aux1, Cartesian_controller::aux2, Cartesian_controller::aux3, Cartesian_controller::changeSchunkMode(), Cartesian_controller::controlCleanUp(), DQ::d, Cartesian_controller::D, Cartesian_controller::D_ref, DQ_free(), Cartesian_controller::DThetas, Cartesian_controller::Err, Cartesian_controller::Err_ant, Cartesian_controller::Err_int, FALSE, Cartesian_controller::getSchunkPositionsAndVelocitiesAndUpdateThetasAndDThetas(), initialPositions, Cartesian_controller::Kd, Cartesian_controller::Ki, Cartesian_controller::Kp, DQ::p, PGMATRIX_ADD_COPY_FREE(), PGMATRIX_DAMPED_LEASTSQUARES_PSEUDOINVERSE(), PGMATRIX_DATA, PGMATRIX_FREE(), PGMATRIX_MULTIPLY_CONST_COPY_FREE(), PGMATRIX_MULTIPLY_COPY_FREE(), PGMATRIX_SET_COLUMN_BY_DQ(), PGMATRIX_SUBTRACT_COPY_FREE(), printPose(), Cartesian_controller::r, Robot_FKM(), Robot_getAJacobian(), Robot_updateLinksThetasByMatrix(), schunk_pose, Cartesian_controller::sendJointPositionsToSchunk(), Cartesian_controller::setSchunkVelocitiesAndSend(), Cartesian_controller::SJ, Cartesian_controller::T, Cartesian_controller::Thetas, TRUE, updateReferences(), and Q::v.
Referenced by main().
                                       {
        /******************************
                                ROS INIT
        *******************************/
        //Ros rate
        ros::Rate ros_rate(1/T);
        /*****************************
           CHANGE SCHUNK MODE TO ASSURE POSITION CONTROL
         *****************************/
        ros::service::waitForService("schunk_set_control_mode");
        ROS_INFO_STREAM("Changing Schunk's Control Mode");
        if(!changeSchunkMode(CONTROL_MODE_POSITION)){return;}
        ROS_INFO_STREAM("Mode Changed to position!");
        ROS_INFO_STREAM("Sending initial position.");
        sendJointPositionsToSchunk(this->
      initialPositions);
        ROS_INFO_STREAM("Sent! Sleeping...");
        sleep(20);
        /*****************************
           CHANGE SCHUNK MODE TO ASSURE VELOCITY CONTROL
         *****************************/
        ROS_INFO_STREAM("Changing Schunk's Control Mode");
        if(!changeSchunkMode(CONTROL_MODE_VELOCITY)){return;}
        ROS_INFO_STREAM("Mode Changed to velocity!");
        /*****************************
           UPDATES SCHUNK'S INITIAL POSITION AND VELOCITY
         *****************************/
        ROS_INFO_STREAM("Where is Schunk and how fast is it?");
        if(!getSchunkPositionsAndVelocitiesAndUpdateThetasAndDThetas
      ()){return;}
        ROS_INFO_STREAM("Schunk found!");
        /******************************
        PRIVATE VARIABLE INITIALIZATION
        *******************************/
        //Update Robot Object. Thetas were updated.
        Robot_updateLinksThetasByMatrix(r,
      Thetas);
        //Update end effectors pose
        DQ* eep = Robot_FKM(r);
        //Current end effectors pose is now the reference pose.
        for(int j=0;j<4;j++){
                this->schunk_pose.positions[j] = eep->p->v[j];
                this->schunk_pose.positions[j+4] = eep->d->v[j];
        }
        //Update D_ref and D
        updateReferences(1);
        PGMATRIX_SET_COLUMN_BY_DQ(D, 1, eep);
        //Here, both D and D_ref should be the same
        for(int j=0;j<8;j++){
                ROS_INFO_STREAM("Values are : D=" << PGMATRIX_DATA
      (D,j+1,1) << " and D_ref=" << PGMATRIX_DATA(D_ref,j+1,1));
        }
        //Jacobians
        SJ = Robot_getAJacobian(r);
        /******************************
                        LOOP
        *******************************/
        ROS_INFO_STREAM("Take a deep breath and GO!");
        //Take a deep breath and GO
        ros_rate.sleep();
        while(ros::ok()){
                //Last Error
                PGMATRIX_FREE(Err_ant);
                Err_ant = Err;
                /******************************
                        /END GET NEW REFERENCES
                *******************************/
                //Current Error
                Err = PGMATRIX_SUBTRACT_COPY_FREE
      (D_ref,D,FALSE,FALSE);
                //Error Integral
                aux1 = PGMATRIX_MULTIPLY_CONST_COPY_FREE
      (Err,T,FALSE);
                Err_int = PGMATRIX_ADD_COPY_FREE(
      Err_int,aux1,TRUE,TRUE);
                //Derivative aux1 = Kd*(Err-Err_ant)*(1/T)
                aux1 = PGMATRIX_SUBTRACT_COPY_FREE
      (Err,Err_ant,FALSE,FALSE);
                aux1 = PGMATRIX_MULTIPLY_COPY_FREE
      (Kd,aux1,FALSE,TRUE);
                aux1 = PGMATRIX_MULTIPLY_CONST_COPY_FREE
      (aux1,(1/T),TRUE);
                //Integral aux2 = Ki*(Err_int)
                aux2 = PGMATRIX_MULTIPLY_COPY_FREE
      (Ki,Err_int,FALSE,FALSE);
                //Proportional aux3 = Kp*(Err)
                aux3 = PGMATRIX_MULTIPLY_COPY_FREE
      (Kp,Err,FALSE,FALSE);
                //Error Sum aux1 = Kd*(Err-Err_ant)*(1/T) + Ki*(Err_int) +
       Kp*(Err)
                aux1 = PGMATRIX_ADD_COPY_FREE(aux1
      ,aux2,TRUE,TRUE);
                aux1 = PGMATRIX_ADD_COPY_FREE(aux1
      ,aux3,TRUE,TRUE);
                //Pseudo Inverse Calculation
                aux2 = PGMATRIX_DAMPED_LEASTSQUARES_PSEUDOINVERSE
      (SJ,0.01);
                //New DThetas = pinv(SJ)*(Error Sum)
                PGMATRIX_FREE(DThetas);
                DThetas = PGMATRIX_MULTIPLY_COPY_FREE
      (aux2,aux1,TRUE,TRUE);
                /******************************
                         GET NEW REFERENCES
                *******************************/
                //Receive callback to after update references
                updateReferences(1);
                /******************************
                        COMUNICATE WITH SCHUNK
                *******************************/
                //Sends information to robot to move, then wait and measure
                setSchunkVelocitiesAndSend(0.01);
                //Wait
                ros_rate.sleep();
                //Position and Velocities, THETAS AND DTHETAS ARE UPDATED
                if(!getSchunkPositionsAndVelocitiesAndUpdateThetasAndDThetas
      ()){return;}
                printPose();
                /******************************
                /END COMUNICATE WITH SCHUNK
                *******************************/
                //Updates Robot's Link's Thetas with current position
                Robot_updateLinksThetasByMatrix(
      r,Thetas);
                //Updates Jacobian with new position
                PGMATRIX_FREE(SJ);
                SJ = Robot_getAJacobian(r);
                //End effectors pose
                DQ_free(eep);
                eep = Robot_FKM(r);
                PGMATRIX_SET_COLUMN_BY_DQ(D, 1, eep);
        }
        /******************************
                        CLEAN UP
        *******************************/
        controlCleanUp();
        return;
}
bool Cartesian_pose_controller::printPose () [private]
Definition at line 223 of file cartesian_pose_controller.cpp.
References Cartesian_controller::D, DQ_create(), DQ_free(), DQ_getR(), DQ_getT(), PGMATRIX_DATA, Q_free(), schunk_pose, schunk_pose_queue, schunk_posePublisher, and Q::v.
Referenced by control().
                                         {
        //for(int j=0;j<8;j++){
        // schunk_pose.positions[j] = PGMATRIX_DATA(D,j+1,1);
        //}
        //Temp TODO: DELETE ALL THE STUFF BETWEEN ME
        DQ* dq = DQ_create(PGMATRIX_DATA(D,1,1),
                        PGMATRIX_DATA(D,2,1),
                        PGMATRIX_DATA(D,3,1),
                        PGMATRIX_DATA(D,4,1),
                        PGMATRIX_DATA(D,5,1),
                        PGMATRIX_DATA(D,6,1),
                        PGMATRIX_DATA(D,7,1),
                        PGMATRIX_DATA(D,8,1));
        Q* trans = DQ_getT(dq);
        Q* rot = DQ_getR(dq);
        for(int j=0;j<4;j++){
                schunk_pose.positions[j] = trans->v[j];
                schunk_pose.positions[j+4] = rot->v[j];
        }
        DQ_free(dq);
        Q_free(trans);
        Q_free(rot);
        //TODO: AND ME
        schunk_posePublisher.publish(schunk_pose
      );
        schunk_pose_queue.callAvailable(ros::WallDuration(0));
        return true;
}
void Cartesian_pose_controller::updateReferences (double ref_gain) [inline], [private]
Calls the last velocity callback and updates the PGMATRIX D_ref with the updated values.
Definition at line 257 of file cartesian_pose_controller.cpp.
References Cartesian_controller::D_ref, PGMATRIX_DATA, reference_updater_queue, and schunk_pose.
Referenced by control().
                                                                      {
        //Calls one of the velocities callbacks in the queue.
        reference_updater_queue.callAvailable(
      ros::WallDuration(0));
        //Update references matrix
        for(int j=0;j<8;j++){
                PGMATRIX_DATA(D_ref,j+1,1) = ref_gain*this->
      schunk_pose.positions[j];
        }
}
void Cartesian_pose_controller::updateReferencesCallback (const schunk_msgs::Positions::ConstPtr & msg)
Receive schunk_msgs::Velocities and updates this Cartesian_controller's internal variables.
Definition at line 272 of file cartesian_pose_controller.cpp.
References schunk_pose.
Referenced by Cartesian_pose_controller().
                                                                               
                      {
        if(msg->positions.size() != 8){
                ROS_ERROR_STREAM("Dualquaternion being sent to
       schunk_reference_positions's topic is not size 8");
                return;
        }
        for(int i = 0; i < 8; i++){
                this->schunk_pose.positions[i] = msg->positions[i];
        }
}
Field Documentation
std::vector<double> Cartesian_pose_controller::initialPositions [private]
Definition at line 23 of file cartesian_pose_controller.h.
Referenced by Cartesian_pose_controller(), and control().
ros::NodeHandle Cartesian_pose_controller::reference_updater_nh [private]
Definition at line 12 of file cartesian_pose_controller.h.
Referenced by Cartesian_pose_controller().
ros::CallbackQueue Cartesian_pose_controller::reference_updater_queue [private]
Definition at line 13 of file cartesian_pose_controller.h.
Referenced by Cartesian_pose_controller(), and updateReferences().
ros::Subscriber Cartesian_pose_controller::reference_updater_subscriber [private]
Definition at line 14 of file cartesian_pose_controller.h.
Referenced by Cartesian_pose_controller().
schunk_msgs::Positions Cartesian_pose_controller::schunk_pose [private]
Definition at line 20 of file cartesian_pose_controller.h.
Referenced by Cartesian_pose_controller(), control(), printPose(), updateReferences(), and updateReferencesCallback().
ros::NodeHandle Cartesian_pose_controller::schunk_pose_nh [private]
Definition at line 18 of file cartesian_pose_controller.h.
Referenced by Cartesian_pose_controller().
ros::CallbackQueue Cartesian_pose_controller::schunk_pose_queue [private]
Definition at line 19 of file cartesian_pose_controller.h.
Referenced by Cartesian_pose_controller(), and printPose().
ros::Publisher Cartesian_pose_controller::schunk_posePublisher [private]
Definition at line 17 of file cartesian_pose_controller.h.
Referenced by Cartesian_pose_controller(), and printPose().
The documentation for this class was generated from the following files:
schunk_high/include/schunk_high/cartesian_pose_controller.h
schunk_high/src/cartesian_pose_controller.cpp