Cartesian_velocity_controller Class Reference
#include `cartesian_velocity_controller.h`
Public Member Functions
Cartesian_velocity_controller (Robot *r, double KP[], double KI[], double KD[], double T)
~Cartesian_velocity_controller ()
void control ()
void referenceUpdateCallback (const schunk_msgs::Velocities::ConstPtr &msg)
Receive schunk_msgs::Velocities and updates this Cartesian_velocity_controller's internal variables.
Data Fields
std::vector< double > references
Protected Member Functions
bool printVel ()
void updateReferences (double ref_gain, double ref_gain2)
Calls the last velocity callback and updates the PGMATRIX D_ref with the updated values.
Protected Attributes
ros::NodeHandle reference_updater_nh
ros::CallbackQueue reference_updater_queue
ros::Subscriber reference_updater_subscriber
ros::NodeHandle endEffector_vel_nh
ros::CallbackQueue endEffector_vel_queue
ros::Publisher endEffector_vel_pub
schunk_msgs::Velocities endEffector_vel
Detailed Description
Definition at line 8 of file cartesian_velocity_controller.h.
Constructor & Destructor Documentation
Cartesian_velocity_controller::Cartesian_velocity_controller (Robot * r, double KP[], double KI[], double KD[], double T)
Definition at line 253 of file cartesian_velocity_controller.cpp.
References Robot::dofs, endEffector_vel, endEffector_vel_nh, endEffector_vel_pub, endEffector_vel_queue, reference_updater_nh, reference_updater_queue, reference_updater_subscriber, references, referenceUpdateCallback(), and Cartesian_controller::ros_pub_buffer.
                                                                                                           
                : Cartesian_controller(r,6,KP,KI,KD,T){
        //Reference Velocities Buffer
        for(int j=0;j<r->dofs;j++){
                this->references.push_back(0.0);
        }
        //Initialize endEffector_vel msg
        for(int j=0;j<6;j++){
                endEffector_vel.velocities.push_back(0.0);
        }
        //Set Queues
        this->reference_updater_nh.setCallbackQueue(&this->
      reference_updater_queue);
        this->endEffector_vel_nh.setCallbackQueue(&this->
      endEffector_vel_queue);
        //Subscriber and queue init.
        this->reference_updater_subscriber = this->
      reference_updater_nh.subscribe("schunk_cartesian_velocities_control",
      ros_pub_buffer, &
      Cartesian_velocity_controller::referenceUpdateCallback
      , this);
        //Publisher
        this->endEffector_vel_pub = this->
      endEffector_vel_nh.advertise<schunk_msgs::Velocities>("schunk_endeffector_velocities",
      ros_pub_buffer);
}
Cartesian_velocity_controller::~Cartesian_velocity_controller ()
Definition at line 249 of file cartesian_velocity_controller.cpp.
                                                             {
}
Member Function Documentation
void Cartesian_velocity_controller::control () [virtual]
Measure Position and Speed
Recalculation of measured data.
Implements Cartesian_controller.
Definition at line 66 of file cartesian_velocity_controller.cpp.
References Cartesian_controller::aux1, Cartesian_controller::aux2, Cartesian_controller::aux3, Cartesian_controller::changeSchunkMode(), Cartesian_controller::controlCleanUp(), Cartesian_controller::D, Cartesian_controller::D_ref, Cartesian_controller::DThetas, Cartesian_controller::end_control, Cartesian_controller::Err, Cartesian_controller::Err_ant, Cartesian_controller::Err_int, FALSE, Cartesian_controller::getSchunkPositionsAndVelocitiesAndUpdateThetasAndDThetas(), Cartesian_controller::Kd, Cartesian_controller::Ki, Cartesian_controller::Kp, PGMATRIX_ADD_COPY_FREE(), PGMATRIX_DAMPED_LEASTSQUARES_PSEUDOINVERSE(), PGMATRIX_FREE(), PGMATRIX_MULTIPLY_CONST_COPY_FREE(), PGMATRIX_MULTIPLY_COPY_FREE(), PGMATRIX_SUBTRACT_COPY_FREE(), printVel(), Cartesian_controller::r, Robot_getGJacobian(), Robot_updateLinksThetasByMatrix(), Cartesian_controller::setSchunkVelocitiesAndSend(), Cartesian_controller::SJ, Cartesian_controller::T, Cartesian_controller::Thetas, TRUE, and updateReferences().
Referenced by main().
                                           {
        /******************************
                                ROS INIT
        *******************************/
        //Ros rate
        ros::Rate ros_rate(1/T);
        /*****************************
           CHANGE SCHUNK MODE TO ASSURE VELOCITY CONTROL
         *****************************/
        //Waits for the service to be available
        ros::service::waitForService("schunk_set_control_mode");
        ROS_INFO_STREAM("Changing Schunk's Control Mode");
        if(!changeSchunkMode(CONTROL_MODE_VELOCITY)){return;}
        ROS_INFO_STREAM("Mode Changed!");
        /*****************************
           UPDATES SCHUNK'S INITIAL POSITION AND VELOCITY
         *****************************/
        ROS_INFO_STREAM("Where is Schunk and how fast is it?");
        if(!getSchunkPositionsAndVelocitiesAndUpdateThetasAndDThetas
      ()){return;}
        ROS_INFO_STREAM("Schunk found!");
        /******************************
        PRIVATE VARIABLE INITIALIZATION
        *******************************/
        //Update Robot Object
        Robot_updateLinksThetasByMatrix(r,Thetas);
        //Jacobians
        SJ = Robot_getGJacobian(r);
        /******************************
                        LOOP
        *******************************/
        ROS_INFO_STREAM("Starting!");
        //Take a deep breath and GO
        ros_rate.sleep();
        while(!end_control){
                //Last Error
                PGMATRIX_FREE(Err_ant);
                Err_ant = Err;
                /******************************
                        /END GET NEW REFERENCES
                *******************************/
                //Current Error
                Err = PGMATRIX_SUBTRACT_COPY_FREE(
      D_ref,D,FALSE,FALSE);
                //Error Integral
                aux1 = PGMATRIX_MULTIPLY_CONST_COPY_FREE(
      Err,T,FALSE);
                Err_int = PGMATRIX_ADD_COPY_FREE(
      Err_int,aux1,TRUE,TRUE);
                //Derivative aux1 = Kd*(Err-Err_ant)*(1/T)
                aux1 = PGMATRIX_SUBTRACT_COPY_FREE(
      Err,Err_ant,FALSE,FALSE);
                aux1 = PGMATRIX_MULTIPLY_COPY_FREE(
      Kd,aux1,FALSE,TRUE);
                aux1 = PGMATRIX_MULTIPLY_CONST_COPY_FREE(
      aux1,(1/T),TRUE);
                //Integral aux2 = Ki*(Err_int)
                aux2 = PGMATRIX_MULTIPLY_COPY_FREE(
      Ki,Err_int,FALSE,FALSE);
                //Proportional aux3 = Kp*(Err)
                aux3 = PGMATRIX_MULTIPLY_COPY_FREE(
      Kp,Err,FALSE,FALSE);
                //Error Sum aux1 = Kd*(Err-Err_ant)*(1/T) + Ki*(Err_int) + Kp*(Err)
                aux1 = PGMATRIX_ADD_COPY_FREE(aux1,
      aux2,TRUE,TRUE);
                aux1 = PGMATRIX_ADD_COPY_FREE(aux1,
      aux3,TRUE,TRUE);
                //Pseudo Inverse Calculation
                aux2 = PGMATRIX_DAMPED_LEASTSQUARES_PSEUDOINVERSE
      (SJ,0.01);
                //New DThetas = pinv(SJ)*(Error Sum)
                PGMATRIX_FREE(DThetas);
                DThetas = PGMATRIX_MULTIPLY_COPY_FREE(
      aux2,aux1,TRUE,TRUE);
                /******************************
                         GET NEW REFERENCES
                *******************************/
                //Receive callback to after update references
                updateReferences(0.1,0.35); //Refs should be received as 1
                /******************************
                        COMUNICATE WITH SCHUNK
                *******************************/
                //Sends information to robot to move, then wait and measure
                setSchunkVelocitiesAndSend(0.5);
                //Wait
                ros_rate.sleep();
                //Position and Velocities, THETAS AND DTHETAS ARE UPDATED
                if(!getSchunkPositionsAndVelocitiesAndUpdateThetasAndDThetas
      ()){return;}
                //Print
                printVel();
                /******************************
                /END COMUNICATE WITH SCHUNK
                *******************************/
                //Updates Robot's Link's Thetas with current position
                Robot_updateLinksThetasByMatrix(r,
      Thetas);
                //Updates Jacobian with new position
                PGMATRIX_FREE(SJ);
                SJ = Robot_getGJacobian(r);
                //End effectors 6DOF velocity
                PGMATRIX_FREE(D);
                D = PGMATRIX_MULTIPLY_COPY_FREE(SJ,
      DThetas,FALSE,FALSE);
        }
        /******************************
                        CLEAN UP
        *******************************/
        controlCleanUp();
        return;
}
bool Cartesian_velocity_controller::printVel () [inline], [protected]
Definition at line 196 of file cartesian_velocity_controller.cpp.
References endEffector_vel, endEffector_vel_pub, endEffector_vel_queue, Cartesian_controller::Err, and PGMATRIX_DATA.
Referenced by control().
                                                   {
        for(int j=0;j<6;j++){
                endEffector_vel.velocities[j] = PGMATRIX_DATA(
      Err,j+1,1);
        }
        //Updates End Effetor's Header Timestamp
        endEffector_vel.header.stamp = ros::Time::now();
        endEffector_vel_pub.publish(endEffector_vel);
        endEffector_vel_queue.callAvailable(ros::WallDuration(0));
        return true;
}
void Cartesian_velocity_controller::referenceUpdateCallback (const schunk_msgs::Velocities::ConstPtr & msg)
Receive schunk_msgs::Velocities and updates this Cartesian_velocity_controller's internal variables.
Should be received as references in the interval [-1.0,1.0]
Definition at line 232 of file cartesian_velocity_controller.cpp.
References references, and Cartesian_controller::stopSchunk().
Referenced by Cartesian_velocity_controller().
                                                                                                   {
        if(msg->velocities.size() != 6){
                ROS_ERROR_STREAM("Velocity being sent to cartesian_velocity_control's topic is not size 6")
      ;
                stopSchunk();
                return;
        }
        for(int i = 0; i < 6; i++){
                if(this->references[i]> 1.0 || this->references[i]< -1.0){
                        ROS_ERROR_STREAM("Reference sent bigger than 1.0 or lower than -1.0.");
                        stopSchunk();
                        return;
                }
                this->references[i] = msg->velocities[i];
        }
}
void Cartesian_velocity_controller::updateReferences (double ref_gain, double ref_gain2) [inline], [protected]
Calls the last velocity callback and updates the PGMATRIX D_ref with the updated values.
Definition at line 213 of file cartesian_velocity_controller.cpp.
References Cartesian_controller::D_ref, PGMATRIX_DATA, reference_updater_queue, and references.
Referenced by control().
                                                                                            {
        //Calls one of the velocities callbacks in the queue.
        reference_updater_queue.callAvailable(ros::WallDuration(0));
        //Update references matrix
        for(int j=0;j<3;j++){
                PGMATRIX_DATA(D_ref,j+1,1) = ref_gain*this->
      references[j];
        }
        for(int j=3;j<6;j++){
                PGMATRIX_DATA(D_ref,j+1,1) = ref_gain2*this->
      references[j];
        }
}
Field Documentation
schunk_msgs::Velocities Cartesian_velocity_controller::endEffector_vel [protected]
Definition at line 24 of file cartesian_velocity_controller.h.
Referenced by Cartesian_velocity_controller(), and printVel().
ros::NodeHandle Cartesian_velocity_controller::endEffector_vel_nh [protected]
Definition at line 20 of file cartesian_velocity_controller.h.
Referenced by Cartesian_velocity_controller().
ros::Publisher Cartesian_velocity_controller::endEffector_vel_pub [protected]
Definition at line 23 of file cartesian_velocity_controller.h.
Referenced by Cartesian_velocity_controller(), and printVel().
ros::CallbackQueue Cartesian_velocity_controller::endEffector_vel_queue [protected]
Definition at line 21 of file cartesian_velocity_controller.h.
Referenced by Cartesian_velocity_controller(), and printVel().
ros::NodeHandle Cartesian_velocity_controller::reference_updater_nh [protected]
Definition at line 14 of file cartesian_velocity_controller.h.
Referenced by Cartesian_velocity_controller().
ros::CallbackQueue Cartesian_velocity_controller::reference_updater_queue [protected]
Definition at line 15 of file cartesian_velocity_controller.h.
Referenced by Cartesian_velocity_controller(), and updateReferences().
ros::Subscriber Cartesian_velocity_controller::reference_updater_subscriber [protected]
Definition at line 17 of file cartesian_velocity_controller.h.
Referenced by Cartesian_velocity_controller().
std::vector<double> Cartesian_velocity_controller::references
Definition at line 46 of file cartesian_velocity_controller.h.
Referenced by Cartesian_velocity_controller(), referenceUpdateCallback(), and updateReferences().
The documentation for this class was generated from the following files:
schunk_high/include/schunk_high/cartesian_velocity_controller.h
schunk_high/src/cartesian_velocity_controller.cpp