CommunicationV0/spi_functions.h File Reference
#include <stdint.h>
*
#include <unistd.h>
*
#include <stdio.h>
*
#include <stdlib.h>
*
#include <getopt.h>
*
#include <fcntl.h>
*
#include <sys/ioctl.h>
*
#include <linux/types.h>
*
#include <linux/spi/spidev.h>
*
Macros
#define ARRAY_SIZE(a) (sizeof(a) / sizeof((a)[0]))
Functions
int spi_init (uint8_t mode, uint32_t speed, uint8_t cs)
spi Functions to deal communication by SPI protocol
void spi_end (int spi_dev)
TERMINATES SPI DEVICE.
short int adc_read (int spi_dev, uint8_t ch, uint8_t sgl)
uint8_t dac_write (int spi_dev, uint8_t ch, uint8_t _shdn, unsigned short int data)
WRITE DATA TO D/A CONVERTER MCP3922.
Macro Definition Documentation
#define ARRAY_SIZE(a) (sizeof(a) / sizeof((a)[0]))
Definition at line 29 of file spi_functions.h.
Function Documentation
short int adc_read (int spi_dev, uint8_t ch, uint8_t sgl)
Definition at line 165 of file spi_functions.c.
References ARRAY_SIZE, delay, and pabort().
{
        int ret;
        if(ch<0 || ch>7) return pabort("Wrong channel value for ADC");
        uint8_t tx[] = {(ch>>2)|(sgl<<1)|0x04, ch<<6, 0x00,};
        uint8_t rx[ARRAY_SIZE(tx)] = {0, };
        struct spi_ioc_transfer tr = {
                .tx_buf = (unsigned long)tx,
                .rx_buf = (unsigned long)rx,
                .len = ARRAY_SIZE(tx),
                .delay_usecs = delay,
                .speed_hz = 0,
                .bits_per_word = 0,
        };
        ret = ioctl(spi_dev, SPI_IOC_MESSAGE(1), &tr);
        if (ret == 1) return pabort("can't send spi message");
//printf("\nRx = 0x%X 0x%X 0x%X\n",rx[0],rx[1],rx[2]);
//printf("\nValor retornado pelo conversor AD:
       %d\n\n",rx[2]+((rx[1]&0x0F)<<8));
        return rx[2]+((rx[1]&0x0F)<<8);
}
uint8_t dac_write (int spi_dev, uint8_t ch, uint8_t _shdn, unsigned short int data)
WRITE DATA TO D/A CONVERTER MCP3922.
Definition at line 200 of file spi_functions.c.
References ARRAY_SIZE, delay, FAILURE, and pabort().
Referenced by actuate().
{
        int ret;
        union txunion{
        unsigned short int data16;
        uint8_t data8[2];
        }txunion;
        if(ch<0 || ch>1) return FAILURE;//pabort("Wrong channel value
       for DAC");
        if(data>4095) return FAILURE;//pabort("Value exceeded for
       DAC");
        txunion.data16 = 0x6000|(ch<<15)|(_shdn<<12)|(data&0x0FFF);
        uint8_t tx[] = {txunion.data8[1], txunion.data8[0]};
        uint8_t rx[ARRAY_SIZE(tx)] = {0, };
        struct spi_ioc_transfer tr = {
                .tx_buf = (unsigned long)tx,
                .rx_buf = (unsigned long)rx,
                .len = ARRAY_SIZE(tx),
                .delay_usecs = delay,
                .speed_hz = 0,
                .bits_per_word = 0,
        };
        ret = ioctl(spi_dev, SPI_IOC_MESSAGE(1), &tr);
        if (ret == 1) return FAILURE;//pabort("can't send spi message");
//printf("\nRx = 0x%X 0x%X 0x%X\n",rx[0],rx[1],rx[2]);
//printf("\nValor retornado pelo conversor AD:
       %d\n\n",rx[2]+((rx[1]&0x0F)<<8));
        return 1;
}
void spi_end (int spi_dev)
TERMINATES SPI DEVICE.
Definition at line 166 of file spi_functions.c.
{
  close(spi_dev);
  return;
}
int spi_init (uint8_t mode, uint32_t speed, uint8_t cs)
spi Functions to deal communication by SPI protocol
INITIALIZE SPI DEVICE
Definition at line 100 of file spi_functions.c.
References bits, pabort(), and spi_dev.
Referenced by devices_init().
{
        int ret = 0;
        int spi_dev;
        char *device;
        //parse_opts(argc, argv);
        /*
         * chose chipselect:
         */
        switch(cs){
          case 0:
            device = "/dev/spidev1.0";
            break;
          case 1:
            device = "/dev/spidev1.1";
            break;
          default:
            return pabort("invalid chip select value");
        }
            
        
        spi_dev = open(device, O_RDWR);
        if (spi_dev < 0)
                return pabort("can't open device");
//printf("\nspi_dev = %d\n",spi_dev);
        /*
         * spi mode
         */
        ret = ioctl(spi_dev, SPI_IOC_WR_MODE, &mode);
        if (ret == -1)
                return pabort("can't set spi mode");
        ret = ioctl(spi_dev, SPI_IOC_RD_MODE, &mode);
        if (ret == -1)
                return pabort("can't get spi mode");
        /*
         * bits per word
         */
        ret = ioctl(spi_dev, SPI_IOC_WR_BITS_PER_WORD, &bits);
        if (ret == -1)
                return pabort("can't set bits per word");
        ret = ioctl(spi_dev, SPI_IOC_RD_BITS_PER_WORD, &bits);
        if (ret == -1)
                return pabort("can't get bits per word");
        /*
         * max speed hz
         */
        ret = ioctl(spi_dev, SPI_IOC_WR_MAX_SPEED_HZ, &speed);
        if (ret == -1)
                return pabort("can't set max speed hz");
        ret = ioctl(spi_dev, SPI_IOC_RD_MAX_SPEED_HZ, &speed);
        if (ret == -1)
                return pabort("can't get max speed hz");
        //printf("spi mode: %d\n", mode);
        //printf("bits per word: %d\n", bits);
        //printf("max speed: %d Hz (%d KHz)\n", speed, speed/1000);
        return spi_dev;
}