CommunicationV0/gpio_functions.h File Reference
#include <stdio.h>
*
#include <stdlib.h>
*
#include <string.h>
*
#include <stdint.h>
*
#include <sys/types.h>
*
Functions
int gpio_read (uint8_t gpio)
int gpio_write (uint8_t gpio, uint8_t value)
int gpio_f_write (uint8_t gpio, uint8_t value)
Function Documentation
int gpio_f_write (uint8_t gpio, uint8_t value)
Definition at line 61 of file gpio_functions.c.
References SUCCESS.
{
  FILE *fp_gpio;
  char path[30];
  char fp_value;
  
  sprintf(path,"/sys/class/gpio/gpio%d/value",gpio);
  fp_gpio=fopen(path,"w");
  rewind(fp_gpio);
  fp_value=0x30+value;
  fwrite(&fp_value, sizeof(char), 1, fp_gpio);
  fclose(fp_gpio);
  return SUCCESS;
}
int gpio_read (uint8_t gpio)
Definition at line 3 of file gpio_functions.c.
References FAILURE.
Referenced by dac_shut_down().
{
  FILE *fp_gpio=NULL;
  char path[30];
  char fp_value;
  sprintf(path,"/sys/class/gpio/gpio%d/value",gpio);
  if((fp_gpio=fopen(path,"rb+")) == NULL)
  {
    //printf("Open %s failed\n",path);
    return FAILURE;
  }
  rewind(fp_gpio);
  fread(&fp_value, 1, sizeof(char), fp_gpio);
  fclose(fp_gpio);
  return (uint8_t)fp_value-0x30;
}
int gpio_write (uint8_t gpio, uint8_t value)
Definition at line 21 of file gpio_functions.c.
References FAILURE, and SUCCESS.
Referenced by actuate(), dac_shut_down(), and read_all_data().
{
  FILE *fp_gpio;
  char path[30];
  char fp_read[4];
  char s_out[]="out";
  char fp_write;
// Verifying if GPIO is set as Output
  sprintf(path,"/sys/class/gpio/gpio%d/direction",gpio);
  if((fp_gpio=fopen(path,"r")) == NULL)
  {
    //printf("Open %s failed\n",path);
    return -1;
  }
  rewind(fp_gpio);
  fread(fp_read, 3, sizeof(char), fp_gpio);
  if(strncmp(fp_read,s_out,3))
  {
    //printf("Gpio%d is set as Input. Impossible to write.",gpio);
    return FAILURE;
  }
  fclose(fp_gpio);
// Writing
  sprintf(path,"/sys/class/gpio/gpio%d/value",gpio);
  
  if((fp_gpio=fopen(path,"w")) == NULL)
  {
    //printf("Open %s failed\n",path);
    return FAILURE;
  }
  rewind(fp_gpio);
  fp_write=0x30+value;
  fwrite(&fp_write, sizeof(char), 1, fp_gpio);
  fclose(fp_gpio);
  return SUCCESS;
}