André backup conflitos/communication (Cópia em conflito de André Carvalho 2013-04-26).c File Reference
#include <stdio.h>
*
#include `communication.h`
*
Functions
int devices_init (IMU_PARAM_STRUCT *imu_param, SPI_PARAM_STRUCT *spi_param)
void read_all_data (int i2c_dev, int spi_dev, IMU_DATA_STRUCT *imu_data, EFF_DATA_STRUCT *eff_data)
Variables
int status
Function Documentation
int devices_init (IMU_PARAM_STRUCT * imu_param, SPI_PARAM_STRUCT * spi_param)
Definition at line 7 of file communication (Cópia em conflito de André Carvalho 2013-04-26).c.
References IMU_PARAM_STRUCT::acc, acc_init(), IMU_PARAM_STRUCT::param_gyr::act, ADD_ADXL345, ADD_HMC5883, ADD_ITG3200, IMU_PARAM_STRUCT::param_gyr::clk_source, SPI_PARAM_STRUCT::cs, FAILURE, IMU_PARAM_STRUCT::param_acc::full_res, IMU_PARAM_STRUCT::gyr, gyr_init(), IMU_PARAM_STRUCT::i2c_dev, IMU_PARAM_STRUCT::param_gyr::lpf_bw, IMU_PARAM_STRUCT::mag, mag_init(), IMU_PARAM_STRUCT::param_mag::meas_mode, SPI_PARAM_STRUCT::mode, IMU_PARAM_STRUCT::param_mag::op_mode, IMU_PARAM_STRUCT::param_acc::range, IMU_PARAM_STRUCT::param_mag::range, IMU_PARAM_STRUCT::param_acc::rate, IMU_PARAM_STRUCT::param_gyr::rate, IMU_PARAM_STRUCT::param_mag::rate, IMU_PARAM_STRUCT::param_mag::samples_avg, SPI_PARAM_STRUCT::speed, SPI_PARAM_STRUCT::spi_dev, spi_init(), and SUCCESS.
Referenced by main(), and periodic_task_2().
{
  
  if((imu_param->i2c_dev = open("/dev/i2c-3", O_RDWR))<0)
  {
    perror("Failed to open i2c_dev");
    return FAILURE;
  }
  if ((ioctl(imu_param->i2c_dev, I2C_SLAVE, ADD_HMC5883)) < 0
      ) {
                perror("ioctl(I2C_SLAVE) mag");
                return FAILURE;
  }
  if((mag_init(imu_param->i2c_dev, imu_param->mag.rate,
      imu_param->mag.range, imu_param->mag.samples_avg,
      imu_param->mag.meas_mode, imu_param->mag.op_mode))< 0)
  {
      perror("Error in magnetometer initialization");
      return FAILURE;
  }
  if(ioctl(imu_param->i2c_dev, I2C_SLAVE, ADD_ITG3200) < 0)
      {
                perror("ioctl(I2C_SLAVE) gyr");
                return FAILURE;
  }
  if(gyr_init(imu_param->i2c_dev, imu_param->gyr.rate,
      imu_param->gyr.lpf_bw, imu_param->gyr.clk_source, imu_param
      ->gyr.act)<0)
  {
      perror("Error in gyrometer initialization");
      return FAILURE;
  }
  if ((ioctl(imu_param->i2c_dev, I2C_SLAVE, ADD_ADXL345)) <
      0) {
        perror("ioctl(I2C_SLAVE) acc");
        return FAILURE;
  }
  if(acc_init(imu_param->i2c_dev, imu_param->acc.full_res
      , imu_param->acc.rate, imu_param->acc.range)<0)
  {
        perror("Error in accelerometer initialization");
        return FAILURE;
  }
  if ((spi_param->spi_dev=spi_init(spi_param->mode,spi_param
      ->speed,spi_param->cs))<0)
  {
    perror("Error in SPI device initialization");
    return FAILURE;
  }
  return SUCCESS;
}
void read_all_data (int i2c_dev, int spi_dev, IMU_DATA_STRUCT * imu_data, EFF_DATA_STRUCT * eff_data)
Definition at line 51 of file communication (Cópia em conflito de André Carvalho 2013-04-26).c.
References IMU_DATA_STRUCT::acc, acc_read_all_data(), adc_read(), ADD_ADXL345, ADD_HMC5883, ADD_ITG3200, EFF_DATA_STRUCT::F, FAILURE, IMU_DATA_STRUCT::gyr, gyr_read_all_data(), IMU_DATA_STRUCT::mag, mag_read_all_data(), IMU_DATA_STRUCT::new_data, EFF_DATA_STRUCT::new_data, SUCCESS, IMU_DATA_STRUCT::temp, DATA_XYZ::x, DATA_XYZ::y, and DATA_XYZ::z.
Referenced by main(), and periodic_task_1().
{
  short int data[4];
  int f=0;
  // Read IMU data
  imu_data->new_data=SUCCESS;
  
  if ((ioctl(i2c_dev, I2C_SLAVE, ADD_ADXL345))<0)
        imu_data->new_data=0;
  if((acc_read_all_data(i2c_dev,data))==FAILURE
       )
  {
        imu_data->new_data=0;
        printf("\nimu_data->new_data = %d\n",imu_data->new_data);
        f=1;
  }
  imu_data->acc.x=data[0];
  imu_data->acc.y=data[1];
  imu_data->acc.z=data[2];
  
  if ((ioctl(i2c_dev, I2C_SLAVE, ADD_ITG3200)) < 0)
        imu_data->new_data=0;
  if((gyr_read_all_data(i2c_dev,data))==FAILURE
       )
        imu_data->new_data=0;
  imu_data->gyr.x=data[0];
  imu_data->gyr.y=data[1];
  imu_data->gyr.z=data[2];
  imu_data->temp=data[3];
  
  if ((ioctl(i2c_dev, I2C_SLAVE, ADD_HMC5883)) < 0)
        imu_data->new_data=0;
  if((mag_read_all_data(i2c_dev,data))==FAILURE
       )
        imu_data->new_data=0;
  imu_data->mag.x=data[0];
  imu_data->mag.y=data[1];
  imu_data->mag.z=data[2];
  
  //Read Efforts data
  eff_data->new_data=SUCCESS;
  
  if((adc_read(spi_dev,0,1,data))==FAILURE)
        eff_data->new_data=FAILURE;
  eff_data->F.x=data[0];
  if(f==1)
    printf("imu_data->new_data antes do return= %d\n",imu_data->new_data
      );
  return;
}
Variable Documentation
int status
Definition at line 5 of file communication (Cópia em conflito de André Carvalho 2013-04-26).c.
Referenced by gDataLogger_Init(), main(), threads_linux_init(), threads_linux_timer_function_task_1(), threads_linux_timer_function_task_2(), timer_function_task_1(), and timer_function_task_2().