communication/spi_functions.c File Reference
#include `spi_functions.h`
*
Macros
#define SUCCESS 1
Modified from SPI testing utility (using spidev driver) Linux/Documentation/spi/spidev_test.c.
#define FAILURE 0
Functions
int pabort (const char *s)
int spi_init (uint8_t mode, uint32_t speed, uint8_t cs)
spi Functions to deal communication by SPI protocol
void spi_end (int spi_dev)
TERMINATES SPI DEVICE.
int adc_read (int spi_dev, uint8_t ch, uint8_t sgl, short int *data)
READ DATA FROM A/D CONVERTER MCP3208.
int dac_write (int spi_dev, uint8_t ch, uint8_t _shdn, unsigned short int data)
WRITE DATA TO D/A CONVERTER MCP3922.
int spi_trans_bytes (int spi_dev, uint8_t *send, uint8_t *receive, int n)
TRANSFER N BYTES.
Variables
static uint8_t bits = 8
static uint16_t delay
Macro Definition Documentation
#define FAILURE 0
Definition at line 9 of file spi_functions.c.
Referenced by adc_read(), dac_write(), and spi_trans_bytes().
#define SUCCESS 1
Modified from SPI testing utility (using spidev driver) Linux/Documentation/spi/spidev_test.c.
Definition at line 8 of file spi_functions.c.
Referenced by adc_read().
Function Documentation
int adc_read (int spi_dev, uint8_t ch, uint8_t sgl, short int * data)
READ DATA FROM A/D CONVERTER MCP3208.
Parameters
ch Set Channel (0 .. 7)
sgl (0: to single or 1: to pseudo-differencial)
Definition at line 172 of file spi_functions.c.
References ARRAY_SIZE, delay, FAILURE, and SUCCESS.
Referenced by read_all_data().
{
        int ret;
        if(ch<0 || ch>7) return FAILURE;
        uint8_t tx[] = {(ch>>1)|(sgl<<2)|0x08, ch<<7, 0x00,};
        union rxunion{
          int8_t rxs[ARRAY_SIZE(tx)];
          uint8_t rx[ARRAY_SIZE(tx)];
        }rxunion;
        //rxunion.rx={0, };
        struct spi_ioc_transfer tr = {
                .tx_buf = (unsigned long)tx,
                .rx_buf = (unsigned long)rxunion.rx,
                .len = ARRAY_SIZE(tx),
                .delay_usecs = delay,
                .speed_hz = 0,
                .bits_per_word = 0,
        };
        ret = ioctl(spi_dev, SPI_IOC_MESSAGE(1), &tr);
        if (ret == 1) return FAILURE;
//printf("\nRx = 0x%X 0x%X 0x%X\n",rx[0],rx[1],rx[2]);
//printf("\nValor retornado pelo conversor AD:
       %d\n\n",rx[2]+((rx[1]&0x0F)<<8));
        //*data=(short int)(rx[2]+((rxs[1]&0x1F)<<8));
        *data=(short int)(rxunion.rx[2]+((int8_t)(((int8_t)(rxunion.rxs[1]&0
      x1F)) <<3)<<5));
        return SUCCESS;
}
int dac_write (int spi_dev, uint8_t ch, uint8_t _shdn, unsigned short int data)
WRITE DATA TO D/A CONVERTER MCP3922.
Definition at line 200 of file spi_functions.c.
Referenced by actuate().
{
        int ret;
        union txunion{
        unsigned short int data16;
        uint8_t data8[2];
        }txunion;
        if(ch<0 || ch>1) return FAILURE;//pabort("Wrong channel value
       for DAC");
        if(data>4095) return FAILURE;//pabort("Value exceeded for
       DAC");
        txunion.data16 = 0x6000|(ch<<15)|(_shdn<<12)|(data&0x0FFF);
        uint8_t tx[] = {txunion.data8[1], txunion.data8[0]};
        uint8_t rx[ARRAY_SIZE(tx)] = {0, };
        struct spi_ioc_transfer tr = {
                .tx_buf = (unsigned long)tx,
                .rx_buf = (unsigned long)rx,
                .len = ARRAY_SIZE(tx),
                .delay_usecs = delay,
                .speed_hz = 0,
                .bits_per_word = 0,
        };
        ret = ioctl(spi_dev, SPI_IOC_MESSAGE(1), &tr);
        if (ret == 1) return FAILURE;//pabort("can't send spi message");
//printf("\nRx = 0x%X 0x%X 0x%X\n",rx[0],rx[1],rx[2]);
//printf("\nValor retornado pelo conversor AD:
       %d\n\n",rx[2]+((rx[1]&0x0F)<<8));
        return 1;
}
int pabort (const char * s)
Definition at line 11 of file spi_functions.c.
Referenced by adc_read(), dac_write(), and spi_init().
{
        perror(s);
        return -1;
}
void spi_end (int spi_dev)
TERMINATES SPI DEVICE.
Definition at line 166 of file spi_functions.c.
{
  close(spi_dev);
  return;
}
int spi_init (uint8_t mode, uint32_t speed, uint8_t cs)
spi Functions to deal communication by SPI protocol
INITIALIZE SPI DEVICE
Definition at line 100 of file spi_functions.c.
Referenced by devices_init().
{
        int ret = 0;
        int spi_dev;
        char *device;
        //parse_opts(argc, argv);
        /*
         * chose chipselect:
         */
        switch(cs){
          case 0:
            device = "/dev/spidev1.0";
            break;
          case 1:
            device = "/dev/spidev1.1";
            break;
          default:
            return pabort("invalid chip select value");
        }
            
        
        spi_dev = open(device, O_RDWR);
        if (spi_dev < 0)
                return pabort("can't open device");
//printf("\nspi_dev = %d\n",spi_dev);
        /*
         * spi mode
         */
        ret = ioctl(spi_dev, SPI_IOC_WR_MODE, &mode);
        if (ret == -1)
                return pabort("can't set spi mode");
        ret = ioctl(spi_dev, SPI_IOC_RD_MODE, &mode);
        if (ret == -1)
                return pabort("can't get spi mode");
        /*
         * bits per word
         */
        ret = ioctl(spi_dev, SPI_IOC_WR_BITS_PER_WORD, &bits);
        if (ret == -1)
                return pabort("can't set bits per word");
        ret = ioctl(spi_dev, SPI_IOC_RD_BITS_PER_WORD, &bits);
        if (ret == -1)
                return pabort("can't get bits per word");
        /*
         * max speed hz
         */
        ret = ioctl(spi_dev, SPI_IOC_WR_MAX_SPEED_HZ, &speed);
        if (ret == -1)
                return pabort("can't set max speed hz");
        ret = ioctl(spi_dev, SPI_IOC_RD_MAX_SPEED_HZ, &speed);
        if (ret == -1)
                return pabort("can't get max speed hz");
        //printf("spi mode: %d\n", mode);
        //printf("bits per word: %d\n", bits);
        //printf("max speed: %d Hz (%d KHz)\n", speed, speed/1000);
        return spi_dev;
}
int spi_trans_bytes (int spi_dev, uint8_t * send, uint8_t * receive, int n)
TRANSFER N BYTES.
Definition at line 228 of file spi_functions.c.
References delay, and FAILURE.
Referenced by enc_read_pos(), enc_wait_for_ack(), and enc_zero_set().
                                                                      {
         //< define send data
        uint8_t *tx;
        tx = send;
        uint8_t rx[n];
        rx[0] = 0;
        /*
        * Transmitting data (full duplex):
        */
        struct spi_ioc_transfer tr = {
                .tx_buf = (unsigned long)tx,
                .rx_buf = (unsigned long)rx,
                .len = n,
                .delay_usecs = delay,
                .speed_hz = 0,
                .bits_per_word = 0,
        };
        int ret = ioctl(spi_dev, SPI_IOC_MESSAGE(1), &tr);
        //Check transmittion:
        if(ret == 1) return FAILURE;//pabort("can't send spi message");
        *receive = rx[0];//get the received data
        return 1;
}
Variable Documentation
uint8_t bits = 8 [static]
Definition at line 18 of file spi_functions.c.
Referenced by conv_byte_hex_bin(), and spi_init().
uint16_t delay [static]
Definition at line 20 of file spi_functions.c.
Referenced by adc_read(), dac_write(), and spi_trans_bytes().