communication/imu_functions.h File Reference
#include <stdio.h>
*
#include <stdint.h>
*
#include <stdlib.h>
*
#include <string.h>
*
#include <errno.h>
*
#include <unistd.h>
*
#include <sys/types.h>
*
#include <sys/stat.h>
*
#include <sys/ioctl.h>
*
#include <fcntl.h>
*
#include <linux/i2c-dev.h>
*
#include `imu_regs.h`
*
Macros
#define ASCII_0 0x30
#define SUCCESS 1
#define FAILURE -1
#define ADD_ADXL345 0x53
#define ADD_ITG3200 0x68
#define ADD_HMC5883 0x1E
Functions
int acc_write_reg (int i2c_dev, uint8_t reg, uint8_t data)
WRITE TO REGISTER.
uint8_t * acc_read_reg (int i2c_dev, uint8_t reg, uint8_t count)
READ COUNT 8-BIT REGISTER IN SEQUENCE
int acc_init (int i2c_dev, uint8_t full_res, uint16_t rate, uint8_t range)
INITIALIZE ACCELEROMETER.
int acc_read_all_data (int i2c_dev, short int *data)
READ ALL DATA AT ONCE (X, Y and Z)
short int acc_read_data (int i2c_dev, int axis)
READ DATA (X, Y or Z)
char * conv_byte_hex_bin (uint8_t *hvalue)
int acc_read_all_reg (int i2c_dev)
Read all accelerometer data and print in stdio.
int gyr_write_reg (int i2c_dev, uint8_t reg, uint8_t data)
WRITE TO REGISTER.
uint8_t * gyr_read_reg (int i2c_dev, uint8_t reg, uint8_t count)
READ COUNT 8-BIT REGISTER IN SEQUENCE.
int gyr_init (int i2c_dev, float rate, short int lpf_bw, char clk_source, char *act)
INITIALIZE GYROMETER.
int gyr_read_all_data (int i2c_dev, short int *data)
READ ALL DATA AT ONCE (X, Y, Z and T)
short int gyr_read_data (int i2c_dev, int type)
READ DATA (X, Y, Z or T)
int mag_write_reg (int i2c_dev, uint8_t reg, uint8_t data)
WRITE TO REGISTER.
uint8_t * mag_read_reg (int i2c_dev, uint8_t reg, uint8_t count)
READ COUNT 8-BIT REGISTER IN SEQUENCE.
int mag_init (int i2c_dev, uint8_t rate, uint8_t range, uint8_t samples_avg, uint8_t meas_mode, uint8_t op_mode)
INITIALIZE MAGNETOMETER.
int mag_read_all_data (int i2c_dev, short int *data)
READ ALL DATA AT ONCE (X, Y and Z)
short int mag_read_data (int i2c_dev, int axis)
READ DATA (X, Y or Z)
Macro Definition Documentation
#define ADD_ADXL345 0x53
Definition at line 32 of file imu_functions.h.
Referenced by devices_init(), and read_all_data().
#define ADD_HMC5883 0x1E
Definition at line 34 of file imu_functions.h.
Referenced by devices_init(), and read_all_data().
#define ADD_ITG3200 0x68
Definition at line 33 of file imu_functions.h.
Referenced by devices_init(), and read_all_data().
#define ASCII_0 0x30
Definition at line 27 of file imu_functions.h.
Referenced by conv_byte_hex_bin().
#define FAILURE -1
Definition at line 30 of file imu_functions.h.
#define SUCCESS 1
Definition at line 29 of file imu_functions.h.
Function Documentation
char* conv_byte_hex_bin (uint8_t * hvalue)
Definition at line 184 of file acc_functions.c.
{
  char bits[9];
  int i;
  for(i=0; i<8; i++)
  {
    bits[i]=((*hvalue)<<i)>>7+ASCII_0;
  }
  bits[8]='\0';
  return bits;
}
int mag_init (int i2c_dev, uint8_t rate, uint8_t range, uint8_t samples_avg, uint8_t meas_mode, uint8_t op_mode)
INITIALIZE MAGNETOMETER.
Definition at line 53 of file mag_functions.c.
Referenced by devices_init().
{
  uint8_t data=0;
  switch(rate){
    case 15:
      data=0x10;
      break;
    case 0:
      data=0x00;
      break;
    case 1:
      data=0x04;
      break;
    case 3:
      data=0x08;
      break;
    case 7:
      data=0x0C;
      break;
    case 30:
      data=0x14;
      break;
    case 75:
      data=0x18;
      break;
    default:
      perror("Wrong rate value");
      break;
  }
  
  switch(samples_avg){
    case 8:
      data=data|0x60;
      break;
    case 1:
      break;
    case 2:
      data=data|0x20;
      break;
    case 4:
      data=data|0x40;
      break;
    default:
      perror("Wrong samples_avg value");
      break;
  }
  
  data+=meas_mode;
  
  if(mag_write_reg(i2c_dev, MAG_CONFIG_A, data)
      <0){
    perror("Write in Configuration register A unsuccesful");
    return -1;
  }
  
  if(mag_write_reg(i2c_dev, MAG_CONFIG_B, range
      <<5)<0){
    perror("Write in configuration register B unsuccesful");
    return -1;
  }
  
  if(mag_write_reg(i2c_dev, MAG_MODE, op_mode)<0){
    perror("Write in mode register unsuccesful");
    return -1;
  }
  
  return 1;
}
int mag_read_all_data (int i2c_dev, short int * data)
READ ALL DATA AT ONCE (X, Y and Z)
Definition at line 121 of file mag_functions.c.
Referenced by read_all_data().
{
  uint8_t i, j;
  uint8_t *data8;
  union result
  {
    unsigned short int usgnd[3];
    short int sgnd[3];
  } result;
  //result=(union result*)malloc(3*sizeof(union result));
  if((data8=mag_read_reg(i2c_dev,MAG_DATAX1,6))==
      NULL)
  {
    //perror("Read accelerometer register failed");
    return FAILURE;
  }
  //result.usgnd=(unsigned int*)malloc(3*sizeof(unsigned int));
  j=0;
  for(i=0; i<3; i++)
  {
    result.usgnd[j]=0;
    result.usgnd[j]=result.usgnd[j]|((unsigned short int)data8[i*2+1])|(((
      unsigned int)data8[i*2])<<8);
    data[j]=result.sgnd[j];
    j=2-i; // trick used to change the sorting of the data from XZY to XYZ
  }
  return SUCCESS;
}
short int mag_read_data (int i2c_dev, int axis)
READ DATA (X, Y or Z)
Definition at line 148 of file mag_functions.c.
{
  uint8_t *data;
  union result
  {
    unsigned int usgnd;
    int sgnd;
  }result;
  switch(axis){
    case 'X':
      data=mag_read_reg(i2c_dev,MAG_DATAX1,2);
      break;
    case 'Y':
      data=mag_read_reg(i2c_dev,MAG_DATAY1,2);
      break;
    case 'Z':
      data=mag_read_reg(i2c_dev,MAG_DATAZ1,2);
      break;
    default:
      //perror("Wrong argument for axis in mag_read_data");
      return -1;
  }
  result.usgnd=0;
  result.usgnd=result.usgnd|(((unsigned short int)data[1]))|(((unsigned short
      int)data[0])<<8);
  return result.sgnd;
}
uint8_t* mag_read_reg (int i2c_dev, uint8_t reg, uint8_t count)
READ COUNT 8-BIT REGISTER IN SEQUENCE.
Parameters
count number of registers in sequence (1-13)
Definition at line 31 of file mag_functions.c.
Referenced by mag_read_all_data(), and mag_read_data().
{
  uint8_t data[13];
  int i;
  //data=(uint8_t*)malloc((count+1)*sizeof(data));
  
  data[0] = reg;
  if (write(i2c_dev, &data, 1) != 1) {
        //perror("write before read");
        return NULL;
  }
  data[0] = 0;
  if (read(i2c_dev, &data, count) != count) {
        //perror("read");
        return NULL;
  }
  return data;
}
int mag_write_reg (int i2c_dev, uint8_t reg, uint8_t data)
WRITE TO REGISTER.
WRITE TO REGISTER.
Implements the I2C communication between Gumstix Overo Fire and HMC5883
Author
Caio Gustavo Mesquita Ângelo
Definition at line 10 of file mag_functions.c.
Referenced by mag_init().
{
  uint8_t reg_data[2];
  reg_data[0] = reg;
  reg_data[1] = data;
  if(MAG_MODE<reg)
  {
      //perror("Write unsucessful: Not a valid writable register");
      return -1;
  }
        
  if (write(i2c_dev, &reg_data, 2) != 2) {
          //perror("Write unsuccessful");
          return -1;
  }
  return 1;
}