André backup conflitos/datalogger (Cópia em conflito de André Carvalho 2013-04-26).c File Reference
#include <stdlib.h>
*
#include <stdio.h>
*
#include <string.h>
*
#include <pthread.h>
*
#include `gqueue.h`
*
#include `gmatlabdatafile.h`
*
#include `gdatalogger.h`
*
#include `gmatrix.h`
*
#include `imu.h`
*
#include `magnetometer.h`
*
#include `sonar.h`
*
#include `gps.h`
*
#include `sensors.h`
*
#include `calibration.h`
*
#include `estimation.h`
*
#include `control.h`
*
#include `datalogger.h`
*
Functions
int datalogger_lock_mutex (void)
int datalogger_unlock_mutex (void)
int datalogger_init (void)
int datalogger_close (void)
int datalogger_write_file (void)
int datalogger_update_IPC (void)
int datalogger_update (double t_s, double t_control_exec_s, double t_ui_exec_s, double t0_s, IMU_DATA_STRUCT *pimu_data, EFF_DATA_STRUCT *peff_data)
Variables
GDATALOGGER gDataLogger
unsigned int datalogger_initialized = DATALOGGER_NOT_INITIALIZED
unsigned int datalogger_running = DATALOGGER_NOT_RUNNING
pthread_mutex_t datalogger_mutex = PTHREAD_MUTEX_INITIALIZER
Function Documentation
int datalogger_close (void)
Definition at line 203 of file datalogger (Cópia em conflito de André Carvalho 2013-04-26).c.
References DATALOGGER_ERROR_NOT_INITIALIZED, datalogger_initialized, DATALOGGER_INITIALIZED, datalogger_lock_mutex(), datalogger_mutex, DATALOGGER_NOT_INITIALIZED, DATALOGGER_SUCCESS, datalogger_unlock_mutex(), gDataLogger_Close(), and gDataLogger_MatfileUpdate().
{
    #if DATALOGGER_MODULE_ENABLED
        datalogger_lock_mutex();
        if(datalogger_initialized !=
      DATALOGGER_INITIALIZED)
    {
            datalogger_unlock_mutex();
        return DATALOGGER_ERROR_NOT_INITIALIZED
      ;
    }
    gDataLogger_MatfileUpdate(&gDataLogger)
      ; // Update data
    gDataLogger_Close(&gDataLogger); // Close
       datalogger
    datalogger_initialized = DATALOGGER_NOT_INITIALIZED
      ;
    datalogger_unlock_mutex();
        #if ANU_COMPILE_FOR_XENOMAI
    rt_mutex_delete(&datalogger_mutex);
        #endif //ANU_COMPILE_FOR_XENOMAI
    #endif //DATALOGGER_MODULE_ENABLED
    return DATALOGGER_SUCCESS;
}
int datalogger_init (void)
Definition at line 37 of file datalogger (Cópia em conflito de André Carvalho 2013-04-26).c.
References DATALOGGER_FAILURE, datalogger_file_exists(), DATALOGGER_FILE_NAME, DATALOGGER_FOLDER, datalogger_initialized, DATALOGGER_INITIALIZED, datalogger_lock_mutex(), DATALOGGER_LOG_ANALOG_INPUTS, DATALOGGER_LOG_EXECTIMES, DATALOGGER_LOG_RAW_IMU, DATALOGGER_LOG_TIME, datalogger_mutex, DATALOGGER_NOT_RUNNING, datalogger_running, DATALOGGER_STANDARD_QUEUE_SIZE, DATALOGGER_SUCCESS, datalogger_unlock_mutex(), gDataLogger_DeclareVariable(), gDataLogger_Init(), and gDataLogger_InsertVariable().
{
    #if DATALOGGER_MODULE_ENABLED
    double enabled_variables[16][1];
    char datalogger_filename[256];
        #if ANU_COMPILE_FOR_XENOMAI
    rt_mutex_create(&datalogger_mutex,"Data Logger Mutex");
        #endif
    datalogger_lock_mutex();
    if(datalogger_initialized == DATALOGGER_INITIALIZED
      )
    {
        datalogger_unlock_mutex();
        return DATALOGGER_FAILURE;
    }
    datalogger_running = DATALOGGER_NOT_RUNNING
      ;
        // Init datalogger
    strcpy(datalogger_filename, DATALOGGER_FOLDER);
    strcat(datalogger_filename, "/");
    strcat(datalogger_filename, DATALOGGER_FILE_NAME);
    strcat(datalogger_filename, ".mat");
        #if DATALOGGER_ENABLE_NEW_FILE_ENNUMERATION
    char datalogger_tmp[256];
    int i = 0;
    if(datalogger_file_exists(datalogger_filename) ==
      DATALOGGER_SUCCESS) // File exists
    {
        strcpy(datalogger_tmp, DATALOGGER_FOLDER);
        strcat(datalogger_tmp, "/");
        strcat(datalogger_tmp, DATALOGGER_FILE_NAME);
        strcat(datalogger_tmp, "_%d.mat");
        do
        {
            sprintf(datalogger_filename, datalogger_tmp, ++i);
        }
        while((datalogger_file_exists(datalogger_filename
      ) == DATALOGGER_SUCCESS) && (i<100));
        if(i == 100)
        {
            datalogger_unlock_mutex();
            return DATALOGGER_FAILURE;
        }
    }
        #endif //DATALOGGER_ENABLE_NEW_FILE_ENNUMERATION
    if(!gDataLogger_Init(&gDataLogger,
      datalogger_filename, NULL))
    {
        datalogger_unlock_mutex();
        return DATALOGGER_FAILURE;
    }
        // Declare variables
        // Arguments for gDataLogger_DeclareVariable:
        // datalogger pointer, variable name, units, number of rows, number of
       columns, queue size
        // Variable that tells MATLAB which variables are enabled
        enabled_variables[0][0] = (double) DATALOGGER_LOG_TIME
      ;
    enabled_variables[1][0] = (double) DATALOGGER_LOG_EXECTIMES
      ;
    enabled_variables[2][0] = (double) DATALOGGER_LOG_RAW_IMU
      ;
    //enabled_variables[3][0] = (double) DATALOGGER_LOG_CALIBRATED_IMU;
    enabled_variables[3][0] = (double) DATALOGGER_LOG_ANALOG_INPUTS
      ;
    //enabled_variables[12][0] = (double)
       DATALOGGER_LOG_LOCAL_COORDINATE_SYSTEM;
    //enabled_variables[13][0] = (double) DATALOGGER_LOG_LOCAL_FIELDS;
    //enabled_variables[14][0] = (double) DATALOGGER_LOG_ESTIMATOR;
    //enabled_variables[15][0] = (double) DATALOGGER_LOG_CONTROLLERS;
    gDataLogger_DeclareVariable(&gDataLogger
      , "enabled_vars", "", 16, 1, 1);
    gDataLogger_InsertVariable(&gDataLogger
      , "enabled_vars", &enabled_variables[0][0]);
        #if DATALOGGER_LOG_TIME
        gDataLogger_DeclareVariable(&gDataLogger
      , "t", "s", 1, 1, DATALOGGER_STANDARD_QUEUE_SIZE);
    gDataLogger_DeclareVariable(&gDataLogger
      , "Ts", "s", 1, 1, 1);
    #endif // DATALOGGER_LOG_TIME
    #if DATALOGGER_LOG_EXECTIMES
    gDataLogger_DeclareVariable(&gDataLogger
      , "t_control_exec", "s", 1, 1, DATALOGGER_STANDARD_QUEUE_SIZE
      );
    gDataLogger_DeclareVariable(&gDataLogger
      , "t_ui_exec", "s", 1, 1, DATALOGGER_STANDARD_QUEUE_SIZE
      );
    #endif // DATALOGGER_LOG_EXECTIMES
        #if DATALOGGER_LOG_RAW_IMU
        gDataLogger_DeclareVariable(&gDataLogger
      , "imu_accelerometer_x_raw", "raw", 1, 1, DATALOGGER_STANDARD_QUEUE_SIZE
      );
        gDataLogger_DeclareVariable(&gDataLogger
      , "imu_accelerometer_y_raw", "raw", 1, 1, DATALOGGER_STANDARD_QUEUE_SIZE
      );
        gDataLogger_DeclareVariable(&gDataLogger
      , "imu_accelerometer_z_raw", "raw", 1, 1, DATALOGGER_STANDARD_QUEUE_SIZE
      );
        gDataLogger_DeclareVariable(&gDataLogger
      , "imu_magnetometer_x_raw", "raw", 1, 1, DATALOGGER_STANDARD_QUEUE_SIZE
      );
        gDataLogger_DeclareVariable(&gDataLogger
      , "imu_magnetometer_y_raw", "raw", 1, 1, DATALOGGER_STANDARD_QUEUE_SIZE
      );
        gDataLogger_DeclareVariable(&gDataLogger
      , "imu_magnetometer_z_raw", "raw", 1, 1, DATALOGGER_STANDARD_QUEUE_SIZE
      );
        gDataLogger_DeclareVariable(&gDataLogger
      , "imu_gyrometer_x_raw", "raw", 1, 1, DATALOGGER_STANDARD_QUEUE_SIZE
      );
        gDataLogger_DeclareVariable(&gDataLogger
      , "imu_gyrometer_y_raw", "raw", 1, 1, DATALOGGER_STANDARD_QUEUE_SIZE
      );
        gDataLogger_DeclareVariable(&gDataLogger
      , "imu_gyrometer_z_raw", "raw", 1, 1, DATALOGGER_STANDARD_QUEUE_SIZE
      );
    gDataLogger_DeclareVariable(&gDataLogger
      , "imu_valid_data", "", 1, 1, DATALOGGER_STANDARD_QUEUE_SIZE
      );
        #endif // DATALOGGER_LOG_IMU
    #if DATALOGGER_LOG_EFFORTS
    gDataLogger_DeclareVariable(&gDataLogger
      , "Vin0", "mV", 1, 1, DATALOGGER_STANDARD_QUEUE_SIZE
      );
    #endif
/*
    #if DATALOGGER_LOG_CALIBRATED_IMU
    gDataLogger_DeclareVariable(&gDataLogger, "imu_accelerometer_x_ms2", "ms2",
       1, 1, DATALOGGER_STANDARD_QUEUE_SIZE);
    gDataLogger_DeclareVariable(&gDataLogger, "imu_accelerometer_y_ms2", "ms2",
       1, 1, DATALOGGER_STANDARD_QUEUE_SIZE);
    gDataLogger_DeclareVariable(&gDataLogger, "imu_accelerometer_z_ms2", "ms2",
       1, 1, DATALOGGER_STANDARD_QUEUE_SIZE);
    gDataLogger_DeclareVariable(&gDataLogger, "imu_magnetometer_x_uT", "uT", 1,
       1, DATALOGGER_STANDARD_QUEUE_SIZE);
    gDataLogger_DeclareVariable(&gDataLogger, "imu_magnetometer_y_uT", "uT", 1,
       1, DATALOGGER_STANDARD_QUEUE_SIZE);
    gDataLogger_DeclareVariable(&gDataLogger, "imu_magnetometer_z_uT", "uT", 1,
       1, DATALOGGER_STANDARD_QUEUE_SIZE);
    gDataLogger_DeclareVariable(&gDataLogger, "imu_gyrometer_x_rads", "rads",
       1, 1, DATALOGGER_STANDARD_QUEUE_SIZE);
    gDataLogger_DeclareVariable(&gDataLogger, "imu_gyrometer_y_rads", "rads",
       1, 1, DATALOGGER_STANDARD_QUEUE_SIZE);
    gDataLogger_DeclareVariable(&gDataLogger, "imu_gyrometer_z_rads", "rads",
       1, 1, DATALOGGER_STANDARD_QUEUE_SIZE);
    gDataLogger_DeclareVariable(&gDataLogger,
       "imu_calibrated_valid_accelerometer_data", "", 1, 1, DATALOGGER_STANDARD_QUEUE_SIZE);
    gDataLogger_DeclareVariable(&gDataLogger,
       "imu_calibrated_valid_gyrometer_data", "", 1, 1, DATALOGGER_STANDARD_QUEUE_SIZE);
    gDataLogger_DeclareVariable(&gDataLogger,
       "imu_calibrated_valid_magnetometer_data", "", 1, 1, DATALOGGER_STANDARD_QUEUE_SIZE);
    #endif // DATALOGGER_LOG_CALIBRATED_IMU
    #if DATALOGGER_LOG_LOCAL_COORDINATE_SYSTEM
    gDataLogger_DeclareVariable(&gDataLogger, "initial_altitude", "m", 1, 1,
       1);
    gDataLogger_DeclareVariable(&gDataLogger, "initial_latitude", "radians", 1,
       1, 1);
    gDataLogger_DeclareVariable(&gDataLogger, "initial_longitude", "radians",
       1, 1, 1);
    gDataLogger_DeclareVariable(&gDataLogger, "initial_ecef_x", "m", 1, 1, 1);
    gDataLogger_DeclareVariable(&gDataLogger, "initial_ecef_y", "m", 1, 1, 1);
    gDataLogger_DeclareVariable(&gDataLogger, "initial_ecef_z", "m", 1, 1, 1);
    gDataLogger_DeclareVariable(&gDataLogger, "rotation_matrix", "matrix", 3,
       3, 1);
    #endif // DATALOGGER_LOG_LOCAL_COORDINATE_SYSTEM
    #if DATALOGGER_LOG_LOCAL_FIELDS
    gDataLogger_DeclareVariable(&gDataLogger, "local_magnetic", "field", 3, 1,
       1);
    gDataLogger_DeclareVariable(&gDataLogger, "local_gravity", "field", 3, 1,
       1);
    gDataLogger_DeclareVariable(&gDataLogger, "magnetic_magnitude", "uT", 1, 1,
       1);
    gDataLogger_DeclareVariable(&gDataLogger, "gravity_magnitude", "ms2", 1, 1,
       1);
    #endif // DATALOGGER_LOG_LOCAL_FIELDS
    #if DATALOGGER_LOG_ESTIMATOR
    gDataLogger_DeclareVariable(&gDataLogger, "estimated_roll_angle_radians",
       "radians", 1, 1, DATALOGGER_STANDARD_QUEUE_SIZE);
    gDataLogger_DeclareVariable(&gDataLogger, "estimated_pitch_angle_radians",
       "radians", 1, 1, DATALOGGER_STANDARD_QUEUE_SIZE);
    gDataLogger_DeclareVariable(&gDataLogger, "estimated_yaw_angle_radians",
       "radians", 1, 1, DATALOGGER_STANDARD_QUEUE_SIZE);
    gDataLogger_DeclareVariable(&gDataLogger, "estimated_q0", "quaternion", 1,
       1, DATALOGGER_STANDARD_QUEUE_SIZE);
    gDataLogger_DeclareVariable(&gDataLogger, "estimated_q1", "quaternion", 1,
       1, DATALOGGER_STANDARD_QUEUE_SIZE);
    gDataLogger_DeclareVariable(&gDataLogger, "estimated_q2", "quaternion", 1,
       1, DATALOGGER_STANDARD_QUEUE_SIZE);
    gDataLogger_DeclareVariable(&gDataLogger, "estimated_q3", "quaternion", 1,
       1, DATALOGGER_STANDARD_QUEUE_SIZE);
    gDataLogger_DeclareVariable(&gDataLogger, "estimated_x_position_meters",
       "meters", 1, 1, DATALOGGER_STANDARD_QUEUE_SIZE);
    gDataLogger_DeclareVariable(&gDataLogger, "estimated_y_position_meters",
       "meters", 1, 1, DATALOGGER_STANDARD_QUEUE_SIZE);
    gDataLogger_DeclareVariable(&gDataLogger, "estimated_z_position_meters",
       "meters", 1, 1, DATALOGGER_STANDARD_QUEUE_SIZE);
    gDataLogger_DeclareVariable(&gDataLogger,
       "estimated_x_velocity_meters_second", "meters", 1, 1, DATALOGGER_STANDARD_QUEUE_SIZE);
    gDataLogger_DeclareVariable(&gDataLogger,
       "estimated_y_velocity_meters_second", "meters", 1, 1, DATALOGGER_STANDARD_QUEUE_SIZE);
    gDataLogger_DeclareVariable(&gDataLogger,
       "estimated_z_velocity_meters_second", "meters", 1, 1, DATALOGGER_STANDARD_QUEUE_SIZE);
    #endif // DATALOGGER_LOG_ESTIMATOR
    #if DATALOGGER_LOG_CONTROLLERS
    gDataLogger_DeclareVariable(&gDataLogger,
       "control_roll_angle_trim_radians", "radians", 1, 1, DATALOGGER_STANDARD_QUEUE_SIZE);
    gDataLogger_DeclareVariable(&gDataLogger,
       "control_pitch_angle_trim_radians", "radians", 1, 1, DATALOGGER_STANDARD_QUEUE_SIZE);
    gDataLogger_DeclareVariable(&gDataLogger, "control_yaw_angle_trim_radians",
       "radians", 1, 1, DATALOGGER_STANDARD_QUEUE_SIZE);
    gDataLogger_DeclareVariable(&gDataLogger, "control_left_aileron_trim",
       "us", 1, 1, DATALOGGER_STANDARD_QUEUE_SIZE);
    gDataLogger_DeclareVariable(&gDataLogger, "control_right_aileron_trim",
       "us", 1, 1, DATALOGGER_STANDARD_QUEUE_SIZE);
    gDataLogger_DeclareVariable(&gDataLogger, "control_elevator_trim", "us", 1,
       1, DATALOGGER_STANDARD_QUEUE_SIZE);
    gDataLogger_DeclareVariable(&gDataLogger, "control_rudder_trim", "us", 1,
       1, DATALOGGER_STANDARD_QUEUE_SIZE);
    gDataLogger_DeclareVariable(&gDataLogger,
       "control_roll_angle_reference_radians", "radians", 1, 1, DATALOGGER_STANDARD_QUEUE_SIZE);
    gDataLogger_DeclareVariable(&gDataLogger,
       "control_pitch_angle_reference_radians", "radians", 1, 1, DATALOGGER_STANDARD_QUEUE_SIZE);
    gDataLogger_DeclareVariable(&gDataLogger,
       "control_yaw_angle_reference_radians", "radians", 1, 1, DATALOGGER_STANDARD_QUEUE_SIZE);
    #endif // DATALOGGER_LOG_CONTROLLERS
*/
    datalogger_initialized = DATALOGGER_INITIALIZED
      ;
    datalogger_unlock_mutex();
    #endif //DATALOGGER_MODULE_ENABLED
    return DATALOGGER_SUCCESS;
}
int datalogger_lock_mutex (void)
Definition at line 599 of file datalogger (Caio-PC's conflicted copy 2012-11-23).c.
References datalogger_mutex, and DATALOGGER_SUCCESS.
Referenced by datalogger_close(), datalogger_init(), datalogger_set_initial_filter_parameters(), datalogger_set_local_coordinate_system(), datalogger_set_local_fields(), datalogger_set_Ts(), datalogger_start(), datalogger_status(), datalogger_stop(), datalogger_update(), datalogger_update_IPC(), and datalogger_write_file().
{
        #if ANU_COMPILE_FOR_XENOMAI
        rt_mutex_acquire(&datalogger_mutex,TM_INFINITE);
        #else
        pthread_mutex_lock(&datalogger_mutex);
        #endif
        return DATALOGGER_SUCCESS;
}
int datalogger_unlock_mutex (void)
Definition at line 609 of file datalogger (Caio-PC's conflicted copy 2012-11-23).c.
References datalogger_mutex, and DATALOGGER_SUCCESS.
Referenced by datalogger_close(), datalogger_init(), datalogger_set_initial_filter_parameters(), datalogger_set_local_coordinate_system(), datalogger_set_local_fields(), datalogger_set_Ts(), datalogger_start(), datalogger_status(), datalogger_stop(), datalogger_update(), datalogger_update_IPC(), and datalogger_write_file().
{
        #if ANU_COMPILE_FOR_XENOMAI
        rt_mutex_release(&datalogger_mutex);
        #else
        pthread_mutex_unlock(&datalogger_mutex);
        #endif
        return DATALOGGER_SUCCESS;
}
int datalogger_update (double t_s, double t_control_exec_s, double t_ui_exec_s, double t0_s, IMU_DATA_STRUCT * pimu_data, EFF_DATA_STRUCT * peff_data)
Definition at line 261 of file datalogger (Cópia em conflito de André Carvalho 2013-04-26).c.
References IMU_DATA_STRUCT::acc, DATALOGGER_ERROR_NOT_INITIALIZED, datalogger_initialized, DATALOGGER_INITIALIZED, datalogger_lock_mutex(), DATALOGGER_SUCCESS, datalogger_unlock_mutex(), EFF_DATA_STRUCT::F, gDataLogger_InsertVariable(), IMU_DATA_STRUCT::gyr, IMU_DATA_STRUCT::mag, IMU_DATA_STRUCT::new_data, EFF_DATA_STRUCT::new_data, DATA_XYZ::x, DATA_XYZ::y, and DATA_XYZ::z.
int datalogger_update_IPC (void)
Definition at line 245 of file datalogger (Cópia em conflito de André Carvalho 2013-04-26).c.
References DATALOGGER_ERROR_NOT_INITIALIZED, datalogger_initialized, DATALOGGER_INITIALIZED, datalogger_lock_mutex(), DATALOGGER_SUCCESS, datalogger_unlock_mutex(), and gDataLogger_IPCUpdate().
{
    #if DATALOGGER_MODULE_ENABLED
    datalogger_lock_mutex();
    if(datalogger_initialized != DATALOGGER_INITIALIZED
      )
    {
        datalogger_unlock_mutex();
        return DATALOGGER_ERROR_NOT_INITIALIZED
      ;
    }
    gDataLogger_IPCUpdate(&gDataLogger); //
       Manages IPC
    datalogger_unlock_mutex();
    #endif
    return DATALOGGER_SUCCESS;
}
int datalogger_write_file (void)
Definition at line 228 of file datalogger (Cópia em conflito de André Carvalho 2013-04-26).c.
References DATALOGGER_ERROR_NOT_INITIALIZED, datalogger_initialized, DATALOGGER_INITIALIZED, datalogger_lock_mutex(), DATALOGGER_SUCCESS, datalogger_unlock_mutex(), and gDataLogger_MatfileUpdate().
{
    #if DATALOGGER_MODULE_ENABLED
    datalogger_lock_mutex();
    if(datalogger_initialized != DATALOGGER_INITIALIZED
      )
    {
        datalogger_unlock_mutex();
        return DATALOGGER_ERROR_NOT_INITIALIZED
      ;
    }
    gDataLogger_MatfileUpdate(&gDataLogger)
      ; // Empty buffers in the file
    datalogger_unlock_mutex();
    #endif
    return DATALOGGER_SUCCESS;
}
Variable Documentation
unsigned int datalogger_initialized = DATALOGGER_NOT_INITIALIZED
Definition at line 25 of file datalogger (Cópia em conflito de André Carvalho 2013-04-26).c.
pthread_mutex_t datalogger_mutex = PTHREAD_MUTEX_INITIALIZER
Definition at line 30 of file datalogger (Cópia em conflito de André Carvalho 2013-04-26).c.
unsigned int datalogger_running = DATALOGGER_NOT_RUNNING
Definition at line 26 of file datalogger (Cópia em conflito de André Carvalho 2013-04-26).c.
GDATALOGGER gDataLogger
Definition at line 24 of file datalogger (Cópia em conflito de André Carvalho 2013-04-26).c.