schunk_high/include/schunk_high/dualquaternion.h File Reference
#include `quaternion.h`
*
#include `gmatrix.h`
*
Data Structures
struct DQ
DualQuaternion library Header.
Typedefs
typedef DQ DualQuaternion
Another name for a DualQuaternion.
Functions
DQ * DQ_alloc ()
Allocates a Dual Quaternion.
DQ * DQ_create (double a, double b, double c, double d, double e, double f, double g, double h)
Allocated and initializes a DualQuaternion.
DQ * DQ_createFromQuaternion (Q *t, Q *r)
Allocated and initializes a DualQuaternion.
Q * DQ_getR (DQ *dq)
DualQuaternion Rotation.
Q * DQ_getT (DQ *dq)
DualQuaternion Translation considering a translation followed by a rotation.
DQ * DQ_free (DQ *dq)
Free's an Allocated DualQuaternion.
DQ * DQ_mult (DQ *a, DQ *b, int freeA, int freeB)
DualQuaternion Multiplication.
void DQ_print (DQ *dq)
Prints a DualQuaternion.
double DQ_getPitchAngle (DQ *dq)
Gets the `PITCH` angle.
void PGMATRIX_SET_COLUMN_BY_DQ (PGMATRIX Pmat, int col, DQ *dq)
Typedef Documentation
typedef DQ DualQuaternion
Another name for a DualQuaternion.
Definition at line 35 of file dualquaternion.h.
Function Documentation
DQ* DQ_alloc ()
Allocates a Dual Quaternion.
Does not initialize any of it's components.
Returns
A DualQuaternion* to a the newly allocated memory region.
Definition at line 30 of file dualquaternion.c.
Referenced by DQ_create(), DQ_createFromQuaternion(), DQ_mult(), and Link_DQFT().
              {
        return (DQ*)malloc(sizeof(DQ));
}
DQ* DQ_create (double a, double b, double c, double d, double e, double f, double g, double h)
Allocated and initializes a DualQuaternion.
Parameters
a Primary part scalar part
b Primary part i part
c Primary part j part
d Primary part k part
e Dual part scalar part
f Dual part i part
g Dual part j part
h Dual part k part
Returns
A DualQuaternion = [a b c d e f g h]'
Definition at line 47 of file dualquaternion.c.
References DQ::d, DQ_alloc(), DQ::p, and Q_create().
Referenced by Cartesian_pose_controller::printPose(), Robot_FKM(), Robot_getAJacobian(), Robot_getGJacobian(), and Robot_getP().
                                                                               
                    {
        DQ* dq = DQ_alloc();
        dq->p = Q_create(a,b,c,d);
        dq->d = Q_create(e,f,g,h);
        return dq;
}
DQ* DQ_createFromQuaternion (Q * t, Q * r)
Allocated and initializes a DualQuaternion.
Parameters
a The quaternion representing the translation.
b The quaternion representing the rotation.
Returns
A DualQuaternion = []
Definition at line 61 of file dualquaternion.c.
References DQ::d, DQ_alloc(), FALSE, DQ::p, Q_copy(), Q_mult(), Q_multd(), and TRUE.
                                       {
        DQ* dq = DQ_alloc();
        //Primary part is r
        dq->p = Q_copy(r);
        //Dual part is (1/2)*(t*r)
        Q* temp = Q_mult(t,r,FALSE,FALSE);
        dq->d = Q_multd(0.5,temp,TRUE);
        return dq;
}
DQ* DQ_free (DQ * dq)
Free's an Allocated DualQuaternion.
Parameters
dq a DualQuaternion* to the Allocated region to be freed.
Returns
NULL
Definition at line 104 of file dualquaternion.c.
References DQ::d, DQ::p, and Q_free().
Referenced by Cartesian_pose_controller::control(), DQ_mult(), main(), Cartesian_pose_controller::printPose(), Robot_getAJacobian(), Robot_getGJacobian(), and Robot_getOJacobianAngleP().
                   {
        Q_free(dq->p);
        Q_free(dq->d);
        free(dq);
        return NULL;
}
double DQ_getPitchAngle (DQ * dq)
Gets the `PITCH` angle.
Parameters
dq The DualQuaternion representing the rotation.
Returns
a Double with the desired value in radians.
Definition at line 150 of file dualquaternion.c.
References DQ::p, and Q_getPitchAngle().
Referenced by main().
                               {
        return Q_getPitchAngle(dq->p);
        
}
Q* DQ_getR (DQ * dq)
DualQuaternion Rotation.
Parameters
dq A DualQuaternion.
Returns
a Unity Quaternion representing dq's Rotation.
Definition at line 77 of file dualquaternion.c.
References DQ::p, and Q_copy().
Referenced by Cartesian_pose_controller::printPose().
                  {
        Q* r = Q_copy(dq->p);
        return r;
}
Q* DQ_getT (DQ * dq)
DualQuaternion Translation considering a translation followed by a rotation.
Parameters
dq The DualQuaternion from which you want to get the translation.
Returns
A Quaternion representing the translation.
Definition at line 88 of file dualquaternion.c.
References DQ::d, FALSE, DQ::p, Q_getConj(), Q_mult(), Q_multd(), and TRUE.
Referenced by main(), Cartesian_pose_controller::printPose(), and Robot_getGJacobian().
                  {
        Q* t;
        //2*(dq->d*(dq->p)')
        t = Q_multd(2,Q_mult(dq->d,Q_getConj(dq->p,
      FALSE),FALSE,TRUE),TRUE);
        return t;
}
DQ* DQ_mult (DQ * a, DQ * b, int freeA, int freeB)
DualQuaternion Multiplication.
It uses the expanded H+ operator on the first term to make the multiplication. Remember that DualQuaternion Multiplication is not commutative in general.
Parameters
a The first DualQuaternion
b The second DualQuaternion
freeA TRUE if you want to free a from memory.
freeB TRUE if you want to free b from memory. c = a*b
Definition at line 123 of file dualquaternion.c.
References DQ::d, DQ_alloc(), DQ_free(), FALSE, DQ::p, Q_add(), Q_mult(), and TRUE.
Referenced by Robot_FKM(), Robot_getAJacobian(), and Robot_getGJacobian().
                                               {
        //Alloc
        DQ* c = DQ_alloc();
        Q* temp1;
        Q* temp2;
        
        //Primary Part = P(a)*P(b).
        c->p = Q_mult(a->p,b->p,FALSE,FALSE);
        
        //Dual Part = P(a)*D(b) + D(a)*P(b)
    temp1 = Q_mult(a->p,b->d,FALSE,FALSE);
        temp2 = Q_mult(a->d,b->p,FALSE,FALSE);
        c->d = Q_add(temp1,temp2,TRUE,TRUE);
        if(freeA){DQ_free(a);}
        if(freeB){DQ_free(b);}
        
        return c;
}
void DQ_print (DQ * dq)
Prints a DualQuaternion.
Parameters
dq The DualQuaternion to be printed.
Definition at line 162 of file dualquaternion.c.
References DQ::d, DQ::p, and Q::v.
                     {
        printf("\t[%e %e %e %e %e %e %e %e]\n",dq->p->v[0],dq->p->v[1],dq
      ->p->v[2],dq->p->v[3],dq->d->v[0],dq->d->v[1],dq->d->v[2],dq->d->v[3]
      );
}
void PGMATRIX_SET_COLUMN_BY_DQ (PGMATRIX Pmat, int col, DQ * dq)
Definition at line 17 of file gmatrix_plus.c.
Referenced by Cartesian_pose_controller::control(), and Robot_getAJacobian().
                                                               {
        GMATRIX_ASSERT("PGMATRIX_SET_COLUMN_BY_DQ",(col > Pmat->
      Nc)&&(Pmat->Nr != 8));
        PGMATRIX_DATA(Pmat,1,col) = dq->p->v[0];
        PGMATRIX_DATA(Pmat,2,col) = dq->p->v[1];
        PGMATRIX_DATA(Pmat,3,col) = dq->p->v[2];
        PGMATRIX_DATA(Pmat,4,col) = dq->p->v[3];
        PGMATRIX_DATA(Pmat,5,col) = dq->d->v[0];
        PGMATRIX_DATA(Pmat,6,col) = dq->d->v[1];
        PGMATRIX_DATA(Pmat,7,col) = dq->d->v[2];
        PGMATRIX_DATA(Pmat,8,col) = dq->d->v[3];
}