schunk_high/include/schunk_high/gmatrix.h File Reference
Data Structures
struct GMATRIX
struct DUMMY_MATRICES
struct GMATRIX_MATLAB_DATAHEAD
Macros
#define GMATRIX_FLOAT double
#define GMATRIX_PRINTCOMMAND printf
#define GMATRIX_ABORTCOMMAND getchar();exit(1);
#define BOOL unsigned char
#define TRUE 1
#define FALSE 0
#define GMATRIX_DEFINE_ALL (1)
#define GMATRIX_DEFINE_ALLOC (0 + GMATRIX_DEFINE_ALL)
#define GMATRIX_DEFINE_SETSIZE (0 + GMATRIX_DEFINE_ALL)
#define GMATRIX_DEFINE_PRINT (0 + GMATRIX_DEFINE_ALL)
#define GMATRIX_DEFINE_PRINT_MATLABFORM (0 + GMATRIX_DEFINE_ALL)
#define GMATRIX_DEFINE_PRINTROW (0 + GMATRIX_DEFINE_ALL)
#define GMATRIX_DEFINE_PRINT_EXP (0 + GMATRIX_DEFINE_ALL)
#define GMATRIX_DEFINE_INFO (0 + GMATRIX_DEFINE_ALL)
#define GMATRIX_DEFINE_ZEROES (0 + GMATRIX_DEFINE_ALL)
#define GMATRIX_DEFINE_SUMLINCOL (0 + GMATRIX_DEFINE_ALL)
#define GMATRIX_DEFINE_ONES (0 + GMATRIX_DEFINE_ALL)
#define GMATRIX_DEFINE_RAND (0 + GMATRIX_DEFINE_ALL)
#define GMATRIX_DEFINE_RANDN (0 + GMATRIX_DEFINE_ALL)
#define GMATRIX_DEFINE_IDENTITY (0 + GMATRIX_DEFINE_ALL)
#define GMATRIX_DEFINE_WILKINSON (0 + GMATRIX_DEFINE_ALL)
#define GMATRIX_DEFINE_ORTHOGONAL (0 + GMATRIX_DEFINE_ALL)
#define GMATRIX_DEFINE_COPY (0 + GMATRIX_DEFINE_ALL)
#define GMATRIX_DEFINE_COPY_COLUMN (0 + GMATRIX_DEFINE_ALL)
#define GMATRIX_DEFINE_COPY_ROW (0 + GMATRIX_DEFINE_ALL)
#define GMATRIX_DEFINE_TRANSPOSE_COPY (0 + GMATRIX_DEFINE_ALL)
#define GMATRIX_DEFINE_TRACE (0 + GMATRIX_DEFINE_ALL)
#define GMATRIX_DEFINE_SUMENTRIES (0 + GMATRIX_DEFINE_ALL)
#define GMATRIX_DEFINE_SUMABSOLUTEENTRIES (0 + GMATRIX_DEFINE_ALL)
#define GMATRIX_DEFINE_LUDCMP (0 + GMATRIX_DEFINE_ALL)
#define GMATRIX_DEFINE_GAUSSJORDAN (0 + GMATRIX_DEFINE_ALL)
#define GMATRIX_DEFINE_CHOLESKY (0 + GMATRIX_DEFINE_ALL)
#define GMATRIX_DEFINE_DETERMINANT2 (0 + GMATRIX_DEFINE_ALL)
#define GMATRIX_DEFINE_DETERMINANT3 (0 + GMATRIX_DEFINE_ALL)
#define GMATRIX_DEFINE_DETERMINANT (0 + GMATRIX_DEFINE_ALL)
#define GMATRIX_DEFINE_INVERSE2_COPY (0 + GMATRIX_DEFINE_ALL)
#define GMATRIX_DEFINE_INVERSE3_COPY (0 + GMATRIX_DEFINE_ALL)
#define GMATRIX_DEFINE_INVERSE_COPY (0 + GMATRIX_DEFINE_ALL)
#define GMATRIX_DEFINE_INVERSE (0 + GMATRIX_DEFINE_ALL)
#define GMATRIX_DEFINE_SWAP_ROW (0 + GMATRIX_DEFINE_ALL)
#define GMATRIX_DEFINE_SWAP_COLUMN (0 + GMATRIX_DEFINE_ALL)
#define GMATRIX_DEFINE_SVD (0 + GMATRIX_DEFINE_ALL)
#define GMATRIX_DEFINE_ADD_CONST (0 + GMATRIX_DEFINE_ALL)
#define GMATRIX_DEFINE_CROSS (0 + GMATRIX_DEFINE_ALL)
#define GMATRIX_DEFINE_MULTIPLY_CONST (0 + GMATRIX_DEFINE_ALL)
#define GMATRIX_DEFINE_MULTIPLY_CONST_COPY (0 + GMATRIX_DEFINE_ALL)
#define GMATRIX_DEFINE_MULTIPLY_CONST_ADD (0 + GMATRIX_DEFINE_ALL)
#define GMATRIX_DEFINE_ADD_COPY (0 + GMATRIX_DEFINE_ALL)
#define GMATRIX_DEFINE_ADD (0 + GMATRIX_DEFINE_ALL)
#define GMATRIX_DEFINE_SUBSTRACT_COPY (0 + GMATRIX_DEFINE_ALL)
#define GMATRIX_DEFINE_SUBSTRACT_IDENTITY_COPY (0 + GMATRIX_DEFINE_ALL)
#define GMATRIX_DEFINE_SUBSTRACT_IDENTITY (0 + GMATRIX_DEFINE_ALL)
#define GMATRIX_DEFINE_SUBSTRACT (0 + GMATRIX_DEFINE_ALL)
#define GMATRIX_DEFINE_MULTIPLY_COPY (0 + GMATRIX_DEFINE_ALL)
#define GMATRIX_DEFINE_MULTIPLY_COPY_EXTENDED (0 + GMATRIX_DEFINE_ALL)
#define GMATRIX_DEFINE_MULTIPLY_ADD (0 + GMATRIX_DEFINE_ALL)
#define GMATRIX_DEFINE_MULTIPLY_ADD_EXTENDED (0 + GMATRIX_DEFINE_ALL)
#define GMATRIX_DEFINE_MULTIPLY_SUBSTRACT (0 + GMATRIX_DEFINE_ALL)
#define GMATRIX_DEFINE_TRIPLEMULTIPLY_COPY (0 + GMATRIX_DEFINE_ALL)
#define GMATRIX_DEFINE_TRIPLEMULTIPLY_COPY_EXTENDED (0 + GMATRIX_DEFINE_ALL)
#define GMATRIX_DEFINE_TRIPLEMULTIPLY_ADD (0 + GMATRIX_DEFINE_ALL)
#define GMATRIX_DEFINE_TRIPLEMULTIPLY_ADD_EXTENDED (0 + GMATRIX_DEFINE_ALL)
#define GMATRIX_DEFINE_COVARIANCE_PROPAGATION_COPY (0 + GMATRIX_DEFINE_ALL)
#define GMATRIX_DEFINE_COVARIANCE_PROPAGATION_ADD (0 + GMATRIX_DEFINE_ALL)
#define GMATRIX_DEFINE_MAHALANOBIS_DISTANCE (0 + GMATRIX_DEFINE_ALL)
#define GMATRIX_DEFINE_SUBMATRIX_COPY (0 + GMATRIX_DEFINE_ALL)
#define GMATRIX_DEFINE_SUBMATRIX_ADD (0 + GMATRIX_DEFINE_ALL)
#define GMATRIX_DEFINE_SUBMATRIX_COPY_EXTENDED (0 + GMATRIX_DEFINE_ALL)
#define GMATRIX_DEFINE_SUBMATRIX_FILL (0 + GMATRIX_DEFINE_ALL)
#define GMATRIX_DEFINE_SUBMATRIX_MULTIPLY_CONST (0 + GMATRIX_DEFINE_ALL)
#define GMATRIX_DEFINE_PSEUDOINVERSE (0 + GMATRIX_DEFINE_ALL)
#define GMATRIX_DEFINE_LEFT_PSEUDOINVERSE_COPY (0 + GMATRIX_DEFINE_ALL)
#define GMATRIX_DEFINE_DERIVATIVE_LEFT_PSEUDOINVERSE (0 + GMATRIX_DEFINE_ALL)
#define GMATRIX_DEFINE_RANK_FROMSVD (0 + GMATRIX_DEFINE_ALL)
#define GMATRIX_DEFINE_RANK (0 + GMATRIX_DEFINE_ALL)
#define GMATRIX_DEFINE_MEAN (0 + GMATRIX_DEFINE_ALL)
#define GMATRIX_DEFINE_VARIANCE (0 + GMATRIX_DEFINE_ALL)
#define GMATRIX_DEFINE_NORM (0 + GMATRIX_DEFINE_ALL)
#define GMATRIX_DEFINE_SPARSITY_COEFFICIENT (0 + GMATRIX_DEFINE_ALL)
#define GMATRIXCONST_PI 3.14159265358979310000
#define GMATRIXCONST_2PI 6.28318530717958620000
#define GMATRIXCONST_E 2.71828182845904550000
#define GMATRIXMACRO_SIGN(a) ((a) >= 0.0 ? 1.0 : -1.0)
#define GMATRIXMACRO_SWAP(a, b) {temp = (a); (a) = (b); (b) = temp;}
#define GMATRIXMACRO_MAX(a, b) ((a) > (b) ? (a) : (b))
#define GMATRIXMACRO_MIN(a, b) ((a) > (b) ? (b) : (a))
#define GMATRIXMACRO_SQR(a) ((a)*(a))
#define GMATRIXMACRO_SIGNCHAR(a) ((a) >= 0.0 ? ' ' : '-')
#define GMATRIX_DECLARE(MatName, NLIN, NCOL)
#define GMATRIX_DATA(Mat, i, j) (*(&Mat.Data[i-1+(j-1)*Mat.Nr]))
#define PGMATRIX_DATA(pMat, i, j) (*(&pMat->Data[i-1+(j-1)*pMat->Nr]))
#define GMATRIX_ERROR(msg) {GMATRIX_PRINTCOMMAND(`\n%s`,msg); GMATRIX_ABORT_FUNCTION;}
#define GMATRIX_ASSERT(CallingFunction, TestFailCode)
#define GMATRIX_ABORT_FUNCTION {GMATRIX_PRINTCOMMAND(`\nAborting...`);GMATRIX_ABORTCOMMAND;}
#define GMATRIX_SETSIZE(Mat, Nll, Ncc) PGMATRIX_SETSIZE(&Mat,Nll,Ncc)
#define GMATRIX_PRINT(Mat) PGMATRIX_PRINT_NAMED(#Mat,&Mat)
#define PGMATRIX_PRINT(pMat) PGMATRIX_PRINT_NAMED(#pMat,pMat)
#define GMATRIX_PRINT_MATLABFORM(Mat) PGMATRIX_PRINT_MATLABFORM_NAMED(#Mat,&Mat)
#define PGMATRIX_PRINT_MATLABFORM(pMat) PGMATRIX_PRINT_MATLABFORM_NAMED(#pMat,pMat)
#define GMATRIX_PRINTROW(Mat, i) PGMATRIX_PRINTROW_NAMED(#Mat,&Mat,i)
#define PGMATRIX_PRINTROW(pMat, i) PGMATRIX_PRINTROW_NAMED(#pMat,pMat,i)
#define GMATRIX_PRINT_EXP(Mat) PGMATRIX_PRINT_EXP_NAMED(#Mat,&Mat)
#define PGMATRIX_PRINT_EXP(pMat) PGMATRIX_PRINT_EXP_NAMED(#pMat,pMat)
#define GMATRIX_INFO(Mat) PGMATRIX_INFO_NAMED(#Mat,&Mat)
#define PGMATRIX_INFO(pMat) PGMATRIX_INFO_NAMED(#pMat,pMat)
#define GMATRIX_ZEROES(Mat) PGMATRIX_ZEROES(&Mat)
#define GMATRIX_SUMLINCOL(Mat) PGMATRIX_SUMLINCOL(&Mat)
#define GMATRIX_ONES(Mat) PGMATRIX_ONES(&Mat)
#define GMATRIX_RAND(Mat) PGMATRIX_RAND(&Mat)
#define GMATRIX_RANDN(Mat) PGMATRIX_RANDN(&Mat)
#define GMATRIX_IDENTITY(Mat) PGMATRIX_IDENTITY(&Mat)
#define GMATRIX_WILKINSON(Mat) PGMATRIX_WILKINSON(&Mat)
#define GMATRIX_ORTHOGONAL(Mat, Type) PGMATRIX_ORTHOGONAL(&Mat,Type)
#define GMATRIX_COPY(MatResult, Mat) PGMATRIX_COPY(&MatResult, &Mat)
#define GMATRIX_COPY_COLUMN(MatResult, ColDest, Mat, ColOrigin) PGMATRIX_COPY_COLUMN(&MatResult, ColDest, &Mat, ColOrigin)
#define GMATRIX_COPY_ROW(MatResult, RowDest, Mat, RowOrigin) PGMATRIX_COPY_ROW(&MatResult, RowDest, &Mat, RowOrigin)
#define GMATRIX_TRANSPOSE_COPY(MatTranspose, Mat) PGMATRIX_TRANSPOSE_COPY(&MatTranspose, &Mat)
#define GMATRIX_TRACE(Mat) PGMATRIX_TRACE(&Mat)
#define GMATRIX_SUMENTRIES(Mat) PGMATRIX_SUMENTRIES(&Mat)
#define GMATRIX_SUMABSOLUTEENTRIES(Mat) PGMATRIX_SUMABSOLUTEENTRIES(&Mat)
#define GMATRIX_SWAP_ROW(Mat, i, j) PGMATRIX_SWAP_ROW(&Mat,i,j)
#define GMATRIX_SWAP_COLUMN(Mat, i, j) PGMATRIX_SWAP_COLUMN(&Mat,i,j)
#define GMATRIX_ADD_CONST(Mat, Value) PGMATRIX_ADD_CONST(&Mat,Value)
#define GMATRIX_CROSS_COPY(MatResult, MatA, MatB) PGMATRIX_CROSS_COPY(&MatResult, &MatA, &MatB)
#define GMATRIX_MULTIPLY_CONST(Mat, Value) PGMATRIX_MULTIPLY_CONST(&Mat,Value)
#define GMATRIX_MULTIPLY_CONST_COPY(MatResult, Mat, Value) PGMATRIX_MULTIPLY_CONST_COPY(&MatResult, &Mat,Value)
#define GMATRIX_MULTIPLY_CONST_ADD(MatResult, Mat, Value) PGMATRIX_MULTIPLY_CONST_ADD(&MatResult, &Mat,Value)
#define GMATRIX_NORM(Mat) PGMATRIX_NORM(&Mat)
#define GMATRIX_ADD_COPY(MatResult, MatA, MatB) PGMATRIX_ADD_COPY(&MatResult, &MatA, &MatB)
#define GMATRIX_ADD(MatA, MatB) PGMATRIX_ADD(&MatA, &MatB)
#define GMATRIX_SUBTRACT_COPY(MatResult, MatA, MatB) PGMATRIX_SUBTRACT_COPY(&MatResult, &MatA, &MatB)
#define PGMATRIX_SUBTRACT_COPY(pMatResult, pMatA, pMatB) PGMATRIX_SUBSTRACT_COPY(pMatResult, pMatA, pMatB)
#define GMATRIX_SUBSTRACT_COPY(MatResult, MatA, MatB) PGMATRIX_SUBSTRACT_COPY(&MatResult, &MatA, &MatB)
#define GMATRIX_SUBSTRACT_IDENTITY_COPY(MatResult, Mat) PGMATRIX_SUBSTRACT_IDENTITY_COPY(&MatResult, &Mat)
#define GMATRIX_SUBSTRACT_IDENTITY(Mat) PGMATRIX_SUBSTRACT_IDENTITY(&Mat)
#define GMATRIX_SUBSTRACT(MatA, MatB) PGMATRIX_SUBSTRACT(&MatA, &MatB)
#define GMATRIX_MULTIPLY_COPY(MatResult, MatA, MatB) PGMATRIX_MULTIPLY_COPY(&MatResult, &MatA, &MatB)
#define GMATRIX_MULTIPLY_COPY_EXTENDED(MatResult, MatA, FlagTransposeA, MatB, FlagTransposeB) PGMATRIX_MULTIPLY_COPY_EXTENDED(&MatResult, &MatA, FlagTransposeA, &MatB, FlagTransposeB)
#define GMATRIX_MULTIPLY_ADD(MatResult, MatA, MatB) PGMATRIX_MULTIPLY_ADD(&MatResult, &MatA, &MatB)
#define GMATRIX_MULTIPLY_ADD_EXTENDED(MatResult, MatA, FlagTransposeA, MatB, FlagTransposeB) PGMATRIX_MULTIPLY_ADD_EXTENDED(&MatResult, &MatA, FlagTransposeA, &MatB, FlagTransposeB)
#define GMATRIX_MULTIPLY_SUBSTRACT(MatResult, MatA, MatB) PGMATRIX_MULTIPLY_SUBSTRACT(&MatResult, &MatA, &MatB)
#define GMATRIX_TRIPLEMULTIPLY_COPY(MatResult, MatA, MatB, MatC, MatDummy) PGMATRIX_TRIPLEMULTIPLY_COPY(&MatResult, &MatA, &MatB, &MatC, &MatDummy)
#define GMATRIX_TRIPLEMULTIPLY_COPY_EXTENDED(MatResult, MatA, FlagTransposeA, MatB, FlagTransposeB, MatC, FlagTransposeC, MatDummy) PGMATRIX_TRIPLEMULTIPLY_COPY_EXTENDED(&MatResult, &MatA, FlagTransposeA, &MatB, FlagTransposeB, &MatC, FlagTransposeC, &MatDummy)
#define GMATRIX_TRIPLEMULTIPLY_ADD(MatResult, MatA, MatB, MatC, MatDummy) PGMATRIX_TRIPLEMULTIPLY_ADD(&MatResult, &MatA, &MatB, &MatC, &MatDummy)
#define GMATRIX_TRIPLEMULTIPLY_ADD_EXTENDED(MatResult, MatA, FlagTransposeA, MatB, FlagTransposeB, MatC, FlagTransposeC, MatDummy) PGMATRIX_TRIPLEMULTIPLY_ADD_EXTENDED(&MatResult, &MatA, FlagTransposeA, &MatB, FlagTransposeB, &MatC, FlagTransposeC, &MatDummy)
#define GMATRIX_SUBMATRIX_COPY(Mat, nl, nc, MatOrigin) PGMATRIX_SUBMATRIX_COPY(&Mat,nl,nc,&MatOrigin);
#define GMATRIX_SUBMATRIX_ADD(Mat, nl, nc, MatOrigin) PGMATRIX_SUBMATRIX_ADD(&Mat,nl,nc,&MatOrigin);
#define GMATRIX_SUBMATRIX_COPY_EXTENDED(Mat, nl, nc, MatOrigin, FlagTransposeOrigin) PGMATRIX_SUBMATRIX_COPY_EXTENDED(&Mat,nl,nc,&MatOrigin,FlagTransposeOrigin);
#define GMATRIX_SUBMATRIX_FILL(Mat, nlb, nle, ncb, nce, Value) PGMATRIX_SUBMATRIX_FILL(&Mat,nlb,nle,ncb,nce,Value)
#define GMATRIX_SUBMATRIX_MULTIPLY_CONST(Mat, nlb, nle, ncb, nce, Value) PGMATRIX_SUBMATRIX_MULTIPLY_CONST(&Mat,nlb,nle,ncb,nce,Value)
Typedefs
typedef struct GMATRIX * PGMATRIX
typedef struct DUMMY_MATRICES * PDUMMY_MATRICES
Functions
PGMATRIX PGMATRIX_ALLOC (int Nr, int Nc)
void PGMATRIX_FREE (PGMATRIX pMatrix)
void PGMATRIX_SETSIZE (PGMATRIX pMat, int Nll, int Ncc)
void PGMATRIX_PRINT_NAMED (char *NameString, PGMATRIX pMat)
void PGMATRIX_PRINT_MATLABFORM_NAMED (char *NameString, PGMATRIX pMat)
void PGMATRIX_PRINTROW_NAMED (char *NameString, PGMATRIX pMat, int i)
void PGMATRIX_PRINT_EXP_NAMED (char *NameString, PGMATRIX pMat)
void PGMATRIX_INFO_NAMED (char *NameString, PGMATRIX pMat)
void PGMATRIX_ZEROES (PGMATRIX pMat)
void PGMATRIX_SUMLINCOL (PGMATRIX pMat)
void PGMATRIX_ONES (PGMATRIX pMat)
void PGMATRIX_RAND (PGMATRIX pMat)
void PGMATRIX_RANDN (PGMATRIX pMat)
void PGMATRIX_IDENTITY (PGMATRIX pMat)
void PGMATRIX_WILKINSON (PGMATRIX pMat)
void PGMATRIX_ORTHOGONAL (PGMATRIX pMat, int Type)
void PGMATRIX_COPY (PGMATRIX pMatResult, PGMATRIX pMat)
void PGMATRIX_COPY_COLUMN (PGMATRIX pMatResult, int ColDest, PGMATRIX pMat, int ColOrigin)
void PGMATRIX_COPY_ROW (PGMATRIX pMatResult, int RowDest, PGMATRIX pMat, int RowOrigin)
void PGMATRIX_TRANSPOSE_COPY (PGMATRIX pMatTranspose, PGMATRIX pMat)
GMATRIX_FLOAT PGMATRIX_TRACE (PGMATRIX pMat)
GMATRIX_FLOAT PGMATRIX_SUMENTRIES (PGMATRIX pMat)
GMATRIX_FLOAT PGMATRIX_SUMABSOLUTEENTRIES (PGMATRIX pMat)
void PGMATRIX_SWAP_ROW (PGMATRIX pMat, int i, int j)
void PGMATRIX_SWAP_COLUMN (PGMATRIX pMat, int i, int j)
void PGMATRIX_ADD_CONST (PGMATRIX pMat, GMATRIX_FLOAT Value)
void PGMATRIX_CROSS_COPY (PGMATRIX pMatResult, PGMATRIX pMatA, PGMATRIX pMatB)
void PGMATRIX_MULTIPLY_CONST (PGMATRIX pMat, GMATRIX_FLOAT Value)
void PGMATRIX_MULTIPLY_CONST_COPY (PGMATRIX pMatResult, PGMATRIX pMat, GMATRIX_FLOAT Value)
void PGMATRIX_MULTIPLY_CONST_ADD (PGMATRIX pMatResult, PGMATRIX pMat, GMATRIX_FLOAT Value)
GMATRIX_FLOAT PGMATRIX_NORM (PGMATRIX pMat)
void PGMATRIX_ADD_COPY (PGMATRIX pMatResult, PGMATRIX pMatA, PGMATRIX pMatB)
void PGMATRIX_ADD (PGMATRIX pMatA, PGMATRIX pMatB)
void PGMATRIX_SUBSTRACT_COPY (PGMATRIX pMatResult, PGMATRIX pMatA, PGMATRIX pMatB)
void PGMATRIX_SUBSTRACT_IDENTITY_COPY (PGMATRIX pMatResult, PGMATRIX pMat)
void PGMATRIX_SUBSTRACT_IDENTITY (PGMATRIX pMat)
void PGMATRIX_SUBSTRACT (PGMATRIX pMatA, PGMATRIX pMatB)
void PGMATRIX_MULTIPLY_COPY (PGMATRIX pMatResult, PGMATRIX pMatA, PGMATRIX pMatB)
void PGMATRIX_MULTIPLY_COPY_EXTENDED (PGMATRIX pMatResult, PGMATRIX pMatA, int FlagTransposeA, PGMATRIX pMatB, int FlagTransposeB)
void PGMATRIX_MULTIPLY_ADD (PGMATRIX pMatResult, PGMATRIX pMatA, PGMATRIX pMatB)
void PGMATRIX_MULTIPLY_ADD_EXTENDED (PGMATRIX pMatResult, PGMATRIX pMatA, int FlagTransposeA, PGMATRIX pMatB, int FlagTransposeB)
void PGMATRIX_MULTIPLY_SUBSTRACT (PGMATRIX pMatResult, PGMATRIX pMatA, PGMATRIX pMatB)
void PGMATRIX_TRIPLEMULTIPLY_COPY (PGMATRIX pMatResult, PGMATRIX pMatA, PGMATRIX pMatB, PGMATRIX pMatC, PGMATRIX pMatDummy)
void PGMATRIX_TRIPLEMULTIPLY_COPY_EXTENDED (PGMATRIX pMatResult, PGMATRIX pMatA, BOOL FlagTransposeA, PGMATRIX pMatB, BOOL FlagTransposeB, PGMATRIX pMatC, BOOL FlagTransposeC, PGMATRIX pMatDummy)
void PGMATRIX_TRIPLEMULTIPLY_ADD (PGMATRIX pMatResult, PGMATRIX pMatA, PGMATRIX pMatB, PGMATRIX pMatC, PGMATRIX pMatDummy)
void PGMATRIX_TRIPLEMULTIPLY_ADD_EXTENDED (PGMATRIX pMatResult, PGMATRIX pMatA, int FlagTransposeA, PGMATRIX pMatB, int FlagTransposeB, PGMATRIX pMatC, int FlagTransposeC, PGMATRIX pMatDummy)
void PGMATRIX_SUBMATRIX_COPY (PGMATRIX pMat, int nl, int nc, PGMATRIX pMatOrigin)
void PGMATRIX_SUBMATRIX_ADD (PGMATRIX pMat, int nl, int nc, PGMATRIX pMatOrigin)
void PGMATRIX_SUBMATRIX_COPY_EXTENDED (PGMATRIX pMat, int nl, int nc, PGMATRIX pMatOrigin, int FlagTransposeOrigin)
void PGMATRIX_SUBMATRIX_FILL (PGMATRIX pMat, int nlb, int nle, int ncb, int nce, GMATRIX_FLOAT Value)
void PGMATRIX_SUBMATRIX_MULTIPLY_CONST (PGMATRIX pMat, int nlb, int nle, int ncb, int nce, GMATRIX_FLOAT Value)
Macro Definition Documentation
#define BOOL unsigned char
Definition at line 48 of file gmatrix.h.
#define FALSE 0
Definition at line 50 of file gmatrix.h.
#define GMATRIX_ABORT_FUNCTION {GMATRIX_PRINTCOMMAND(`\nAborting...`);GMATRIX_ABORTCOMMAND;}
Definition at line 368 of file gmatrix.h.
#define GMATRIX_ABORTCOMMAND getchar();exit(1);
Definition at line 43 of file gmatrix.h.
#define GMATRIX_ADD(MatA, MatB) PGMATRIX_ADD(&MatA, &MatB)
Definition at line 484 of file gmatrix.h.
#define GMATRIX_ADD_CONST(Mat, Value) PGMATRIX_ADD_CONST(&Mat,Value)
Definition at line 462 of file gmatrix.h.
#define GMATRIX_ADD_COPY(MatResult, MatA, MatB) PGMATRIX_ADD_COPY(&MatResult, &MatA, &MatB)
Definition at line 481 of file gmatrix.h.
#define GMATRIX_ASSERT(CallingFunction, TestFailCode)
Value:
if(TestFailCode){ \
                GMATRIX_PRINTCOMMAND("\n*** Warning (%s) in function %s",#TestFailCode,CallingFunction);\
                GMATRIX_ABORT_FUNCTION;\
        }
Definition at line 344 of file gmatrix.h.
Referenced by PGMATRIX_PSEUDOINVERSE_PLUS(), and PGMATRIX_SET_COLUMN_BY_DQ().
#define GMATRIX_COPY(MatResult, Mat) PGMATRIX_COPY(&MatResult, &Mat)
Definition at line 435 of file gmatrix.h.
#define GMATRIX_COPY_COLUMN(MatResult, ColDest, Mat, ColOrigin) PGMATRIX_COPY_COLUMN(&MatResult, ColDest, &Mat, ColOrigin)
Definition at line 438 of file gmatrix.h.
#define GMATRIX_COPY_ROW(MatResult, RowDest, Mat, RowOrigin) PGMATRIX_COPY_ROW(&MatResult, RowDest, &Mat, RowOrigin)
Definition at line 441 of file gmatrix.h.
#define GMATRIX_CROSS_COPY(MatResult, MatA, MatB) PGMATRIX_CROSS_COPY(&MatResult, &MatA, &MatB)
Definition at line 465 of file gmatrix.h.
#define GMATRIX_DATA(Mat, i, j) (*(&Mat.Data[i-1+(j-1)*Mat.Nr]))
Definition at line 336 of file gmatrix.h.
#define GMATRIX_DECLARE(MatName, NLIN, NCOL)
Value:
GMATRIX_FLOAT MatName##_Data[NLIN*NCOL]; \
        GMATRIX MatName = {NLIN,NCOL,NLIN*NCOL,&MatName##_Data[0]}
Definition at line 329 of file gmatrix.h.
#define GMATRIX_DEFINE_ADD (0 + GMATRIX_DEFINE_ALL)
Definition at line 185 of file gmatrix.h.
#define GMATRIX_DEFINE_ADD_CONST (0 + GMATRIX_DEFINE_ALL)
Definition at line 167 of file gmatrix.h.
#define GMATRIX_DEFINE_ADD_COPY (0 + GMATRIX_DEFINE_ALL)
Definition at line 182 of file gmatrix.h.
#define GMATRIX_DEFINE_ALL (1)
Definition at line 59 of file gmatrix.h.
#define GMATRIX_DEFINE_ALLOC (0 + GMATRIX_DEFINE_ALL)
Definition at line 62 of file gmatrix.h.
#define GMATRIX_DEFINE_CHOLESKY (0 + GMATRIX_DEFINE_ALL)
Definition at line 134 of file gmatrix.h.
#define GMATRIX_DEFINE_COPY (0 + GMATRIX_DEFINE_ALL)
Definition at line 107 of file gmatrix.h.
#define GMATRIX_DEFINE_COPY_COLUMN (0 + GMATRIX_DEFINE_ALL)
Definition at line 110 of file gmatrix.h.
#define GMATRIX_DEFINE_COPY_ROW (0 + GMATRIX_DEFINE_ALL)
Definition at line 113 of file gmatrix.h.
#define GMATRIX_DEFINE_COVARIANCE_PROPAGATION_ADD (0 + GMATRIX_DEFINE_ALL)
Definition at line 230 of file gmatrix.h.
#define GMATRIX_DEFINE_COVARIANCE_PROPAGATION_COPY (0 + GMATRIX_DEFINE_ALL)
Definition at line 227 of file gmatrix.h.
#define GMATRIX_DEFINE_CROSS (0 + GMATRIX_DEFINE_ALL)
Definition at line 170 of file gmatrix.h.
#define GMATRIX_DEFINE_DERIVATIVE_LEFT_PSEUDOINVERSE (0 + GMATRIX_DEFINE_ALL)
Definition at line 257 of file gmatrix.h.
#define GMATRIX_DEFINE_DETERMINANT (0 + GMATRIX_DEFINE_ALL)
Definition at line 143 of file gmatrix.h.
#define GMATRIX_DEFINE_DETERMINANT2 (0 + GMATRIX_DEFINE_ALL)
Definition at line 137 of file gmatrix.h.
#define GMATRIX_DEFINE_DETERMINANT3 (0 + GMATRIX_DEFINE_ALL)
Definition at line 140 of file gmatrix.h.
#define GMATRIX_DEFINE_GAUSSJORDAN (0 + GMATRIX_DEFINE_ALL)
Definition at line 131 of file gmatrix.h.
#define GMATRIX_DEFINE_IDENTITY (0 + GMATRIX_DEFINE_ALL)
Definition at line 98 of file gmatrix.h.
#define GMATRIX_DEFINE_INFO (0 + GMATRIX_DEFINE_ALL)
Definition at line 80 of file gmatrix.h.
#define GMATRIX_DEFINE_INVERSE (0 + GMATRIX_DEFINE_ALL)
Definition at line 155 of file gmatrix.h.
#define GMATRIX_DEFINE_INVERSE2_COPY (0 + GMATRIX_DEFINE_ALL)
Definition at line 146 of file gmatrix.h.
#define GMATRIX_DEFINE_INVERSE3_COPY (0 + GMATRIX_DEFINE_ALL)
Definition at line 149 of file gmatrix.h.
#define GMATRIX_DEFINE_INVERSE_COPY (0 + GMATRIX_DEFINE_ALL)
Definition at line 152 of file gmatrix.h.
#define GMATRIX_DEFINE_LEFT_PSEUDOINVERSE_COPY (0 + GMATRIX_DEFINE_ALL)
Definition at line 254 of file gmatrix.h.
#define GMATRIX_DEFINE_LUDCMP (0 + GMATRIX_DEFINE_ALL)
Definition at line 128 of file gmatrix.h.
#define GMATRIX_DEFINE_MAHALANOBIS_DISTANCE (0 + GMATRIX_DEFINE_ALL)
Definition at line 233 of file gmatrix.h.
#define GMATRIX_DEFINE_MEAN (0 + GMATRIX_DEFINE_ALL)
Definition at line 266 of file gmatrix.h.
#define GMATRIX_DEFINE_MULTIPLY_ADD (0 + GMATRIX_DEFINE_ALL)
Definition at line 206 of file gmatrix.h.
#define GMATRIX_DEFINE_MULTIPLY_ADD_EXTENDED (0 + GMATRIX_DEFINE_ALL)
Definition at line 209 of file gmatrix.h.
#define GMATRIX_DEFINE_MULTIPLY_CONST (0 + GMATRIX_DEFINE_ALL)
Definition at line 173 of file gmatrix.h.
#define GMATRIX_DEFINE_MULTIPLY_CONST_ADD (0 + GMATRIX_DEFINE_ALL)
Definition at line 179 of file gmatrix.h.
#define GMATRIX_DEFINE_MULTIPLY_CONST_COPY (0 + GMATRIX_DEFINE_ALL)
Definition at line 176 of file gmatrix.h.
#define GMATRIX_DEFINE_MULTIPLY_COPY (0 + GMATRIX_DEFINE_ALL)
Definition at line 200 of file gmatrix.h.
#define GMATRIX_DEFINE_MULTIPLY_COPY_EXTENDED (0 + GMATRIX_DEFINE_ALL)
Definition at line 203 of file gmatrix.h.
#define GMATRIX_DEFINE_MULTIPLY_SUBSTRACT (0 + GMATRIX_DEFINE_ALL)
Definition at line 212 of file gmatrix.h.
#define GMATRIX_DEFINE_NORM (0 + GMATRIX_DEFINE_ALL)
Definition at line 272 of file gmatrix.h.
#define GMATRIX_DEFINE_ONES (0 + GMATRIX_DEFINE_ALL)
Definition at line 89 of file gmatrix.h.
#define GMATRIX_DEFINE_ORTHOGONAL (0 + GMATRIX_DEFINE_ALL)
Definition at line 104 of file gmatrix.h.
#define GMATRIX_DEFINE_PRINT (0 + GMATRIX_DEFINE_ALL)
Definition at line 68 of file gmatrix.h.
#define GMATRIX_DEFINE_PRINT_EXP (0 + GMATRIX_DEFINE_ALL)
Definition at line 77 of file gmatrix.h.
#define GMATRIX_DEFINE_PRINT_MATLABFORM (0 + GMATRIX_DEFINE_ALL)
Definition at line 71 of file gmatrix.h.
#define GMATRIX_DEFINE_PRINTROW (0 + GMATRIX_DEFINE_ALL)
Definition at line 74 of file gmatrix.h.
#define GMATRIX_DEFINE_PSEUDOINVERSE (0 + GMATRIX_DEFINE_ALL)
Definition at line 251 of file gmatrix.h.
#define GMATRIX_DEFINE_RAND (0 + GMATRIX_DEFINE_ALL)
Definition at line 92 of file gmatrix.h.
#define GMATRIX_DEFINE_RANDN (0 + GMATRIX_DEFINE_ALL)
Definition at line 95 of file gmatrix.h.
#define GMATRIX_DEFINE_RANK (0 + GMATRIX_DEFINE_ALL)
Definition at line 263 of file gmatrix.h.
#define GMATRIX_DEFINE_RANK_FROMSVD (0 + GMATRIX_DEFINE_ALL)
Definition at line 260 of file gmatrix.h.
#define GMATRIX_DEFINE_SETSIZE (0 + GMATRIX_DEFINE_ALL)
Definition at line 65 of file gmatrix.h.
#define GMATRIX_DEFINE_SPARSITY_COEFFICIENT (0 + GMATRIX_DEFINE_ALL)
Definition at line 275 of file gmatrix.h.
#define GMATRIX_DEFINE_SUBMATRIX_ADD (0 + GMATRIX_DEFINE_ALL)
Definition at line 239 of file gmatrix.h.
#define GMATRIX_DEFINE_SUBMATRIX_COPY (0 + GMATRIX_DEFINE_ALL)
Definition at line 236 of file gmatrix.h.
#define GMATRIX_DEFINE_SUBMATRIX_COPY_EXTENDED (0 + GMATRIX_DEFINE_ALL)
Definition at line 242 of file gmatrix.h.
#define GMATRIX_DEFINE_SUBMATRIX_FILL (0 + GMATRIX_DEFINE_ALL)
Definition at line 245 of file gmatrix.h.
#define GMATRIX_DEFINE_SUBMATRIX_MULTIPLY_CONST (0 + GMATRIX_DEFINE_ALL)
Definition at line 248 of file gmatrix.h.
#define GMATRIX_DEFINE_SUBSTRACT (0 + GMATRIX_DEFINE_ALL)
Definition at line 197 of file gmatrix.h.
#define GMATRIX_DEFINE_SUBSTRACT_COPY (0 + GMATRIX_DEFINE_ALL)
Definition at line 188 of file gmatrix.h.
#define GMATRIX_DEFINE_SUBSTRACT_IDENTITY (0 + GMATRIX_DEFINE_ALL)
Definition at line 194 of file gmatrix.h.
#define GMATRIX_DEFINE_SUBSTRACT_IDENTITY_COPY (0 + GMATRIX_DEFINE_ALL)
Definition at line 191 of file gmatrix.h.
#define GMATRIX_DEFINE_SUMABSOLUTEENTRIES (0 + GMATRIX_DEFINE_ALL)
Definition at line 125 of file gmatrix.h.
#define GMATRIX_DEFINE_SUMENTRIES (0 + GMATRIX_DEFINE_ALL)
Definition at line 122 of file gmatrix.h.
#define GMATRIX_DEFINE_SUMLINCOL (0 + GMATRIX_DEFINE_ALL)
Definition at line 86 of file gmatrix.h.
#define GMATRIX_DEFINE_SVD (0 + GMATRIX_DEFINE_ALL)
Definition at line 164 of file gmatrix.h.
#define GMATRIX_DEFINE_SWAP_COLUMN (0 + GMATRIX_DEFINE_ALL)
Definition at line 161 of file gmatrix.h.
#define GMATRIX_DEFINE_SWAP_ROW (0 + GMATRIX_DEFINE_ALL)
Definition at line 158 of file gmatrix.h.
#define GMATRIX_DEFINE_TRACE (0 + GMATRIX_DEFINE_ALL)
Definition at line 119 of file gmatrix.h.
#define GMATRIX_DEFINE_TRANSPOSE_COPY (0 + GMATRIX_DEFINE_ALL)
Definition at line 116 of file gmatrix.h.
#define GMATRIX_DEFINE_TRIPLEMULTIPLY_ADD (0 + GMATRIX_DEFINE_ALL)
Definition at line 221 of file gmatrix.h.
#define GMATRIX_DEFINE_TRIPLEMULTIPLY_ADD_EXTENDED (0 + GMATRIX_DEFINE_ALL)
Definition at line 224 of file gmatrix.h.
#define GMATRIX_DEFINE_TRIPLEMULTIPLY_COPY (0 + GMATRIX_DEFINE_ALL)
Definition at line 215 of file gmatrix.h.
#define GMATRIX_DEFINE_TRIPLEMULTIPLY_COPY_EXTENDED (0 + GMATRIX_DEFINE_ALL)
Definition at line 218 of file gmatrix.h.
#define GMATRIX_DEFINE_VARIANCE (0 + GMATRIX_DEFINE_ALL)
Definition at line 269 of file gmatrix.h.
#define GMATRIX_DEFINE_WILKINSON (0 + GMATRIX_DEFINE_ALL)
Definition at line 101 of file gmatrix.h.
#define GMATRIX_DEFINE_ZEROES (0 + GMATRIX_DEFINE_ALL)
Definition at line 83 of file gmatrix.h.
#define GMATRIX_ERROR(msg) {GMATRIX_PRINTCOMMAND(`\n%s`,msg); GMATRIX_ABORT_FUNCTION;}
Definition at line 342 of file gmatrix.h.
#define GMATRIX_FLOAT double
Definition at line 34 of file gmatrix.h.
Referenced by PGMATRIX_PSEUDOINVERSE_PLUS().
#define GMATRIX_IDENTITY(Mat) PGMATRIX_IDENTITY(&Mat)
Definition at line 426 of file gmatrix.h.
#define GMATRIX_INFO(Mat) PGMATRIX_INFO_NAMED(#Mat,&Mat)
Definition at line 406 of file gmatrix.h.
#define GMATRIX_MULTIPLY_ADD(MatResult, MatA, MatB) PGMATRIX_MULTIPLY_ADD(&MatResult, &MatA, &MatB)
Definition at line 507 of file gmatrix.h.
#define GMATRIX_MULTIPLY_ADD_EXTENDED(MatResult, MatA, FlagTransposeA, MatB, FlagTransposeB) PGMATRIX_MULTIPLY_ADD_EXTENDED(&MatResult, &MatA, FlagTransposeA, &MatB, FlagTransposeB)
Definition at line 510 of file gmatrix.h.
#define GMATRIX_MULTIPLY_CONST(Mat, Value) PGMATRIX_MULTIPLY_CONST(&Mat,Value)
Definition at line 469 of file gmatrix.h.
#define GMATRIX_MULTIPLY_CONST_ADD(MatResult, Mat, Value) PGMATRIX_MULTIPLY_CONST_ADD(&MatResult, &Mat,Value)
Definition at line 475 of file gmatrix.h.
#define GMATRIX_MULTIPLY_CONST_COPY(MatResult, Mat, Value) PGMATRIX_MULTIPLY_CONST_COPY(&MatResult, &Mat,Value)
Definition at line 472 of file gmatrix.h.
#define GMATRIX_MULTIPLY_COPY(MatResult, MatA, MatB) PGMATRIX_MULTIPLY_COPY(&MatResult, &MatA, &MatB)
Definition at line 501 of file gmatrix.h.
#define GMATRIX_MULTIPLY_COPY_EXTENDED(MatResult, MatA, FlagTransposeA, MatB, FlagTransposeB) PGMATRIX_MULTIPLY_COPY_EXTENDED(&MatResult, &MatA, FlagTransposeA, &MatB, FlagTransposeB)
Definition at line 504 of file gmatrix.h.
#define GMATRIX_MULTIPLY_SUBSTRACT(MatResult, MatA, MatB) PGMATRIX_MULTIPLY_SUBSTRACT(&MatResult, &MatA, &MatB)
Definition at line 514 of file gmatrix.h.
#define GMATRIX_NORM(Mat) PGMATRIX_NORM(&Mat)
Definition at line 478 of file gmatrix.h.
#define GMATRIX_ONES(Mat) PGMATRIX_ONES(&Mat)
Definition at line 417 of file gmatrix.h.
#define GMATRIX_ORTHOGONAL(Mat, Type) PGMATRIX_ORTHOGONAL(&Mat,Type)
Definition at line 432 of file gmatrix.h.
#define GMATRIX_PRINT(Mat) PGMATRIX_PRINT_NAMED(#Mat,&Mat)
Definition at line 389 of file gmatrix.h.
#define GMATRIX_PRINT_EXP(Mat) PGMATRIX_PRINT_EXP_NAMED(#Mat,&Mat)
Definition at line 398 of file gmatrix.h.
#define GMATRIX_PRINT_MATLABFORM(Mat) PGMATRIX_PRINT_MATLABFORM_NAMED(#Mat,&Mat)
Definition at line 392 of file gmatrix.h.
#define GMATRIX_PRINTCOMMAND printf
Definition at line 38 of file gmatrix.h.
#define GMATRIX_PRINTROW(Mat, i) PGMATRIX_PRINTROW_NAMED(#Mat,&Mat,i)
Definition at line 395 of file gmatrix.h.
#define GMATRIX_RAND(Mat) PGMATRIX_RAND(&Mat)
Definition at line 420 of file gmatrix.h.
#define GMATRIX_RANDN(Mat) PGMATRIX_RANDN(&Mat)
Definition at line 423 of file gmatrix.h.
#define GMATRIX_SETSIZE(Mat, Nll, Ncc) PGMATRIX_SETSIZE(&Mat,Nll,Ncc)
Definition at line 386 of file gmatrix.h.
#define GMATRIX_SUBMATRIX_ADD(Mat, nl, nc, MatOrigin) PGMATRIX_SUBMATRIX_ADD(&Mat,nl,nc,&MatOrigin);
Definition at line 533 of file gmatrix.h.
#define GMATRIX_SUBMATRIX_COPY(Mat, nl, nc, MatOrigin) PGMATRIX_SUBMATRIX_COPY(&Mat,nl,nc,&MatOrigin);
Definition at line 530 of file gmatrix.h.
#define GMATRIX_SUBMATRIX_COPY_EXTENDED(Mat, nl, nc, MatOrigin, FlagTransposeOrigin) PGMATRIX_SUBMATRIX_COPY_EXTENDED(&Mat,nl,nc,&MatOrigin,FlagTransposeOrigin);
Definition at line 536 of file gmatrix.h.
#define GMATRIX_SUBMATRIX_FILL(Mat, nlb, nle, ncb, nce, Value) PGMATRIX_SUBMATRIX_FILL(&Mat,nlb,nle,ncb,nce,Value)
Definition at line 539 of file gmatrix.h.
#define GMATRIX_SUBMATRIX_MULTIPLY_CONST(Mat, nlb, nle, ncb, nce, Value) PGMATRIX_SUBMATRIX_MULTIPLY_CONST(&Mat,nlb,nle,ncb,nce,Value)
Definition at line 542 of file gmatrix.h.
#define GMATRIX_SUBSTRACT(MatA, MatB) PGMATRIX_SUBSTRACT(&MatA, &MatB)
Definition at line 498 of file gmatrix.h.
#define GMATRIX_SUBSTRACT_COPY(MatResult, MatA, MatB) PGMATRIX_SUBSTRACT_COPY(&MatResult, &MatA, &MatB)
Definition at line 489 of file gmatrix.h.
#define GMATRIX_SUBSTRACT_IDENTITY(Mat) PGMATRIX_SUBSTRACT_IDENTITY(&Mat)
Definition at line 495 of file gmatrix.h.
#define GMATRIX_SUBSTRACT_IDENTITY_COPY(MatResult, Mat) PGMATRIX_SUBSTRACT_IDENTITY_COPY(&MatResult, &Mat)
Definition at line 492 of file gmatrix.h.
#define GMATRIX_SUBTRACT_COPY(MatResult, MatA, MatB) PGMATRIX_SUBTRACT_COPY(&MatResult, &MatA, &MatB)
Definition at line 487 of file gmatrix.h.
#define GMATRIX_SUMABSOLUTEENTRIES(Mat) PGMATRIX_SUMABSOLUTEENTRIES(&Mat)
Definition at line 453 of file gmatrix.h.
#define GMATRIX_SUMENTRIES(Mat) PGMATRIX_SUMENTRIES(&Mat)
Definition at line 450 of file gmatrix.h.
#define GMATRIX_SUMLINCOL(Mat) PGMATRIX_SUMLINCOL(&Mat)
Definition at line 414 of file gmatrix.h.
#define GMATRIX_SWAP_COLUMN(Mat, i, j) PGMATRIX_SWAP_COLUMN(&Mat,i,j)
Definition at line 459 of file gmatrix.h.
#define GMATRIX_SWAP_ROW(Mat, i, j) PGMATRIX_SWAP_ROW(&Mat,i,j)
Definition at line 456 of file gmatrix.h.
#define GMATRIX_TRACE(Mat) PGMATRIX_TRACE(&Mat)
Definition at line 447 of file gmatrix.h.
#define GMATRIX_TRANSPOSE_COPY(MatTranspose, Mat) PGMATRIX_TRANSPOSE_COPY(&MatTranspose, &Mat)
Definition at line 444 of file gmatrix.h.
#define GMATRIX_TRIPLEMULTIPLY_ADD(MatResult, MatA, MatB, MatC, MatDummy) PGMATRIX_TRIPLEMULTIPLY_ADD(&MatResult, &MatA, &MatB, &MatC, &MatDummy)
Definition at line 523 of file gmatrix.h.
#define GMATRIX_TRIPLEMULTIPLY_ADD_EXTENDED(MatResult, MatA, FlagTransposeA, MatB, FlagTransposeB, MatC, FlagTransposeC, MatDummy) PGMATRIX_TRIPLEMULTIPLY_ADD_EXTENDED(&MatResult, &MatA, FlagTransposeA, &MatB, FlagTransposeB, &MatC, FlagTransposeC, &MatDummy)
Definition at line 526 of file gmatrix.h.
#define GMATRIX_TRIPLEMULTIPLY_COPY(MatResult, MatA, MatB, MatC, MatDummy) PGMATRIX_TRIPLEMULTIPLY_COPY(&MatResult, &MatA, &MatB, &MatC, &MatDummy)
Definition at line 517 of file gmatrix.h.
#define GMATRIX_TRIPLEMULTIPLY_COPY_EXTENDED(MatResult, MatA, FlagTransposeA, MatB, FlagTransposeB, MatC, FlagTransposeC, MatDummy) PGMATRIX_TRIPLEMULTIPLY_COPY_EXTENDED(&MatResult, &MatA, FlagTransposeA, &MatB, FlagTransposeB, &MatC, FlagTransposeC, &MatDummy)
Definition at line 520 of file gmatrix.h.
#define GMATRIX_WILKINSON(Mat) PGMATRIX_WILKINSON(&Mat)
Definition at line 429 of file gmatrix.h.
#define GMATRIX_ZEROES(Mat) PGMATRIX_ZEROES(&Mat)
Definition at line 411 of file gmatrix.h.
#define GMATRIXCONST_2PI 6.28318530717958620000
Definition at line 297 of file gmatrix.h.
#define GMATRIXCONST_E 2.71828182845904550000
Definition at line 298 of file gmatrix.h.
#define GMATRIXCONST_PI 3.14159265358979310000
Definition at line 296 of file gmatrix.h.
#define GMATRIXMACRO_MAX(a, b) ((a) > (b) ? (a) : (b))
Definition at line 302 of file gmatrix.h.
Referenced by PGMATRIX_PSEUDOINVERSE_PLUS().
#define GMATRIXMACRO_MIN(a, b) ((a) > (b) ? (b) : (a))
Definition at line 303 of file gmatrix.h.
#define GMATRIXMACRO_SIGN(a) ((a) >= 0.0 ? 1.0 : -1.0)
Definition at line 300 of file gmatrix.h.
#define GMATRIXMACRO_SIGNCHAR(a) ((a) >= 0.0 ? ' ' : '-')
Definition at line 305 of file gmatrix.h.
#define GMATRIXMACRO_SQR(a) ((a)*(a))
Definition at line 304 of file gmatrix.h.
#define GMATRIXMACRO_SWAP(a, b) {temp = (a); (a) = (b); (b) = temp;}
Definition at line 301 of file gmatrix.h.
#define PGMATRIX_DATA(pMat, i, j) (*(&pMat->Data[i-1+(j-1)*pMat->Nr]))
Definition at line 337 of file gmatrix.h.
Referenced by Cartesian_pose_controller::control(), Cartesian_controller::getSchunkPositionsAndVelocitiesAndUpdateThetasAndDThetas(), main(), PGMATRIX_CREATE_DIAG_FROM_ARRAY(), PGMATRIX_CREATE_FROM_ARRAY(), PGMATRIX_DAMPED_LEASTSQUARES_PSEUDOINVERSE(), PGMATRIX_PSEUDOINVERSE_PLUS(), PGMATRIX_RIGHT_PSEUDOINVERSE_NULLSPACE_PROJECTOR(), PGMATRIX_SET_COLUMN_BY_DQ(), Cartesian_pose_controller::printPose(), Cartesian_velocity_controller::printVel(), Robot_getGJacobian(), Robot_getOJacobianAngleP(), Robot_updateLinksThetasByMatrix(), Cartesian_controller::setSchunkVelocitiesAndSend(), Cartesian_pose_controller::updateReferences(), and Cartesian_velocity_controller::updateReferences().
#define PGMATRIX_INFO(pMat) PGMATRIX_INFO_NAMED(#pMat,pMat)
Definition at line 407 of file gmatrix.h.
#define PGMATRIX_PRINT(pMat) PGMATRIX_PRINT_NAMED(#pMat,pMat)
Definition at line 390 of file gmatrix.h.
Referenced by main().
#define PGMATRIX_PRINT_EXP(pMat) PGMATRIX_PRINT_EXP_NAMED(#pMat,pMat)
Definition at line 399 of file gmatrix.h.
#define PGMATRIX_PRINT_MATLABFORM(pMat) PGMATRIX_PRINT_MATLABFORM_NAMED(#pMat,pMat)
Definition at line 393 of file gmatrix.h.
#define PGMATRIX_PRINTROW(pMat, i) PGMATRIX_PRINTROW_NAMED(#pMat,pMat,i)
Definition at line 396 of file gmatrix.h.
#define PGMATRIX_SUBTRACT_COPY(pMatResult, pMatA, pMatB) PGMATRIX_SUBSTRACT_COPY(pMatResult, pMatA, pMatB)
Definition at line 488 of file gmatrix.h.
Referenced by PGMATRIX_SUBTRACT_COPY_FREE().
#define TRUE 1
Definition at line 49 of file gmatrix.h.
Typedef Documentation
typedef struct DUMMY_MATRICES* PDUMMY_MATRICES
typedef struct GMATRIX * PGMATRIX
Function Documentation
void PGMATRIX_ADD (PGMATRIX pMatA, PGMATRIX pMatB)
void PGMATRIX_ADD_CONST (PGMATRIX pMat, GMATRIX_FLOAT Value)
void PGMATRIX_ADD_COPY (PGMATRIX pMatResult, PGMATRIX pMatA, PGMATRIX pMatB)
Referenced by PGMATRIX_ADD_COPY_FREE().
PGMATRIX PGMATRIX_ALLOC (int Nr, int Nc)
Referenced by main(), PGMATRIX_CREATE_DIAG_FROM_ARRAY(), PGMATRIX_CREATE_FROM_ARRAY(), PGMATRIX_CREATE_ZEROES(), PGMATRIX_DAMPED_LEASTSQUARES_PSEUDOINVERSE(), PGMATRIX_PSEUDOINVERSE_PLUS(), PGMATRIX_RIGHT_PSEUDOINVERSE(), PGMATRIX_RIGHT_PSEUDOINVERSE_NULLSPACE_PROJECTOR(), Robot_getAJacobian(), Robot_getGJacobian(), and Robot_getOJacobianAngleP().
void PGMATRIX_COPY (PGMATRIX pMatResult, PGMATRIX pMat)
Referenced by PGMATRIX_MULTIPLY_CONST_COPY_FREE().
void PGMATRIX_COPY_COLUMN (PGMATRIX pMatResult, int ColDest, PGMATRIX pMat, int ColOrigin)
void PGMATRIX_COPY_ROW (PGMATRIX pMatResult, int RowDest, PGMATRIX pMat, int RowOrigin)
Referenced by main(), and Robot_getOJacobianAngleP().
void PGMATRIX_CROSS_COPY (PGMATRIX pMatResult, PGMATRIX pMatA, PGMATRIX pMatB)
Referenced by Robot_getGJacobian().
void PGMATRIX_FREE (PGMATRIX pMatrix)
Referenced by Cartesian_pose_controller::control(), Cartesian_velocity_controller::control(), Cartesian_controller::controlCleanUp(), main(), PGMATRIX_ADD_COPY_FREE(), PGMATRIX_DAMPED_LEASTSQUARES_PSEUDOINVERSE(), PGMATRIX_MULTIPLY_CONST_COPY_FREE(), PGMATRIX_MULTIPLY_COPY_FREE(), PGMATRIX_PSEUDOINVERSE_PLUS(), PGMATRIX_RIGHT_PSEUDOINVERSE(), PGMATRIX_SUBTRACT_COPY_FREE(), Robot_getGJacobian(), and Robot_getOJacobianAngleP().
void PGMATRIX_IDENTITY (PGMATRIX pMat)
void PGMATRIX_INFO_NAMED (char * NameString, PGMATRIX pMat)
void PGMATRIX_MULTIPLY_ADD (PGMATRIX pMatResult, PGMATRIX pMatA, PGMATRIX pMatB)
void PGMATRIX_MULTIPLY_ADD_EXTENDED (PGMATRIX pMatResult, PGMATRIX pMatA, int FlagTransposeA, PGMATRIX pMatB, int FlagTransposeB)
void PGMATRIX_MULTIPLY_CONST (PGMATRIX pMat, GMATRIX_FLOAT Value)
Referenced by PGMATRIX_MULTIPLY_CONST_COPY_FREE().
void PGMATRIX_MULTIPLY_CONST_ADD (PGMATRIX pMatResult, PGMATRIX pMat, GMATRIX_FLOAT Value)
void PGMATRIX_MULTIPLY_CONST_COPY (PGMATRIX pMatResult, PGMATRIX pMat, GMATRIX_FLOAT Value)
void PGMATRIX_MULTIPLY_COPY (PGMATRIX pMatResult, PGMATRIX pMatA, PGMATRIX pMatB)
Referenced by PGMATRIX_MULTIPLY_COPY_FREE(), and Robot_getOJacobianAngleP().
void PGMATRIX_MULTIPLY_COPY_EXTENDED (PGMATRIX pMatResult, PGMATRIX pMatA, int FlagTransposeA, PGMATRIX pMatB, int FlagTransposeB)
Referenced by PGMATRIX_PSEUDOINVERSE_PLUS().
void PGMATRIX_MULTIPLY_SUBSTRACT (PGMATRIX pMatResult, PGMATRIX pMatA, PGMATRIX pMatB)
GMATRIX_FLOAT PGMATRIX_NORM (PGMATRIX pMat)
void PGMATRIX_ONES (PGMATRIX pMat)
void PGMATRIX_ORTHOGONAL (PGMATRIX pMat, int Type)
void PGMATRIX_PRINT_EXP_NAMED (char * NameString, PGMATRIX pMat)
void PGMATRIX_PRINT_MATLABFORM_NAMED (char * NameString, PGMATRIX pMat)
void PGMATRIX_PRINT_NAMED (char * NameString, PGMATRIX pMat)
void PGMATRIX_PRINTROW_NAMED (char * NameString, PGMATRIX pMat, int i)
void PGMATRIX_RAND (PGMATRIX pMat)
void PGMATRIX_RANDN (PGMATRIX pMat)
void PGMATRIX_SETSIZE (PGMATRIX pMat, int Nll, int Ncc)
void PGMATRIX_SUBMATRIX_ADD (PGMATRIX pMat, int nl, int nc, PGMATRIX pMatOrigin)
void PGMATRIX_SUBMATRIX_COPY (PGMATRIX pMat, int nl, int nc, PGMATRIX pMatOrigin)
void PGMATRIX_SUBMATRIX_COPY_EXTENDED (PGMATRIX pMat, int nl, int nc, PGMATRIX pMatOrigin, int FlagTransposeOrigin)
void PGMATRIX_SUBMATRIX_FILL (PGMATRIX pMat, int nlb, int nle, int ncb, int nce, GMATRIX_FLOAT Value)
void PGMATRIX_SUBMATRIX_MULTIPLY_CONST (PGMATRIX pMat, int nlb, int nle, int ncb, int nce, GMATRIX_FLOAT Value)
void PGMATRIX_SUBSTRACT (PGMATRIX pMatA, PGMATRIX pMatB)
void PGMATRIX_SUBSTRACT_COPY (PGMATRIX pMatResult, PGMATRIX pMatA, PGMATRIX pMatB)
void PGMATRIX_SUBSTRACT_IDENTITY (PGMATRIX pMat)
void PGMATRIX_SUBSTRACT_IDENTITY_COPY (PGMATRIX pMatResult, PGMATRIX pMat)
GMATRIX_FLOAT PGMATRIX_SUMABSOLUTEENTRIES (PGMATRIX pMat)
GMATRIX_FLOAT PGMATRIX_SUMENTRIES (PGMATRIX pMat)
void PGMATRIX_SUMLINCOL (PGMATRIX pMat)
void PGMATRIX_SWAP_COLUMN (PGMATRIX pMat, int i, int j)
void PGMATRIX_SWAP_ROW (PGMATRIX pMat, int i, int j)
GMATRIX_FLOAT PGMATRIX_TRACE (PGMATRIX pMat)
void PGMATRIX_TRANSPOSE_COPY (PGMATRIX pMatTranspose, PGMATRIX pMat)
Referenced by PGMATRIX_DAMPED_LEASTSQUARES_PSEUDOINVERSE(), and PGMATRIX_RIGHT_PSEUDOINVERSE().
void PGMATRIX_TRIPLEMULTIPLY_ADD (PGMATRIX pMatResult, PGMATRIX pMatA, PGMATRIX pMatB, PGMATRIX pMatC, PGMATRIX pMatDummy)
void PGMATRIX_TRIPLEMULTIPLY_ADD_EXTENDED (PGMATRIX pMatResult, PGMATRIX pMatA, int FlagTransposeA, PGMATRIX pMatB, int FlagTransposeB, PGMATRIX pMatC, int FlagTransposeC, PGMATRIX pMatDummy)
void PGMATRIX_TRIPLEMULTIPLY_COPY (PGMATRIX pMatResult, PGMATRIX pMatA, PGMATRIX pMatB, PGMATRIX pMatC, PGMATRIX pMatDummy)
void PGMATRIX_TRIPLEMULTIPLY_COPY_EXTENDED (PGMATRIX pMatResult, PGMATRIX pMatA, BOOL FlagTransposeA, PGMATRIX pMatB, BOOL FlagTransposeB, PGMATRIX pMatC, BOOL FlagTransposeC, PGMATRIX pMatDummy)
void PGMATRIX_WILKINSON (PGMATRIX pMat)
void PGMATRIX_ZEROES (PGMATRIX pMat)
Referenced by PGMATRIX_CREATE_ZEROES(), Robot_getAJacobian(), and Robot_getGJacobian().