gdatalogger/gmatlabdatafile.c File Reference
#include <stdio.h>
*
#include <stdlib.h>
*
#include <string.h>
*
#include `gmatlabdatafile.h`
*
Data Structures
struct MATLAB_DATAHEAD
Typedefs
typedef struct MATLAB_DATAHEAD * PMATLAB_DATAHEAD
Functions
int gMATLABDataFile_OpenWrite (PGMATLABDATAFILECONFIG pGMatlabDataFileConfig, char *filename, char *dirname)
int gMATLABDataFile_OpenRead (PGMATLABDATAFILECONFIG pGMatlabDataFileConfig, char *filename, char *dirname)
void gMATLABDataFile_Close (PGMATLABDATAFILECONFIG pGMatlabDataFileConfig)
int gMATLABDataFile_SaveVector (PGMATLABDATAFILECONFIG pGMatlabDataFileConfig, const char *varname, double *v, long nlin)
int gMATLABDataFile_SaveMatrix (PGMATLABDATAFILECONFIG pGMatlabDataFileConfig, const char *varname, double **m, long nlin, long ncol)
Typedef Documentation
typedef struct MATLAB_DATAHEAD * PMATLAB_DATAHEAD
Function Documentation
void gMATLABDataFile_Close (PGMATLABDATAFILECONFIG pGMatlabDataFileConfig)
Definition at line 58 of file gmatlabdatafile.c.
References GMATLABDATAFILECONFIG::fp.
Referenced by gDataLogger_Close().
{
        fclose(pGMatlabDataFileConfig->fp);
}
int gMATLABDataFile_OpenRead (PGMATLABDATAFILECONFIG pGMatlabDataFileConfig, char * filename, char * dirname)
Definition at line 40 of file gmatlabdatafile.c.
References FALSE, GMATLABDATAFILECONFIG::FileName, GMATLABDATAFILECONFIG::FlagStillNotSaved, GMATLABDATAFILECONFIG::fp, and TRUE.
{
        pGMatlabDataFileConfig->FileName[0] = '\0';
        if(dirname!=NULL)
                sprintf(pGMatlabDataFileConfig->FileName,"%s",dirname);
        strcat(pGMatlabDataFileConfig->FileName,filename);
        pGMatlabDataFileConfig->FlagStillNotSaved = TRUE;
        pGMatlabDataFileConfig->fp = fopen(pGMatlabDataFileConfig->FileName
      , "r");
        if(pGMatlabDataFileConfig->fp==NULL){
                return FALSE;
        }
        rewind(pGMatlabDataFileConfig->fp);
        return TRUE;
}
int gMATLABDataFile_OpenWrite (PGMATLABDATAFILECONFIG pGMatlabDataFileConfig, char * filename, char * dirname)
Definition at line 21 of file gmatlabdatafile.c.
References FALSE, GMATLABDATAFILECONFIG::FileName, GMATLABDATAFILECONFIG::FlagStillNotSaved, GMATLABDATAFILECONFIG::fp, and TRUE.
Referenced by gDataLogger_Init().
{
        pGMatlabDataFileConfig->FileName[0] = '\0';
        if(dirname!=NULL)
                sprintf(pGMatlabDataFileConfig->FileName,"%s",dirname);
        strcat(pGMatlabDataFileConfig->FileName,filename);
        pGMatlabDataFileConfig->FlagStillNotSaved = TRUE;
        pGMatlabDataFileConfig->fp = fopen(pGMatlabDataFileConfig->FileName
      , "w");
        if(pGMatlabDataFileConfig->fp==NULL){
                printf("\n pGMatlabDataFileConfig->fp==NULL: %s",
      pGMatlabDataFileConfig->FileName);
                return FALSE;
        }
        rewind(pGMatlabDataFileConfig->fp);
        return TRUE;
}
int gMATLABDataFile_SaveMatrix (PGMATLABDATAFILECONFIG pGMatlabDataFileConfig, const char * varname, double ** m, long nlin, long ncol)
Definition at line 92 of file gmatlabdatafile.c.
References FALSE, GMATLABDATAFILECONFIG::FlagStillNotSaved, GMATLABDATAFILECONFIG::fp, MATLAB_DATAHEAD::imagf, MATLAB_DATAHEAD::mrows, MATLAB_DATAHEAD::namlen, MATLAB_DATAHEAD::ncols, TRUE, and MATLAB_DATAHEAD::type.
{
        MATLAB_DATAHEAD DataHead;
        int nl,nc;
        double *vcol;
        DataHead.type = (long)(0);
        DataHead.mrows = (long)(nlin);
        DataHead.ncols = (long)(ncol);
        DataHead.imagf = (long)(0);
        DataHead.namlen = (long)(strlen(varname)+1);
        if(! fwrite(&DataHead, sizeof(MATLAB_DATAHEAD), 1,
      pGMatlabDataFileConfig->fp)){
                return FALSE;
        }
        if(! fwrite(varname, sizeof(char), (strlen(varname)+1),
      pGMatlabDataFileConfig->fp)){
                return FALSE;
        }
        vcol = (double*)malloc(nlin*sizeof(double));
        for(nc=0;nc<ncol;++nc){
                for(nl=0;nl<nlin;++nl){
                        vcol[nl] = m[nl][nc];
                }
                if(! fwrite(vcol, sizeof(double), nlin, pGMatlabDataFileConfig
      ->fp)){
                        free(vcol);
                        return FALSE;
                }
        }
        free(vcol);
        pGMatlabDataFileConfig->FlagStillNotSaved = FALSE
      ;
        return(TRUE);
}
int gMATLABDataFile_SaveVector (PGMATLABDATAFILECONFIG pGMatlabDataFileConfig, const char * varname, double * v, long nlin)
Definition at line 64 of file gmatlabdatafile.c.
References FALSE, GMATLABDATAFILECONFIG::FlagStillNotSaved, GMATLABDATAFILECONFIG::fp, MATLAB_DATAHEAD::imagf, MATLAB_DATAHEAD::mrows, MATLAB_DATAHEAD::namlen, MATLAB_DATAHEAD::ncols, TRUE, and MATLAB_DATAHEAD::type.
Referenced by gDataLogger_Close(), and gDataLogger_MatfileUpdate().
{
        MATLAB_DATAHEAD DataHead;
        DataHead.type = (long)(0);
        DataHead.mrows = (long)(nlin);
        DataHead.ncols = (long)(1);
        DataHead.imagf = (long)(0);
        DataHead.namlen = (long)(strlen(varname)+1);
        if(! fwrite(&DataHead, sizeof(MATLAB_DATAHEAD), 1,
      pGMatlabDataFileConfig->fp)){
                return FALSE;
        }
        if(! fwrite(varname, sizeof(char), (strlen(varname)+1),
      pGMatlabDataFileConfig->fp)){
                return FALSE;
        }
        if(! fwrite(v, sizeof(double), nlin, pGMatlabDataFileConfig->fp)){
                return FALSE;
        }
        pGMatlabDataFileConfig->FlagStillNotSaved = FALSE
      ;
        return(TRUE);
}