gdatalogger/gqueue.h File Reference
Data Structures
struct GQUEUECONTROL
Macros
#define TRUE 1
#define FALSE 0
#define MAXSIZE_QUEUE_READ_GATES 5
#define QUEUE_READ_GATE_0 0
#define QUEUE_READ_GATE_1 1
#define QUEUE_READ_GATE_2 2
#define QUEUE_READ_GATE_3 3
#define QUEUE_READ_GATE_4 4
#define GQUEUE_RTAI_SUPPORT 0
Typedefs
typedef struct GQUEUECONTROL * PGQUEUECONTROL
Functions
int gQUEUE_Init (PGQUEUECONTROL pQueueControl, int Size, int NReaders)
int gQUEUE_GetReadIndex (PGQUEUECONTROL pQueueControl, int NReader, int *Index, int IndexHorizon)
int gQUEUE_GetWriteIndex (PGQUEUECONTROL pQueueControl, int *Index, int IndexHorizon)
int gQUEUE_RequestReadIndex (PGQUEUECONTROL pQueueControl, int NReader, int *Index)
int gQUEUE_RequestWriteIndex (PGQUEUECONTROL pQueueControl, int *Index)
int gQUEUE_RequestLastReadIndex (PGQUEUECONTROL pQueueControl, int NReader, int *Index)
int gQUEUE_UnwrapWriteIndex (PGQUEUECONTROL pQueueControl)
int gQUEUE_UnwrapReadIndex (PGQUEUECONTROL pQueueControl, int NReader)
int gQUEUE_GetNumberOfUnreadData (PGQUEUECONTROL pQueueControl, int NReader, int *Index)
Macro Definition Documentation
#define FALSE 0
Definition at line 20 of file gqueue.h.
#define GQUEUE_RTAI_SUPPORT 0
Definition at line 29 of file gqueue.h.
#define MAXSIZE_QUEUE_READ_GATES 5
Definition at line 22 of file gqueue.h.
Referenced by gQUEUE_Init().
#define QUEUE_READ_GATE_0 0
Definition at line 23 of file gqueue.h.
#define QUEUE_READ_GATE_1 1
Definition at line 24 of file gqueue.h.
#define QUEUE_READ_GATE_2 2
Definition at line 25 of file gqueue.h.
#define QUEUE_READ_GATE_3 3
Definition at line 26 of file gqueue.h.
#define QUEUE_READ_GATE_4 4
Definition at line 27 of file gqueue.h.
#define TRUE 1
Definition at line 19 of file gqueue.h.
Typedef Documentation
typedef struct GQUEUECONTROL * PGQUEUECONTROL
Function Documentation
int gQUEUE_GetNumberOfUnreadData (PGQUEUECONTROL pQueueControl, int NReader, int * Index)
Definition at line 314 of file gqueue.c.
References FALSE, GQUEUECONTROL::NReaders, GQUEUECONTROL::ReadIndex, GQUEUECONTROL::Size, TRUE, and GQUEUECONTROL::WriteIndex.
Referenced by gDataLogger_IPCUpdate(), and gDataLogger_MatfileUpdate().
{
        if(NReader>=pQueueControl->NReaders){
                return FALSE;
        }
        if(pQueueControl->WriteIndex >= pQueueControl->ReadIndex
      [NReader]){
                *Index = pQueueControl->WriteIndex-pQueueControl->
      ReadIndex[NReader];
        }
        else{
                *Index = pQueueControl->Size-(pQueueControl->ReadIndex
      [NReader]-pQueueControl->WriteIndex);
        }
        
        return TRUE;
}
int gQUEUE_GetReadIndex (PGQUEUECONTROL pQueueControl, int NReader, int * Index, int IndexHorizon)
Definition at line 166 of file gqueue.c.
References BEGIN_ATOMIC, END_ATOMIC, FALSE, GQUEUECONTROL::FlagStillNotWritten, gQUEUE_UnwrapReadIndex(), GQUEUECONTROL::NReaders, GQUEUECONTROL::ReadIndex, GQUEUECONTROL::Size, and TRUE.
{
        if(NReader>=pQueueControl->NReaders){
                return FALSE;
        }
        if(pQueueControl->FlagStillNotWritten == TRUE){
                return FALSE;
        }
    
BEGIN_ATOMIC();
        *Index = (pQueueControl->ReadIndex[NReader]-IndexHorizon);
        if(*Index<0){
                *Index += pQueueControl->Size;
        }
        gQUEUE_UnwrapReadIndex(pQueueControl, NReader);
END_ATOMIC();
    return TRUE;
}
int gQUEUE_GetWriteIndex (PGQUEUECONTROL pQueueControl, int * Index, int IndexHorizon)
Definition at line 203 of file gqueue.c.
References BEGIN_ATOMIC, END_ATOMIC, FALSE, GQUEUECONTROL::FlagStillNotWritten, gQUEUE_UnwrapWriteIndex(), GQUEUECONTROL::Size, TRUE, and GQUEUECONTROL::WriteIndex.
{
    if(pQueueControl->FlagStillNotWritten == TRUE){
        return FALSE;
    }
BEGIN_ATOMIC();
    
        *Index = (pQueueControl->WriteIndex-IndexHorizon);
        if(*Index<0){
                *Index += pQueueControl->Size;
        }
        gQUEUE_UnwrapWriteIndex(pQueueControl);
END_ATOMIC();
    return TRUE;
}
int gQUEUE_Init (PGQUEUECONTROL pQueueControl, int Size, int NReaders)
Definition at line 31 of file gqueue.c.
References FALSE, GQUEUECONTROL::FlagFull, GQUEUECONTROL::FlagStillNotRead, GQUEUECONTROL::FlagStillNotWritten, MAXSIZE_QUEUE_READ_GATES, GQUEUECONTROL::NReaders, GQUEUECONTROL::ReadIndex, GQUEUECONTROL::Size, TRUE, and GQUEUECONTROL::WriteIndex.
Referenced by gDataLogger_DeclareVariable().
{
        int n;
        if(NReaders > MAXSIZE_QUEUE_READ_GATES){
                return FALSE;
        }
        pQueueControl->Size = Size,
        pQueueControl->NReaders = NReaders;
        pQueueControl->FlagStillNotWritten = TRUE;
        for(n=0;n<NReaders;++n){
                pQueueControl->ReadIndex[n] = 0;
                pQueueControl->FlagStillNotRead[n] = TRUE;
                pQueueControl->FlagFull[n] = FALSE;
        }
        pQueueControl->WriteIndex = 0;
#if GQUEUE_RTAI_SUPPORT
        rt_spl_init(&pQueueControl->SPLAtomicAccess);
#endif
    return TRUE;
}
int gQUEUE_RequestLastReadIndex (PGQUEUECONTROL pQueueControl, int NReader, int * Index)
Definition at line 67 of file gqueue.c.
References BEGIN_ATOMIC, END_ATOMIC, FALSE, GQUEUECONTROL::FlagFull, GQUEUECONTROL::FlagStillNotRead, GQUEUECONTROL::FlagStillNotWritten, gQUEUE_UnwrapReadIndex(), GQUEUECONTROL::NReaders, GQUEUECONTROL::ReadIndex, TRUE, and GQUEUECONTROL::WriteIndex.
{
        if(NReader>=pQueueControl->NReaders){
                return FALSE;
        }
        
        if(pQueueControl->FlagStillNotWritten == TRUE){
                return FALSE;
        }
BEGIN_ATOMIC();
        
        if(pQueueControl->FlagStillNotRead[NReader] == TRUE
      ){
                pQueueControl->ReadIndex[NReader] = pQueueControl->
      WriteIndex;
                *Index = pQueueControl->ReadIndex[NReader];
                pQueueControl->FlagStillNotRead[NReader] =
      FALSE;
        }
        else{
                if(pQueueControl->ReadIndex[NReader] == pQueueControl
      ->WriteIndex){
                        pQueueControl->FlagFull[NReader] = FALSE;
                        *Index = -1;
                }
                else{
                        pQueueControl->ReadIndex[NReader] =
      pQueueControl->WriteIndex;
                        gQUEUE_UnwrapReadIndex(
      pQueueControl,NReader);
                        *Index = pQueueControl->ReadIndex[NReader];
                }
        }
END_ATOMIC();
        if(*Index==-1){
                return FALSE;
        }
    return TRUE;
}
int gQUEUE_RequestReadIndex (PGQUEUECONTROL pQueueControl, int NReader, int * Index)
Definition at line 117 of file gqueue.c.
References BEGIN_ATOMIC, END_ATOMIC, FALSE, GQUEUECONTROL::FlagFull, GQUEUECONTROL::FlagStillNotRead, GQUEUECONTROL::FlagStillNotWritten, gQUEUE_UnwrapReadIndex(), GQUEUECONTROL::NReaders, GQUEUECONTROL::ReadIndex, TRUE, and GQUEUECONTROL::WriteIndex.
Referenced by gDataLogger_IPCUpdate(), and gDataLogger_MatfileUpdate().
{
        if(NReader>=pQueueControl->NReaders){
                return FALSE;
        }
        if(pQueueControl->FlagStillNotWritten == TRUE){
                return FALSE;
        }
    
BEGIN_ATOMIC();
        if(pQueueControl->FlagStillNotRead[NReader] == TRUE
      ){
                *Index = pQueueControl->ReadIndex[NReader];
                pQueueControl->FlagStillNotRead[NReader] =
      FALSE;
        }
        else{
                if(pQueueControl->ReadIndex[NReader] == pQueueControl
      ->WriteIndex){
                        pQueueControl->FlagFull[NReader] = FALSE;
                        *Index = -1;
                }
                else{
                        ++pQueueControl->ReadIndex[NReader];
                        gQUEUE_UnwrapReadIndex(
      pQueueControl,NReader);
                        *Index = pQueueControl->ReadIndex[NReader];
                }
        }
END_ATOMIC();
        if(*Index==-1){
                return FALSE;
        }
    return TRUE;
}
int gQUEUE_RequestWriteIndex (PGQUEUECONTROL pQueueControl, int * Index)
Definition at line 233 of file gqueue.c.
References BEGIN_ATOMIC, END_ATOMIC, FALSE, GQUEUECONTROL::FlagFull, GQUEUECONTROL::FlagStillNotWritten, gQUEUE_UnwrapWriteIndex(), GQUEUECONTROL::NReaders, GQUEUECONTROL::ReadIndex, GQUEUECONTROL::Size, TRUE, and GQUEUECONTROL::WriteIndex.
Referenced by gDataLogger_InsertVariable().
{
        int n;
        int FlagNotFull = TRUE;
BEGIN_ATOMIC();
    
    if(pQueueControl->FlagStillNotWritten == TRUE){
        *Index = pQueueControl->WriteIndex;
        pQueueControl->FlagStillNotWritten = FALSE;
        }
    else{
                /* Increment write index in two positions to test if queue is
       full */
        pQueueControl->WriteIndex += 2;
        gQUEUE_UnwrapWriteIndex(pQueueControl);
        
                for(n=0;n<pQueueControl->NReaders;++n){
                        if(pQueueControl->ReadIndex[n] ==
      pQueueControl->WriteIndex){
                                pQueueControl->FlagFull[n] = TRUE;
                                FlagNotFull = FALSE;
                        }
                }
                /* Decrement write index of one position to return to the
       correct state */
        pQueueControl->WriteIndex += pQueueControl->Size-1;
        gQUEUE_UnwrapWriteIndex(pQueueControl);
                *Index = pQueueControl->WriteIndex;
    }
END_ATOMIC();
    return FlagNotFull;
}
int gQUEUE_UnwrapReadIndex (PGQUEUECONTROL pQueueControl, int NReader)
Definition at line 277 of file gqueue.c.
References FALSE, GQUEUECONTROL::NReaders, GQUEUECONTROL::ReadIndex, GQUEUECONTROL::Size, and TRUE.
Referenced by gQUEUE_GetReadIndex(), gQUEUE_RequestLastReadIndex(), and gQUEUE_RequestReadIndex().
{
        if(NReader>=pQueueControl->NReaders){
                return FALSE;
        }
        pQueueControl->ReadIndex[NReader] = (pQueueControl->ReadIndex
      [NReader]) % (pQueueControl->Size);
  
        return TRUE;
}
int gQUEUE_UnwrapWriteIndex (PGQUEUECONTROL pQueueControl)
Definition at line 297 of file gqueue.c.
References GQUEUECONTROL::Size, TRUE, and GQUEUECONTROL::WriteIndex.
Referenced by gQUEUE_GetWriteIndex(), and gQUEUE_RequestWriteIndex().
{
        pQueueControl->WriteIndex = (pQueueControl->WriteIndex
      ) % (pQueueControl->Size);
        
        return TRUE;
}