Functions to deal the User Inteface using ncurses
Functions
int ui_init (void)
Initialize UI.
int ui_close (void)
Close UI.
int ui_update (IMU_DATA_STRUCT *pimu_data, EFF_DATA_STRUCT *peff_data, MRA_DATA_STRUCT *pmra_data, ENC_DATA_STRUCT *enc_data, int total, int failure)
Update Screen with new data of sensors.
int ui_imu_data (IMU_DATA_STRUCT *pimu_data)
Print IMU data.
int ui_mra_data (MRA_DATA_STRUCT *pmra_data)
Print MRA data.
Detailed Description
Function Documentation
int ui_close (void)
Close UI.
Definition at line 41 of file ui.c.
References SUCCESS.
Referenced by main(), and threads_linux_init().
{
    #if UI_MODULE_ENABLED
        clear();
        printw("Cleaning up...\n");
        refresh();
        endwin();
    #endif
          return SUCCESS;
}
int ui_imu_data (IMU_DATA_STRUCT * pimu_data)
Print IMU data.
Definition at line 130 of file ui.c.
References IMU_DATA_STRUCT::acc, IMU_DATA_STRUCT::calibrated::acc, IMU_DATA_STRUCT::calib, IMU_DATA_STRUCT::gyr, IMU_DATA_STRUCT::calibrated::gyr, IMU_DATA_STRUCT::mag, IMU_DATA_STRUCT::calibrated::mag, SUCCESS, DATA_XYZ::x, DATA_XYZ_DOUBLE::x, DATA_XYZ::y, DATA_XYZ_DOUBLE::y, DATA_XYZ::z, and DATA_XYZ_DOUBLE::z.
Referenced by ui_update().
{
        mvprintw(2, 0, "Accelerometer X (raw): %d", pimu_data->acc.x);
        mvprintw(2, 40, "Accelerometer X (g): %lf", pimu_data->calib.acc
      .x);
        mvprintw(3, 0, "Accelerometer Y (raw): %d", pimu_data->acc.y);
        mvprintw(3, 40, "Accelerometer Y (g): %lf", pimu_data->calib.acc
      .y);
        mvprintw(4, 0, "Accelerometer Z (raw): %d", pimu_data->acc.z);
        mvprintw(4, 40, "Accelerometer Z (g): %lf", pimu_data->calib.acc
      .z);
        mvprintw(5, 0, "Gyrometer X (raw): %d", pimu_data->gyr.x);
        mvprintw(5, 40, "Gyrometer X (rad/sec): %lf", pimu_data->calib.
      gyr.x);
        mvprintw(6, 0, "Gyrometer Y (raw): %d", pimu_data->gyr.y);
        mvprintw(6, 40, "Gyrometer Y (rad/sec): %lf", pimu_data->calib.
      gyr.y);
        mvprintw(7, 0, "Gyrometer Z (raw): %d", pimu_data->gyr.z);
        mvprintw(7, 40, "Gyrometer Z (rad/sec): %lf", pimu_data->calib.
      gyr.z);
        mvprintw(8, 0, "Magnetometer X (raw): %d", pimu_data->mag.x);
        mvprintw(8, 40, "Magnetometer X (B): %lf", pimu_data->calib.
      mag.x);
        mvprintw(9, 0, "Magnetometer Y (raw): %d", pimu_data->mag.y);
        mvprintw(9, 40, "Magnetometer Y (B): %lf", pimu_data->calib.
      mag.y);
        mvprintw(10,0, "Magnetometer Z (raw): %d", pimu_data->mag.z);
        mvprintw(10,40, "Magnetometer Z (B): %lf", pimu_data->calib.
      mag.z);
        mvprintw(12,0,"Total Acceleromter: %lf",sqrt(pimu_data->calib.acc
      .x*pimu_data->calib.acc.x+pimu_data->calib.acc.y*pimu_data->
      calib.acc.y+pimu_data->calib.acc.z*pimu_data->calib.acc
      .z));
        mvprintw(13,0,"Total Gyrometer: %lf",sqrt(pimu_data->calib.gyr.
      x*pimu_data->calib.gyr.x+pimu_data->calib.gyr.y*pimu_data->
      calib.gyr.y+pimu_data->calib.gyr.z*pimu_data->calib.gyr
      .z));
        mvprintw(14,0,"Total Magnetometer: %lf",sqrt(pimu_data->calib.mag
      .x*pimu_data->calib.mag.x+pimu_data->calib.mag.y*pimu_data->
      calib.mag.y+pimu_data->calib.mag.z*pimu_data->calib.mag
      .z));
        //mvprintw(15, 0, "Encoder (raw): %lf", enc.data);
        return SUCCESS;
}
int ui_init (void)
Initialize UI.
Definition at line 26 of file ui.c.
References SUCCESS, and TRUE.
Referenced by main(), and threads_linux_init().
{
    #if UI_MODULE_ENABLED
        //NCURSES
        initscr();
        scrollok(stdscr,TRUE);
        //resizeterm(33,100);
        //wresize(scr,32,100);
        //erase();
        timeout(0); //No delay for getch();
    #endif
        return SUCCESS;
}
int ui_mra_data (MRA_DATA_STRUCT * pmra_data)
Print MRA data.
Definition at line 183 of file ui.c.
References SUCCESS, MRA_DATA_STRUCT::v_ctl, and MRA_DATA_STRUCT::v_ctl_read.
Referenced by ui_update().
{
        mvprintw(2,0,"V_ctl (bits): %d",pmra_data->v_ctl);
        mvprintw(3,0,"V_ctl_read (bits): %d",pmra_data->v_ctl_read);
        //mvprintw(2,40,"Fx (N): %lf",peff_data->??);
        return SUCCESS;
}
int ui_update (IMU_DATA_STRUCT * pimu_data, EFF_DATA_STRUCT * peff_data, MRA_DATA_STRUCT * pmra_data, ENC_DATA_STRUCT * enc_data, int total, int failure)
Update Screen with new data of sensors.
Definition at line 53 of file ui.c.
References exit_program(), FAILURE, SUCCESS, ui_eff_data(), ui_enc_data(), ui_imu_data(), ui_mra_data(), and ui_overview_data().
Referenced by periodic_task_2(), threads_linux_periodic_task_2(), and ui_task().
{
        unsigned char user_char = 0;
        static enum {UI_OVERVIEW = 0, UI_IMU, UI_EFF, UI_MRA , UI_ENC} ui_state
      ;
        erase();
        //wresize(scr,32,100);
        attron(A_STANDOUT);
        mvaddstr(0,15,"RLEG Data");
        attroff(A_STANDOUT);
        switch(ui_state)
        {
                case UI_IMU:
                        if(ui_imu_data(pimu_data) != SUCCESS)
       return FAILURE;
                        break;
                case UI_EFF:
                        if(ui_eff_data(peff_data) != SUCCESS)
       return FAILURE;
                        break;
                case UI_MRA:
                        if(ui_mra_data(pmra_data) != SUCCESS)
       return FAILURE;
                        break;
        case UI_ENC:
                        if(ui_enc_data(enc_data) != SUCCESS)
      return FAILURE;
                        break;
                case UI_OVERVIEW:
                default:
                        if(ui_overview_data(total, failure
      , pimu_data, peff_data, pmra_data, enc_data) != SUCCESS) return FAILURE
      ;
                        break;
        }
        refresh();
        user_char = getch(); //Getting a char typed by the user
        switch(user_char)
        {
                case 'Q':
                case 'q': //Quit
                        exit_program();
                        break;
                case 'i': //IMU view
                        ui_state = UI_IMU;
                        break;
                case 'f': //EFF view
                        ui_state = UI_EFF;
                        break;
            case 'e': // ENCODER view
                    ui_state = UI_ENC;
                    break;
                case 'o': //Overview
                        ui_state = UI_OVERVIEW;
                        break;
                case 'm': //MRA
                        ui_state = UI_MRA;
                
                        break;
                /* removed datalogger
                case 'd': //Datalogger start/stop
                  if(datalogger_status() == DATALOGGER_RUNNING)
                  {
                    datalogger_stop();
                  }
                  else
                  {
                    datalogger_start();
                  }
                  break;
                */
               default:
                 break;
        }
        return SUCCESS;
}