Functions for accelerometer ADXL345
Functions
int acc_write_reg (int i2c_dev, uint8_t reg, uint8_t data)
WRITE TO REGISTER.
uint8_t * acc_read_reg (int i2c_dev, uint8_t reg, uint8_t count)
READ COUNT 8-BIT REGISTER IN SEQUENCE
int acc_init (int i2c_dev, uint8_t full_res, uint16_t rate, uint8_t range)
INITIALIZE ACCELEROMETER.
int acc_read_all_data (int i2c_dev, short int *data)
READ ALL DATA AT ONCE (X, Y and Z)
short int acc_read_data (int i2c_dev, int axis)
READ DATA (X, Y or Z)
int acc_read_all_reg (int i2c_dev)
Read all accelerometer data and print in stdio.
Detailed Description
Function Documentation
int acc_init (int i2c_dev, uint8_t full_res, uint16_t rate, uint8_t range)
INITIALIZE ACCELEROMETER.
Parameters
i2c_dev Communication Port
full_res Set resolution to 10 bits if value equal 0 else set to Full resolution
rate Set data output rate (Hz), possible values: (3200,1600,800,400,200,100,50,25, 12: 12.5Hz, 6: 6.25Hz)
range Set range of read, possible values: (2: +- 2g 4: +- 4g 8: +- 8g anyother: 16g)
Returns
flag with SUCCESS or FAILURE
INITIALIZE ACCELEROMETER.
Implements the I2C communication between Gumstix Overo Fire and ADXL345
Author
Caio Gustavo Mesquita Ângelo
Definition at line 11 of file acc_functions.c.
References ACC_BW_RATE, ACC_DATA_FORMAT, ACC_POWER_CTL, ACC_POWER_CTL_MEAS_MODE, acc_write_reg(), FAILURE, and SUCCESS.
Referenced by devices_init().
{
  uint8_t data=0;
  switch(range){
    case 2:
      data=0x08;;
      break;
    case 4:
      data=0x09;
      break;
    case 8:
      data=0x0A;
      break;
    default:
      data=0x0B;
      break;
  }
  
  if(full_res==0)
    data=data&(0xF7);
  
  if((acc_write_reg(i2c_dev, ACC_DATA_FORMAT, data)
      )<0){
    perror("Data Format unsuccesful");
    return FAILURE;
  }
  
  data=ACC_POWER_CTL_MEAS_MODE;
  if((acc_write_reg(i2c_dev, ACC_POWER_CTL, data))<0)
      {
    perror("Power Control unsuccesful");
    return FAILURE;
  }
  
  switch(rate){
    case 100:
      data=0x0A;
      break;
    case 3200:
      data=0x0F;;
      break;
    case 1600:
      data=0x0E;
      break;
    case 800:
      data=0x0D;
      break;
    case 400:
      data=0x0C;
      break;
    case 200:
      data=0x0B;
      break;
    case 50:
      data=0x09;
      break;
    case 25:
      data=0x08;
      break;
    case 12:
      data=0x07;
      break;
    case 6:
      data=0x06;
      break;
    default:
      perror("Wrong rate value");
      return FAILURE;
  }
  if((acc_write_reg(i2c_dev, ACC_BW_RATE, data))<0){
    perror("Write in BW_RATE unsuccesful");
    return FAILURE;
  }
  
  return SUCCESS;
}
int acc_read_all_data (int i2c_dev, short int * data)
READ ALL DATA AT ONCE (X, Y and Z)
Parameters
   i2c_dev Communication Port
out data Data's vector
Returns
flag with SUCCESS or FAILURE
Definition at line 159 of file acc_functions.c.
References ACC_DATAX0, acc_read_reg(), FAILURE, and SUCCESS.
Referenced by read_all_data().
{
  int i;
  uint8_t *data8;
  union result
  {
    unsigned short int usgnd[3];
    short int sgnd[3];
  } result;
  //result=(union result*)malloc(3*sizeof(union result));
  if((data8=acc_read_reg(i2c_dev,ACC_DATAX0,6))==NULL)
  {
    //perror("Read accelerometer register failed");
    return FAILURE;
  }
  //result.usgnd=(unsigned int*)malloc(3*sizeof(unsigned int));
  for(i=0; i<3; i++)
  {
    result.usgnd[i]=0;
    result.usgnd[i]=result.usgnd[i]|((unsigned short int)data8[i*2])|(((
      unsigned short int)data8[i*2+1])<<8);
    data[i]=result.sgnd[i];
  }
  return SUCCESS;
}
int acc_read_all_reg (int i2c_dev)
Read all accelerometer data and print in stdio.
Parameters
i2c_dev Communication Port
Definition at line 196 of file acc_functions.c.
References ACC_DEVID, acc_read_reg(), ACC_THRESH_TAP, and conv_byte_hex_bin().
{
  uint8_t *hvalue0, *hvalue1, *hvalue;
  int i;
  
  hvalue0=acc_read_reg(i2c_dev,ACC_DEVID,1);
  printf("\nhey");
  printf("\nhey3");
  printf("\nhey2");
  printf("\nhey3");
  hvalue1=acc_read_reg(i2c_dev,ACC_THRESH_TAP, 29);
  printf("\nhey3");
  //hvalue--;
  hvalue=(uint8_t*)malloc(30*sizeof(uint8_t));
  hvalue[0]=hvalue0[0];
  for(i=0; i<29; i++)
    hvalue[i+1]=hvalue1[i];
  printf("\nhey4");
  printf("\nACC_DEVID = 0x%02X = %s", hvalue0[0],conv_byte_hex_bin
      (hvalue0));
  printf("\nACC_THRESH_TAP = 0x%02X = %s", hvalue1[0],conv_byte_hex_bin
      (hvalue+1));
  printf("\nACC_OFSX = 0x%02X = %s", hvalue[2],conv_byte_hex_bin
      (hvalue+2));
  printf("\nACC_OFSY = 0x%02X = %s", hvalue[3],conv_byte_hex_bin
      (hvalue+3));
  printf("\nACC_OFSZ = 0x%02X = %s", hvalue[4],conv_byte_hex_bin
      (hvalue+4));
  printf("\nACC_DUR = 0x%02X = %s", hvalue[5],conv_byte_hex_bin
      (hvalue+5));
  printf("\nACC_LATENT = 0x%02X = %s", hvalue[6],conv_byte_hex_bin
      (hvalue+6));
  printf("\nACC_WINDOW = 0x%02X = %s", hvalue[7],conv_byte_hex_bin
      (hvalue+7));
  printf("\nACC_THRESH_ACT = 0x%02X = %s", hvalue[8],conv_byte_hex_bin
      (hvalue+8));
  printf("\nACC_THRESH_INACT = 0x%02X = %s", hvalue[9],conv_byte_hex_bin
      (hvalue+9));
  printf("\nACC_TIME_INACT = 0x%02X = %s", hvalue[10],conv_byte_hex_bin
      (hvalue+10));
  printf("\nACC_ACT_INACT_CTL = 0x%02X = %s", hvalue[11],conv_byte_hex_bin
      (hvalue+11));
  printf("\nACC_THRESH_FF = 0x%02X = %s", hvalue[12],conv_byte_hex_bin
      (hvalue+12));
  printf("\nACC_TIME_FF = 0x%02X = %s", hvalue[13],conv_byte_hex_bin
      (hvalue+13));
  printf("\nACC_TAP_AXES = 0x%02X = %s", hvalue[14],conv_byte_hex_bin
      (hvalue+14));
  printf("\nACC_ACT_TAP_STATUS = 0x%02X = %s", hvalue[15],conv_byte_hex_bin
      (hvalue+15));
  printf("\nACC_BW_RATE = 0x%02X = %s", hvalue[16],conv_byte_hex_bin
      (hvalue+16));
  printf("\nACC_POWER_CTL = 0x%02X = %s", hvalue[17],conv_byte_hex_bin
      (hvalue+17));
  printf("\nACC_INT_ENABLE = 0x%02X = %s", hvalue[18],conv_byte_hex_bin
      (hvalue+18));
  printf("\nACC_INT_MAP = 0x%02X = %s", hvalue[19],conv_byte_hex_bin
      (hvalue+19));
  printf("\nACC_INT_SOURCE = 0x%02X = %s", hvalue[20],conv_byte_hex_bin
      (hvalue+20));
  printf("\nACC_DATA_FORMAT = 0x%02X = %s", hvalue1[20],conv_byte_hex_bin
      (hvalue1+21));
  printf("\nACC_DATAX0 = 0x%02X = %s", hvalue1[21],conv_byte_hex_bin
      (hvalue1+22));
  printf("\nACC_DATAX1 = 0x%02X = %s", hvalue1[22],conv_byte_hex_bin
      (hvalue1+23));
  printf("\nACC_DATAY0 = 0x%02X = %s", hvalue1[23],conv_byte_hex_bin
      (hvalue1+24));
  printf("\nACC_DATAY1 = 0x%02X = %s", hvalue1[24],conv_byte_hex_bin
      (hvalue1+25));
  printf("\nACC_DATAZ0 = 0x%02X = %s", hvalue1[25],conv_byte_hex_bin
      (hvalue1+26));
  printf("\nACC_DATAZ1 = 0x%02X = %s", hvalue1[26],conv_byte_hex_bin
      (hvalue1+27));
  printf("\nACC_FIFO_CTL = 0x%02X = %s", hvalue[28],conv_byte_hex_bin
      (hvalue+28));
  printf("\nACC_FIFO_STATUS = 0x%02X = %s", hvalue[29],conv_byte_hex_bin
      (hvalue+29));
  return 1;
}
short int acc_read_data (int i2c_dev, int axis)
READ DATA (X, Y or Z)
Parameters
   i2c_dev Communication Port
in axis Accelerate's axis to read ('X' or 'Y' or 'Z')
Returns
Definition at line 131 of file acc_functions.c.
References ACC_DATAX0, ACC_DATAY0, ACC_DATAZ0, and acc_read_reg().
{
  uint8_t *data;
  union result
  {
    unsigned short int usgnd;
    short int sgnd;
  }result;
  switch(axis){
    case 'X':
      data=acc_read_reg(i2c_dev,ACC_DATAX0,2);
      break;
    case 'Y':
      data=acc_read_reg(i2c_dev,ACC_DATAY0,2);
      break;
    case 'Z':
      data=acc_read_reg(i2c_dev,ACC_DATAZ0,2);
      break;
    default:
      //perror("Wrong argument for axis in acc_read_data");
      return -1;
  }
  result.usgnd=0;
  result.usgnd=result.usgnd|(((unsigned short int)data[0]))|(((unsigned short
      int)data[1])<<8);
  return result.sgnd;
}
uint8_t* acc_read_reg (int i2c_dev, uint8_t reg, uint8_t count)
READ COUNT 8-BIT REGISTER IN SEQUENCE
Parameters
   i2c_dev Communication Port
in reg Register
in count Number of register in sequence (1-29)
Returns
Data of register or NULL in case of any problem.
Definition at line 109 of file acc_functions.c.
Referenced by acc_read_all_data(), acc_read_all_reg(), and acc_read_data().
{
  uint8_t data[29];
  int i;
  //data=(uint8_t*)malloc((count+1)*sizeof(data));
  
  data[0] = reg;
  if ((write(i2c_dev, &data, 1)) != 1) {
        //perror("write before read");
        return NULL;
  }
  data[0] = 0;
  if ((read(i2c_dev, &data, count)) != count) {
        //perror("read");
        return NULL;
  }
  return data;
}
int acc_write_reg (int i2c_dev, uint8_t reg, uint8_t data)
WRITE TO REGISTER.
Parameters
   i2c_dev Communication Port
in reg Register
in data Data to write
Definition at line 87 of file acc_functions.c.
References ACC_ACT_TAP_STATUS, ACC_DATAX0, ACC_DATAX1, ACC_DATAY0, ACC_DATAY1, ACC_DATAZ0, ACC_DATAZ1, ACC_DEVID, ACC_FIFO_STATUS, ACC_INT_SOURCE, FAILURE, and SUCCESS.
Referenced by acc_init().
{
  uint8_t reg_data[2];
  reg_data[0] = reg;
  reg_data[1] = data;
  if(reg==ACC_DEVID || reg==ACC_ACT_TAP_STATUS ||
      reg==ACC_INT_SOURCE || reg==ACC_FIFO_STATUS ||
      reg==ACC_DATAX0 || reg==ACC_DATAX1 || reg==ACC_DATAY0
       || reg==ACC_DATAY1 || reg==ACC_DATAZ0 || reg==ACC_DATAZ1
      )
  {
      perror("Write unsucessful: Read-Only Register");
      return FAILURE;
  }
        
  if ((write(i2c_dev, &reg_data, 2)) != 2) {
          perror("Write unsuccessful");
          return FAILURE;
  }
  return SUCCESS;
}