Function of Encoder AMT203
Functions
int enc_read_pos (int spi_dev, unsigned short int *data)
READ POSITION.
int enc_zero_set (int spi_dev)
SET ZERO POINT.
int enc_wait_for_ack (int spi_dev, uint8_t ack, int max_errors)
send command and delay between reads
Function Documentation
int enc_read_pos (int spi_dev, unsigned short int * data)
READ POSITION.
Parameters
spi_dev Communication Port
$\leftarrow$ *data Data to read
Returns
flag with SUCCESS or FAILURE
Check this function, in case of error put delay before each byte data
Definition at line 37 of file encoder_functions.c.
References ARRAY_SIZE, enc_wait_for_ack(), ENCODER_NO_OP, ENCODER_RD_POS, FAILURE, INT_MAX, spi_trans_bytes(), and SUCCESS.
Referenced by read_all_data().
                                                      
    uint8_t send[] = ENCODER_RD_POS,ENCODER_NO_OP;
    uint8_t receive[ARRAY_SIZE(send)] = 0, ;
    uint8_t buffer[ARRAY_SIZE(send)] = 0, ;
    
    /* Send command */
    spi_trans_bytes(spi_dev,send,receive,1);
    if (enc_wait_for_ack(spi_dev, ENCODER_RD_POS, INT_MAX) != SUCCESS)
        return FAILURE;
    
    send[0]=ENCODER_NO_OP;
    if(spi_trans_bytes(spi_dev,send,receive,2) != SUCCESS)
        return FAILURE;
    
    buffer[0] = receive[0];
    if(spi_trans_bytes(spi_dev,send,receive,2) != SUCCESS)
        return FAILURE;
    
    buffer[1] = receive[0];
    *data = buffer[0]*256+buffer[1];
    //printf("= 0x %2x %2x %d",buffer[0],buffer[1],data);
   return SUCCESS;
int enc_wait_for_ack (int spi_dev, uint8_t ack, int max_errors)
send command and delay between reads
Parameters
spi_dev Communication Dev
$\leftarrow$ data Data to write
Returns
flag with SUCCESS or FAILURE
Definition at line 73 of file encoder_functions.c.
References ENCODER_NO_OP, ENCODER_WAIT_RESP, FAILURE, spi_trans_bytes(), and SUCCESS.
Referenced by enc_read_pos(), and enc_zero_set().
    int errors = 0;
    uint8_t send = ENCODER_NO_OP;
    uint8_t receive = 1;
        
  //nanosleep(10);
        //spi_trans_bytes(spi_dev,send,receive,1);
    while (receive != ack)
        spi_trans_bytes(spi_dev,&send,&receive,1);
        //printf("= 0x%x ",receive);
        if (receive != ENCODER_WAIT_RESP)
            errors++;
            if (errors > max_errors) return FAILURE;
        
    
    return SUCCESS;
int enc_zero_set (int spi_dev)
SET ZERO POINT.
Parameters
spi_dev Communication Dev
$\leftarrow$ data Data to write
Returns
flag with SUCCESS or FAILURE
Definition at line 19 of file encoder_functions.c.
References enc_wait_for_ack(), ENCODER_EEPROM_WR, ENCODER_SET_ZERO_PT, FAILURE, INT_MAX, spi_trans_bytes(), and SUCCESS.
                             
    uint8_t send = ENCODER_SET_ZERO_PT;
    uint8_t receive = 0;
    
    /* Send command */
    spi_trans_bytes(spi_dev,&send,&receive,1);
    if (enc_wait_for_ack(spi_dev, ENCODER_EEPROM_WR, INT_MAX) != SUCCESS)
        return FAILURE;
    
    /* Note:
     * From datasheet, the encoder must be power-cycled after this command
     * for the new zero position to be used in the position calculation. */
    return SUCCESS;