Scheduler for tasks
Implentation of Scheduler for tasks:
Functions
void timer_new_task (TASK_S *task, void(*runFunction)(int))
Create a task.
void timer_start_task (TASK_S *task, int period_us)
Start some task.
void timer_stop_task (TASK_S *task)
Stop some task.
Detailed Description
Implentation of Scheduler for tasks:
Author
Rafael Lima
Todo
Todo test it
Function Documentation
void timer_new_task (TASK_S * task, void(*)(int) runFunction)
Create a task.
Parameters
*task
*voidFunction Pointer to the function called to execute
Definition at line 16 of file taskScheduler.c.
Referenced by main().
                                                          {
  (*task).t_global = 0.0;
  (*task).T_exec_global = 0.0;
  (*task).T_mean_global = 0.0;
  (*task).T_max_global = 0.0;
  (*task).period_us = 0.0;
  (*task).isFirstExecution = 1;
  (*task).run = runFunction;
}
void timer_start_task (TASK_S * task, int period_us)
Start some task.
Parameters
*task Struct whith task data
period_us Period Value to repeat the task
Todo
Todo verify how use two tasks
Definition at line 27 of file taskScheduler.c.
References TASK_S::isFirstExecution, TASK_S::period_us, TASK_S::run, and TASK_S::timer.
Referenced by main().
                                                 {
  struct itimerspec itimer;
  struct sigevent evp;
  int erno = 0;
  
  task->isFirstExecution = 1;
  task->period_us = period_us;
  evp.sigev_value.sival_ptr = &(task->timer);
  evp.sigev_notify = SIGEV_SIGNAL;
  evp.sigev_signo = SIGUSR1;
  if(timer_create(CLOCK_REALTIME, &evp, &(task->timer))<0)
  {
    fprintf(stderr, "[%d]: %s\n", __LINE__, strerror(erno));
    exit(erno);
  }
  // Signal handler configuration
  struct sigaction satimer;
  satimer.sa_handler = task->run;
  sigemptyset(&satimer.sa_mask);
  satimer.sa_flags = SA_RESTART;
  if (sigaction(SIGUSR1, &satimer, NULL) < 0)
  {
    printf("ERROR: sigaction.\n");
    fprintf(stderr, "[%d]: %s\n", __LINE__, strerror(erno));
    exit(erno);
  }
  itimer.it_interval.tv_sec = 0;
  itimer.it_interval.tv_nsec= task->period_us*1000;
  itimer.it_value = itimer.it_interval;
  if(timer_settime(task->timer,0,&itimer,NULL) < 0)
  {
    fprintf(stderr,"[%d]: %s\n", __LINE__, strerror(erno));
    exit(erno);
  }
}
void timer_stop_task (TASK_S * task)
Stop some task.
Todo
Todo verify use of variable 'erno'
Definition at line 121 of file taskScheduler.c.
Referenced by main().
                                  {
  int erno = 0;
  if(timer_delete((*task).timer)<0){
    fprintf(stderr,"[%d]:%s\n",__LINE__,strerror(erno));
    exit(erno);
  }
}