André backup conflitos/imu_functions (Cópia em conflito de André Carvalho 2013-04-26).h File Reference
#include <stdio.h>
*
#include <stdint.h>
*
#include <stdlib.h>
*
#include <string.h>
*
#include <errno.h>
*
#include <unistd.h>
*
#include <sys/types.h>
*
#include <sys/stat.h>
*
#include <sys/ioctl.h>
*
#include <fcntl.h>
*
#include <linux/i2c-dev.h>
*
#include `imu_regs.h`
*
Macros
#define ASCII_0 0x30
#define SUCCESS 1
#define FAILURE -1
#define ADD_ADXL345 0x53
#define ADD_ITG3200 0x68
#define ADD_HMC5883 0x1E
Functions
int acc_write_reg (int i2c_dev, uint8_t reg, uint8_t data)
uint8_t * acc_read_reg (int i2c_dev, uint8_t reg, uint8_t count)
int acc_init (int i2c_dev, uint8_t full_res, uint16_t rate, uint8_t range)
Rev 0 - 11/11/2012 RLEG project - 2012.
uint8_t acc_read_all_data (int i2c_dev, short int *data)
short int acc_read_data (int i2c_dev, int axis)
char * conv_byte_hex_bin (uint8_t *hvalue)
int acc_read_all_reg (int i2c_dev)
int gyr_write_reg (int i2c_dev, uint8_t reg, uint8_t data)
uint8_t * gyr_read_reg (int i2c_dev, uint8_t reg, uint8_t count)
int gyr_init (int i2c_dev, float rate, short int lpf_bw, char clk_source, char *act)
uint8_t gyr_read_all_data (int i2c_dev, short int *data)
short int gyr_read_data (int i2c_dev, int type)
int mag_write_reg (int i2c_dev, uint8_t reg, uint8_t data)
Rev 0 - 11/11/2012 RLEG project - 2012.
uint8_t * mag_read_reg (int i2c_dev, uint8_t reg, uint8_t count)
int mag_init (int i2c_dev, uint8_t rate, uint8_t range, uint8_t samples_avg, uint8_t meas_mode, uint8_t op_mode)
uint8_t mag_read_all_data (int i2c_dev, short int *data)
short int mag_read_data (int i2c_dev, int axis)
Macro Definition Documentation
#define ADD_ADXL345 0x53
Definition at line 30 of file imu_functions (Cópia em conflito de André Carvalho 2013-04-26).h.
Referenced by devices_init(), main(), and read_all_data().
#define ADD_HMC5883 0x1E
Definition at line 32 of file imu_functions (Cópia em conflito de André Carvalho 2013-04-26).h.
Referenced by devices_init(), main(), and read_all_data().
#define ADD_ITG3200 0x68
Definition at line 31 of file imu_functions (Cópia em conflito de André Carvalho 2013-04-26).h.
Referenced by devices_init(), main(), and read_all_data().
#define ASCII_0 0x30
Definition at line 25 of file imu_functions (Cópia em conflito de André Carvalho 2013-04-26).h.
Referenced by conv_byte_hex_bin().
#define FAILURE -1
Definition at line 28 of file imu_functions (Cópia em conflito de André Carvalho 2013-04-26).h.
#define SUCCESS 1
Definition at line 27 of file imu_functions (Cópia em conflito de André Carvalho 2013-04-26).h.
Function Documentation
int acc_init (int i2c_dev, uint8_t full_res, uint16_t rate, uint8_t range)
Rev 0 - 11/11/2012 RLEG project - 2012.
Implements the I2C communication between Gumstix Overo Fire and ADXL345
Author
Caio Gustavo Mesquita Ângelo
Definition at line 10 of file acc_functions (Cópia em conflito de André Carvalho 2013-04-26).c.
{
  uint8_t data=0;
  switch(range){
    case 2:
      data=0x08;;
      break;
    case 4:
      data=0x09;
      break;
    case 8:
      data=0x0A;
      break;
    default:
      data=0x0B;
      break;
  }
  
  if(full_res==0)
    data=data&(0xF7);
  
  if((acc_write_reg(i2c_dev, ACC_DATA_FORMAT
      , data))<0){
    perror("Data Format unsuccesful");
    return -1;
  }
  
  data=ACC_POWER_CTL_MEAS_MODE;
  if((acc_write_reg(i2c_dev, ACC_POWER_CTL,
      data))<0){
    perror("Power Control unsuccesful");
    return -1;
  }
  
  switch(rate){
    case 100:
      data=0x0A;
      break;
    case 3200:
      data=0x0F;;
      break;
    case 1600:
      data=0x0E;
      break;
    case 800:
      data=0x0D;
      break;
    case 400:
      data=0x0C;
      break;
    case 200:
      data=0x0B;
      break;
    case 50:
      data=0x09;
      break;
    case 25:
      data=0x08;
      break;
    case 12:
      data=0x07;
      break;
    case 6:
      data=0x06;
      break;
    default:
      perror("Wrong rate value");
      return -1;
  }
  if((acc_write_reg(i2c_dev, ACC_BW_RATE, data))
      <0){
    perror("Write in BW_RATE unsuccesful");
    return -1;
  }
  
  return 1;
}
uint8_t acc_read_all_data (int i2c_dev, short int * data)
Definition at line 158 of file acc_functions (Cópia em conflito de André Carvalho 2013-04-26).c.
{
  int i;
  uint8_t *data8;
  union result
  {
    unsigned short int usgnd[3];
    short int sgnd[3];
  } result;
  //result=(union result*)malloc(3*sizeof(union result));
  if((data8=acc_read_reg(i2c_dev,ACC_DATAX0,6))==
      NULL)
  {
    perror("Read accelerometer register failed");
    return FAILURE;
  }
  //result.usgnd=(unsigned int*)malloc(3*sizeof(unsigned int));
  for(i=0; i<3; i++)
  {
    result.usgnd[i]=0;
    result.usgnd[i]=result.usgnd[i]|((unsigned short int)data8[i*2])|(((
      unsigned short int)data8[i*2+1])<<8);
    data[i]=result.sgnd[i];
  }
  return SUCCESS;
}
int acc_read_all_reg (int i2c_dev)
Definition at line 195 of file acc_functions (Cópia em conflito de André Carvalho 2013-04-26).c.
{
  uint8_t *hvalue0, *hvalue1, *hvalue;
  int i;
  
  hvalue0=acc_read_reg(i2c_dev,ACC_DEVID,1);
  printf("\nhey");
  printf("\nhey3");
  printf("\nhey2");
  printf("\nhey3");
  hvalue1=acc_read_reg(i2c_dev,ACC_THRESH_TAP,
       29);
  printf("\nhey3");
  //hvalue--;
  hvalue=(uint8_t*)malloc(30*sizeof(uint8_t));
  hvalue[0]=hvalue0[0];
  for(i=0; i<29; i++)
    hvalue[i+1]=hvalue1[i];
  printf("\nhey4");
  printf("\nACC_DEVID = 0x%02X = %s", hvalue0[0],conv_byte_hex_bin
      (hvalue0));
  printf("\nACC_THRESH_TAP = 0x%02X = %s", hvalue1[0],conv_byte_hex_bin
      (hvalue+1));
  printf("\nACC_OFSX = 0x%02X = %s", hvalue[2],conv_byte_hex_bin
      (hvalue+2));
  printf("\nACC_OFSY = 0x%02X = %s", hvalue[3],conv_byte_hex_bin
      (hvalue+3));
  printf("\nACC_OFSZ = 0x%02X = %s", hvalue[4],conv_byte_hex_bin
      (hvalue+4));
  printf("\nACC_DUR = 0x%02X = %s", hvalue[5],conv_byte_hex_bin
      (hvalue+5));
  printf("\nACC_LATENT = 0x%02X = %s", hvalue[6],conv_byte_hex_bin
      (hvalue+6));
  printf("\nACC_WINDOW = 0x%02X = %s", hvalue[7],conv_byte_hex_bin
      (hvalue+7));
  printf("\nACC_THRESH_ACT = 0x%02X = %s", hvalue[8],conv_byte_hex_bin
      (hvalue+8));
  printf("\nACC_THRESH_INACT = 0x%02X = %s", hvalue[9],conv_byte_hex_bin
      (hvalue+9));
  printf("\nACC_TIME_INACT = 0x%02X = %s", hvalue[10],conv_byte_hex_bin
      (hvalue+10));
  printf("\nACC_ACT_INACT_CTL = 0x%02X = %s", hvalue[11],conv_byte_hex_bin
      (hvalue+11));
  printf("\nACC_THRESH_FF = 0x%02X = %s", hvalue[12],conv_byte_hex_bin
      (hvalue+12));
  printf("\nACC_TIME_FF = 0x%02X = %s", hvalue[13],conv_byte_hex_bin
      (hvalue+13));
  printf("\nACC_TAP_AXES = 0x%02X = %s", hvalue[14],conv_byte_hex_bin
      (hvalue+14));
  printf("\nACC_ACT_TAP_STATUS = 0x%02X = %s", hvalue[15],conv_byte_hex_bin
      (hvalue+15));
  printf("\nACC_BW_RATE = 0x%02X = %s", hvalue[16],conv_byte_hex_bin
      (hvalue+16));
  printf("\nACC_POWER_CTL = 0x%02X = %s", hvalue[17],conv_byte_hex_bin
      (hvalue+17));
  printf("\nACC_INT_ENABLE = 0x%02X = %s", hvalue[18],conv_byte_hex_bin
      (hvalue+18));
  printf("\nACC_INT_MAP = 0x%02X = %s", hvalue[19],conv_byte_hex_bin
      (hvalue+19));
  printf("\nACC_INT_SOURCE = 0x%02X = %s", hvalue[20],conv_byte_hex_bin
      (hvalue+20));
  printf("\nACC_DATA_FORMAT = 0x%02X = %s", hvalue1[20],conv_byte_hex_bin
      (hvalue1+21));
  printf("\nACC_DATAX0 = 0x%02X = %s", hvalue1[21],conv_byte_hex_bin
      (hvalue1+22));
  printf("\nACC_DATAX1 = 0x%02X = %s", hvalue1[22],conv_byte_hex_bin
      (hvalue1+23));
  printf("\nACC_DATAY0 = 0x%02X = %s", hvalue1[23],conv_byte_hex_bin
      (hvalue1+24));
  printf("\nACC_DATAY1 = 0x%02X = %s", hvalue1[24],conv_byte_hex_bin
      (hvalue1+25));
  printf("\nACC_DATAZ0 = 0x%02X = %s", hvalue1[25],conv_byte_hex_bin
      (hvalue1+26));
  printf("\nACC_DATAZ1 = 0x%02X = %s", hvalue1[26],conv_byte_hex_bin
      (hvalue1+27));
  printf("\nACC_FIFO_CTL = 0x%02X = %s", hvalue[28],conv_byte_hex_bin
      (hvalue+28));
  printf("\nACC_FIFO_STATUS = 0x%02X = %s", hvalue[29],conv_byte_hex_bin
      (hvalue+29));
  return 1;
}
short int acc_read_data (int i2c_dev, int axis)
Definition at line 130 of file acc_functions (Cópia em conflito de André Carvalho 2013-04-26).c.
{
  uint8_t *data;
  union result
  {
    unsigned short int usgnd;
    short int sgnd;
  }result;
  switch(axis){
    case 'X':
      data=acc_read_reg(i2c_dev,ACC_DATAX0,2);
      break;
    case 'Y':
      data=acc_read_reg(i2c_dev,ACC_DATAY0,2);
      break;
    case 'Z':
      data=acc_read_reg(i2c_dev,ACC_DATAZ0,2);
      break;
    default:
      perror("Wrong argument for axis in acc_read_data");
      return -1;
  }
  result.usgnd=0;
  result.usgnd=result.usgnd|(((unsigned short int)data[0]))|(((unsigned short
      int)data[1])<<8);
  return result.sgnd;
}
uint8_t* acc_read_reg (int i2c_dev, uint8_t reg, uint8_t count)
Definition at line 108 of file acc_functions (Cópia em conflito de André Carvalho 2013-04-26).c.
{
  uint8_t data[29];
  int i;
  //data=(uint8_t*)malloc((count+1)*sizeof(data));
  
  data[0] = reg;
  if ((write(i2c_dev, &data, 1)) != 1) {
        perror("write before read");
        return NULL;
  }
  data[0] = 0;
  if ((read(i2c_dev, &data, count)) != count) {
        perror("read");
        return NULL;
  }
  return data;
}
int acc_write_reg (int i2c_dev, uint8_t reg, uint8_t data)
Definition at line 86 of file acc_functions (Cópia em conflito de André Carvalho 2013-04-26).c.
{
  uint8_t reg_data[2];
  reg_data[0] = reg;
  reg_data[1] = data;
  if(reg==ACC_DEVID || reg==ACC_ACT_TAP_STATUS ||
      reg==ACC_INT_SOURCE || reg==ACC_FIFO_STATUS ||
      reg==ACC_DATAX0 || reg==ACC_DATAX1 || reg==ACC_DATAY0
       || reg==ACC_DATAY1 || reg==ACC_DATAZ0 || reg==ACC_DATAZ1
      )
  {
      perror("Write unsucessful: Read-Only Register");
      return -1;
  }
        
  if ((write(i2c_dev, &reg_data, 2)) != 2) {
          perror("Write unsuccessful");
          return -1;
  }
  return 1;
}
char* conv_byte_hex_bin (uint8_t * hvalue)
Definition at line 183 of file acc_functions (Cópia em conflito de André Carvalho 2013-04-26).c.
{
  char bits[9];
  int i;
  for(i=0; i<8; i++)
  {
    bits[i]=((*hvalue)<<i)>>7+ASCII_0;
  }
  bits[8]='\0';
  return bits;
}
int gyr_init (int i2c_dev, float rate, short int lpf_bw, char clk_source, char * act)
Definition at line 53 of file gyr_functions (Cópia em conflito de André Carvalho 2013-04-26).c.
{
  uint8_t data=0;
  float Fint=1000;
  switch(lpf_bw){
    case 256:
      Fint=8000;
      data=0x18;
      break;
    case 188:
      data=0x19;
      break;
    case 98:
      data=0x1A;
      break;
    case 42:
      data=0x1B;
      break;
    case 20:
      data=0x1C;
      break;
    case 10:
      data=0x1D;
      break;
    case 5:
      data=0x1E;
      break;
    default:
      perror("Wrong low pass filter bandwidth value");
      break;
  }
  
  if(gyr_write_reg(i2c_dev, GYR_DLPF_FS, data)<0
      ){
    perror("Write in Configuration register A unsuccesful");
    return -1;
  }
  if((rate>Fint)||(rate<0))
  {
    perror("Wrong choice for rate");
    return -1;
  }
  data=(uint8_t)(Fint/rate - 1);
  
  if(gyr_write_reg(i2c_dev, GYR_SMPLRT_DIV,
      data)<0){
    perror("Write in configuration register B unsuccesful");
    return -1;
  }
      
  switch(clk_source){
    case 'I':
      data=0x00;
      break;
    case 'X':
      data=0x01;
      break;
    case 'Y':
      data=0x02;
      break;
    case 'Z':
      data=0x03;
      break;
    default:
      perror("Wrong clk_source value");
      break;
  }
      
  if(strcmp(act,"XYZ")==0);
  else if(strcmp(act,"YZ")==0)
      data=data|0x20;
  else if(strcmp(act,"")==0)
      data=data|0x40;
  else if(strcmp(act,"Y")==0)
      data=data|0x28;
  else if(strcmp(act,"Z")==0)
      data=data|0x30;
  else if(strcmp(act,"X")==0)
      data=data|0x18;
  else if(strcmp(act,"XY")==0)
      data=data|0x08;
  else if(strcmp(act,"XZ")==0)
      data=data|0x10;
  else{
    perror("Wrong act value in gyrometer initialization");
    return -1;
  }
   
  if(gyr_write_reg(i2c_dev, GYR_PWR_MGM, data)<0
      ){
    perror("Write in mode register unsuccesful");
    return -1;
  }
  
  return 1;
}
uint8_t gyr_read_all_data (int i2c_dev, short int * data)
Definition at line 149 of file gyr_functions (Cópia em conflito de André Carvalho 2013-04-26).c.
{
  uint8_t i;
  uint8_t *data8;
  union result
  {
    unsigned short int usgnd[4];
    int short sgnd[4];
  } result;
  if((data8=gyr_read_reg(i2c_dev,GYR_TEMP_OUT_H
      ,8))==NULL)
  {
    perror("Read accelerometer register failed");
    return FAILURE;
  }
  // Result receives gyro data:
  for(i=1; i<4; i++)
  {
    result.usgnd[i-1]=0;
    result.usgnd[i-1]=result.usgnd[i-1]|((unsigned short int)data8[i*2+1])|(((
      unsigned int)data8[i*2])<<8);
    data[i-1]=result.sgnd[i-1];
  }
  // Result receives temperature data:
  result.usgnd[3]=0;
  result.usgnd[3]=result.usgnd[3]|((unsigned short int)data8[1])|(((unsigned
      int)data8[0])<<8);
  data[3]=result.sgnd[3];
  return SUCCESS;
}
short int gyr_read_data (int i2c_dev, int type)
Definition at line 177 of file gyr_functions (Cópia em conflito de André Carvalho 2013-04-26).c.
{
  uint8_t *data;
  union result
  {
    unsigned int usgnd;
    int sgnd;
  }result;
  switch(type){
    case 'X':
      data=gyr_read_reg(i2c_dev,GYR_GYRO_XOUT_H
      ,2);
      break;
    case 'Y':
      data=gyr_read_reg(i2c_dev,GYR_GYRO_YOUT_H
      ,2);
      break;
    case 'Z':
      data=gyr_read_reg(i2c_dev,GYR_GYRO_ZOUT_H
      ,2);
      break;
    case 'T':
      data=gyr_read_reg(i2c_dev,GYR_TEMP_OUT_H
      ,2);
    default:
      perror("Wrong argument for type in gyr_read_data");
      return -1;
  }
  result.usgnd=0;
  result.usgnd=result.usgnd|(((unsigned short int)data[1]))|(((unsigned short
      int)data[0])<<8);
  return result.sgnd;
}
uint8_t* gyr_read_reg (int i2c_dev, uint8_t reg, uint8_t count)
Definition at line 31 of file gyr_functions (Cópia em conflito de André Carvalho 2013-04-26).c.
{
  uint8_t data[9];
  int i;
  //data=(uint8_t*)malloc((count+1)*sizeof(data));
  
  data[0] = reg;
  if (write(i2c_dev, &data, 1) != 1) {
        perror("write before read");
        return NULL;
  }
  data[0] = 0;
  if (read(i2c_dev, &data, count) != count) {
        perror("read");
        return NULL;
  }
  return data;
}
int gyr_write_reg (int i2c_dev, uint8_t reg, uint8_t data)
Author
Caio Gustavo Mesquita Ângelo Rev 0 - 12/11/2012 RLEG project - 2012
Implements the I2C communication between Gumstix Overo Fire and ITG3200
Definition at line 10 of file gyr_functions (Cópia em conflito de André Carvalho 2013-04-26).c.
{
  uint8_t reg_data[2];
  reg_data[0] = reg;
  reg_data[1] = data;
  if(!((reg==GYR_WHO_AM_I)||((GYR_SMPLRT_DIV<=reg)
      &&(reg<=GYR_INT_CFG))||(reg==GYR_PWR_MGM)))
  {
      perror("Write unsucessful: Not a valid writable register");
      return -1;
  }
        
  if (write(i2c_dev, &reg_data, 2) != 2) {
          perror("Write unsuccessful");
          return -1;
  }
  return 1;
}
int mag_init (int i2c_dev, uint8_t rate, uint8_t range, uint8_t samples_avg, uint8_t meas_mode, uint8_t op_mode)
Definition at line 53 of file mag_functions (Cópia em conflito de André Carvalho 2013-04-26).c.
Referenced by devices_init(), and main().
{
  uint8_t data=0;
  switch(rate){
    case 15:
      data=0x10;
      break;
    case 0:
      data=0x00;
      break;
    case 1:
      data=0x04;
      break;
    case 3:
      data=0x08;
      break;
    case 7:
      data=0x0C;
      break;
    case 30:
      data=0x14;
      break;
    case 75:
      data=0x18;
      break;
    default:
      perror("Wrong rate value");
      break;
  }
  
  switch(samples_avg){
    case 8:
      data=data|0x60;
      break;
    case 1:
      break;
    case 2:
      data=data|0x20;
      break;
    case 4:
      data=data|0x40;
      break;
    default:
      perror("Wrong samples_avg value");
      break;
  }
  
  data+=meas_mode;
  
  if(mag_write_reg(i2c_dev, MAG_CONFIG_A, data)
      <0){
    perror("Write in Configuration register A unsuccesful");
    return -1;
  }
  
  if(mag_write_reg(i2c_dev, MAG_CONFIG_B, range
      <<5)<0){
    perror("Write in configuration register B unsuccesful");
    return -1;
  }
  
  if(mag_write_reg(i2c_dev, MAG_MODE, op_mode)<0){
    perror("Write in mode register unsuccesful");
    return -1;
  }
  
  return 1;
}
uint8_t mag_read_all_data (int i2c_dev, short int * data)
Definition at line 121 of file mag_functions (Cópia em conflito de André Carvalho 2013-04-26).c.
Referenced by main(), and read_all_data().
{
  uint8_t i, j;
  uint8_t *data8;
  union result
  {
    unsigned short int usgnd[3];
    short int sgnd[3];
  } result;
  //result=(union result*)malloc(3*sizeof(union result));
  if((data8=mag_read_reg(i2c_dev,MAG_DATAX1,6))==
      NULL)
  {
    perror("Read accelerometer register failed");
    return FAILURE;
  }
  //result.usgnd=(unsigned int*)malloc(3*sizeof(unsigned int));
  j=0;
  for(i=0; i<3; i++)
  {
    result.usgnd[j]=0;
    result.usgnd[j]=result.usgnd[j]|((unsigned short int)data8[i*2+1])|(((
      unsigned int)data8[i*2])<<8);
    data[j]=result.sgnd[j];
    j=2-i; // trick used to change the sorting of the data from XZY to XYZ
  }
  return SUCCESS;
}
short int mag_read_data (int i2c_dev, int axis)
Definition at line 148 of file mag_functions (Cópia em conflito de André Carvalho 2013-04-26).c.
{
  uint8_t *data;
  union result
  {
    unsigned int usgnd;
    int sgnd;
  }result;
  switch(axis){
    case 'X':
      data=mag_read_reg(i2c_dev,MAG_DATAX1,2);
      break;
    case 'Y':
      data=mag_read_reg(i2c_dev,MAG_DATAY1,2);
      break;
    case 'Z':
      data=mag_read_reg(i2c_dev,MAG_DATAZ1,2);
      break;
    default:
      perror("Wrong argument for axis in mag_read_data");
      return -1;
  }
  result.usgnd=0;
  result.usgnd=result.usgnd|(((unsigned short int)data[1]))|(((unsigned short
      int)data[0])<<8);
  return result.sgnd;
}
uint8_t* mag_read_reg (int i2c_dev, uint8_t reg, uint8_t count)
Definition at line 31 of file mag_functions (Cópia em conflito de André Carvalho 2013-04-26).c.
Referenced by mag_read_all_data(), and mag_read_data().
{
  uint8_t data[13];
  int i;
  //data=(uint8_t*)malloc((count+1)*sizeof(data));
  
  data[0] = reg;
  if (write(i2c_dev, &data, 1) != 1) {
        perror("write before read");
        return NULL;
  }
  data[0] = 0;
  if (read(i2c_dev, &data, count) != count) {
        perror("read");
        return NULL;
  }
  return data;
}
int mag_write_reg (int i2c_dev, uint8_t reg, uint8_t data)
Rev 0 - 11/11/2012 RLEG project - 2012.
Implements the I2C communication between Gumstix Overo Fire and HMC5883
Author
Caio Gustavo Mesquita Ângelo
Definition at line 10 of file mag_functions (Cópia em conflito de André Carvalho 2013-04-26).c.
Referenced by mag_init().
{
  uint8_t reg_data[2];
  reg_data[0] = reg;
  reg_data[1] = data;
  if(MAG_MODE<reg)
  {
      perror("Write unsucessful: Not a valid writable register");
      return -1;
  }
        
  if (write(i2c_dev, &reg_data, 2) != 2) {
          perror("Write unsuccessful");
          return -1;
  }
  return 1;
}