main.c File Reference
#include <stdio.h>
*
#include <math.h>
*
#include `communication/communication.h`
*
#include `main.h`
*
#include `taskScheduler.h`
*
#include `ui.h`
*
Macros
#define TASK_UI_PERIOD 100000
Functions
int main (void)
static void ui_task (int signo)
static void control_task (int signo)
int get_time (double *time_control_task_s, double *Ts_control_task_s, double *mean_time_control_task_s, double *t0_control_task_s)
void exit_program (void)
Internal function to end program.
Variables
TASK_S task1
Main rotine for control:
TASK_S task2
IMU_PARAM_STRUCT imu_param
SPI_PARAM_STRUCT spi_param
EFF_DATA_STRUCT eff_data
IMU_DATA_STRUCT imu_data
ENC_DATA_STRUCT enc_data
MRA_DATA_STRUCT mra_data
int total = 0
int failure = 0
int acquire = 0
int quittask = 0
int t0 = 0
Macro Definition Documentation
#define TASK_UI_PERIOD 100000
Definition at line 19 of file main.c.
Referenced by main().
Function Documentation
static void control_task (int signo) [static]
Definition at line 109 of file main.c.
References actuate(), failure, IMU_PARAM_STRUCT::i2c_dev, read_all_data(), SPI_PARAM_STRUCT::spi_dev, SUCCESS, TASK_S::t_global, total, and MRA_DATA_STRUCT::v_ctl.
Referenced by main().
                                   {
  total++;
/*Input*/
  if(read_all_data(imu_param.i2c_dev, spi_param
      .spi_dev, &imu_data,&eff_data, &mra_data, &
      enc_data) != SUCCESS) failure++;
  
/* Control */
  mra_data.v_ctl=1275 + (uint8_t)(800*cosf(task1.t_global
      *1000));
  //control_main(task1.t_global,&imu_data,&eff_data,&mra_data);
/* Actuate */
  actuate(spi_param.spi_dev,&mra_data);
}
void exit_program (void)
Internal function to end program.
Definition at line 135 of file main.c.
Referenced by ui_update().
                       {
  quittask = 1;
  return;
}
int get_time (double * time_control_task_s, double * Ts_control_task_s, double * mean_time_control_task_s, double * t0_control_task_s)
Definition at line 122 of file main.c.
Referenced by ui_overview_data().
{
  *time_control_task_s = task1.t_global;
  *Ts_control_task_s = (task1.period_us)/1e6;
  *mean_time_control_task_s = task1.T_mean_global;
  *t0_control_task_s = t0;
  return SUCCESS;
}
int main (void)
Definition at line 39 of file main.c.
References IMU_PARAM_STRUCT::acc, IMU_PARAM_STRUCT::param_gyr::act, IMU_PARAM_STRUCT::param_gyr::clk_source, control_task(), SPI_PARAM_STRUCT::cs, devices_init(), FAILURE, IMU_PARAM_STRUCT::param_acc::full_res, IMU_PARAM_STRUCT::gyr, IMU_PARAM_STRUCT::i2c_dev, IMU_PARAM_STRUCT::param_gyr::lpf_bw, IMU_PARAM_STRUCT::mag, IMU_PARAM_STRUCT::param_mag::meas_mode, SPI_PARAM_STRUCT::mode, IMU_PARAM_STRUCT::param_mag::op_mode, quittask, IMU_PARAM_STRUCT::param_acc::range, IMU_PARAM_STRUCT::param_mag::range, IMU_PARAM_STRUCT::param_acc::rate, IMU_PARAM_STRUCT::param_gyr::rate, IMU_PARAM_STRUCT::param_mag::rate, IMU_PARAM_STRUCT::param_mag::samples_avg, SPI_PARAM_STRUCT::speed, SPI_PARAM_STRUCT::spi_dev, SUCCESS, TASK_UI_PERIOD, timer_new_task(), timer_start_task(), timer_stop_task(), ui_close(), ui_init(), and ui_task().
              {
  int return_value = SUCCESS;
/*Setting config values:*/
  // Parameters for IMU
  imu_param.acc.full_res=1;
  imu_param.acc.rate=100;
  imu_param.acc.range=16;
  imu_param.gyr.rate=100;
  imu_param.gyr.lpf_bw=188;
  imu_param.gyr.clk_source='Z';
  imu_param.gyr.act="XYZ";
  imu_param.mag.rate=75;
  imu_param.mag.range=0;
  imu_param.mag.samples_avg=8;
  imu_param.mag.meas_mode=0;
  imu_param.mag.op_mode=0;
  // Parameters for SPI
  spi_param.mode=0;
  spi_param.speed=375000;
  spi_param.cs=0;
  // Task for control UI:
  timer_new_task(&task1,ui_task);
  timer_new_task(&task2,control_task);
  
/*Initialization:*/
  if(devices_init(&imu_param,&spi_param,&mra_data
      )!=SUCCESS){
    perror("Unsuccesful devices initialization");
    return FAILURE;
  }
  if(ui_init()!=SUCCESS){
    perror("Unsuccesful user interface initialization");
    return FAILURE;
  }
  timer_start_task(&task1,TASK_UI_PERIOD);
  //timer_start_task(task2);
/* Main loop: */
  while(quittask == 0){
    //ui_task(0);
  }
/*Shutting Down:*/
  timer_stop_task(&task1);
  usleep(2000);
  //timer_stop_task(&task2);
  if(ui_close()==FAILURE){
    return_value = FAILURE;
  }
  close(imu_param.i2c_dev);
  close(spi_param.spi_dev);
  return return_value;
}
static void ui_task (int signo) [static]
Definition at line 100 of file main.c.
References failure, IMU_PARAM_STRUCT::i2c_dev, read_all_data(), SPI_PARAM_STRUCT::spi_dev, SUCCESS, total, and ui_update().
Referenced by main().
                              {
  total++;
  if(read_all_data(imu_param.i2c_dev, spi_param
      .spi_dev, &imu_data,&eff_data, &mra_data, &
      enc_data) != SUCCESS) failure++;
  ui_update(&imu_data, &eff_data, &mra_data,&
      enc_data, total, failure);
}
Variable Documentation
int acquire = 0
Definition at line 34 of file main.c.
EFF_DATA_STRUCT eff_data
Definition at line 26 of file main.c.
ENC_DATA_STRUCT enc_data
Definition at line 28 of file main.c.
int failure = 0
Definition at line 33 of file main.c.
Referenced by control_task(), periodic_task_1(), periodic_task_2(), threads_linux_periodic_task_1(), threads_linux_periodic_task_2(), and ui_task().
IMU_DATA_STRUCT imu_data
Definition at line 27 of file main.c.
Referenced by control_main().
IMU_PARAM_STRUCT imu_param
Definition at line 22 of file main.c.
MRA_DATA_STRUCT mra_data
Definition at line 29 of file main.c.
Referenced by control_main().
int quittask = 0
Definition at line 36 of file main.c.
Referenced by exit_program(), main(), and threads_linux_init().
SPI_PARAM_STRUCT spi_param
Definition at line 23 of file main.c.
int t0 = 0
Definition at line 37 of file main.c.
Referenced by get_time(), periodic_task_1(), reset_timer(), threads_get_time(), threads_linux_periodic_task_1(), threads_linux_periodic_task_2(), threads_linux_timer_function_task_1(), threads_reset_timer(), timer_function_task_1(), and ui_overview_data().
TASK_S task1
Main rotine for control:
Author
Rafael Lima
Version
0.1
Definition at line 16 of file main.c.
Referenced by main().
TASK_S task2
Definition at line 16 of file main.c.
Referenced by main().
int total = 0
Definition at line 32 of file main.c.
Referenced by control_task(), periodic_task_1(), periodic_task_2(), threads_linux_periodic_task_1(), threads_linux_periodic_task_2(), and ui_task().