schunk_high/include/schunk_high/quaternion.h File Reference
Data Structures
struct Q
Typedefs
typedef Q Quaternion
Functions
Q * Q_alloc ()
Quaternion Library.
Q * Q_create (double a, double b, double c, double d)
Allocates a Quaternion and its values.
Q * Q_copy (Q *q)
Makes a copy of a Quaternion.
void Q_free (Q *q)
Frees an Allocated Quaternion from memory.
void Q_print (Q *q)
Prints a Quaternion.
Q * Q_add (Q *a, Q *b, int freeA, int freeB)
Quaternion Addition.
Q * Q_mult (Q *a, Q *b, int freeA, int freeB)
Quaternion Multiplication.
Q * Q_multd (double a, Q *b, int freeB)
Quaternion Multiplication by Double.
Q * Q_getConj (Q *a, int freeA)
Quaternion Conjugate.
Q * Q_sub (Q *a, Q *b, int freeA, int freeB)
Quaternion Subtraction.
double Q_getPitchAngle (Q *q)
Gets the `PITCH` angle.
Typedef Documentation
typedef Q Quaternion
Definition at line 12 of file quaternion.h.
Function Documentation
Q* Q_add (Q * a, Q * b, int freeA, int freeB)
Quaternion Addition.
Sums each element of each Quaternion. The result is a newly allocated Quaternion with the result. Quaternion Addition is commutative.
Parameters
a The first Quaternion.
b The second Quaternion.
freeA TRUE if you want to free a from memory.
freeB TRUE if you want to free b from memory.
Returns
c = a+b.
Definition at line 96 of file quaternion.c.
References Q_alloc(), Q_free(), and Q::v.
Referenced by DQ_mult().
                                          {
        Q* c = Q_alloc();
        
        c->v[0] = a->v[0]+b->v[0];
        c->v[1] = a->v[1]+b->v[1];
        c->v[2] = a->v[2]+b->v[2];
        c->v[3] = a->v[3]+b->v[3];
        
        if(freeA){Q_free(a);}
        if(freeB){Q_free(b);}
        return c;
}
Q* Q_alloc ()
Quaternion Library.
Author
Murilo Marques Marinho. Allocates a Quaternion, its components are not initialized. Use with care.
Returns
a Quaternion* to the newly allocated region.
Definition at line 17 of file quaternion.c.
Referenced by Link_DQFT(), Q_add(), Q_create(), Q_mult(), and Q_sub().
            {
        return (Q*)malloc(sizeof(Q));
}
Q* Q_copy (Q * q)
Makes a copy of a Quaternion.
Parameters
q The Quaternion you want to copy.
Returns
a Quaternion copy.
Definition at line 57 of file quaternion.c.
References Q_create(), and Q::v.
Referenced by DQ_createFromQuaternion(), and DQ_getR().
               {
        Q* qc = Q_create(q->v[0],q->v[1],q->v[2],q->v[3]);
        return qc;
}
Q* Q_create (double a, double b, double c, double d)
Allocates a Quaternion and its values.
Parameters
a The scalar part.
b The part following the i unity vector.
c The part following the j unity vector.
d The part following the k unity vector.
Returns
A Quaternion = [a + ib + jc + kd].
Definition at line 45 of file quaternion.c.
References Q_alloc(), and Q::v.
Referenced by DQ_create(), Q_copy(), Q_getConj(), and Q_multd().
                                                   {
        Q* q = Q_alloc();
        q->v[0] = a; q->v[1] = b; q->v[2] = c; q->v[3] = d;
return q;
}
void Q_free (Q * q)
Frees an Allocated Quaternion from memory.
Parameters
q A Quaternion* you wish to free.
Definition at line 68 of file quaternion.c.
Referenced by DQ_free(), main(), Cartesian_pose_controller::printPose(), Q_add(), Q_getConj(), Q_mult(), Q_multd(), Q_sub(), and Robot_getGJacobian().
                 {
        free(q);
}
Q* Q_getConj (Q * a, int freeA)
Quaternion Conjugate.
Parameters
a The entry Quaternion.
freeA TRUE if you want to free a from memory.
Returns
a Quaternion representing the Conjugate of a, using the operation: if a = (a1,a2,a3,a4), Q_getConj(a) = (a1,-a2,-a3,-a4).
Definition at line 197 of file quaternion.c.
References Q_create(), Q_free(), and Q::v.
Referenced by DQ_getT().
                             {
        Q* b = Q_create(a->v[0],-(a->v[1]),-(a->v[2]),-(a->v[3]));
        if(freeA){Q_free(a);}
        return b;
}
double Q_getPitchAngle (Q * q)
Gets the `PITCH` angle.
Parameters
q The Unit Quaternion representing the rotation.
Returns
a Double with the desired value in radians.
Definition at line 27 of file quaternion.c.
References Q::v.
Referenced by DQ_getPitchAngle().
                            {
        double ret;
        ret = asin(2*(q->v[0]*q->v[2]-q->v[3]*q->v[1]));
        return ret;
}
Q* Q_mult (Q * a, Q * b, int freeA, int freeB)
Quaternion Multiplication.
It uses the H+ operator on the first term to make the multiplication. Quaternion Multiplication is not commutative in general.
Parameters
a The first Quaternion
b The second Quaternion
freeA TRUE if you want to free a from memory.
freeB TRUE if you want to free b from memory.
Returns
c = a*b
Definition at line 154 of file quaternion.c.
References Q_alloc(), Q_free(), and Q::v.
Referenced by DQ_createFromQuaternion(), DQ_getT(), and DQ_mult().
                                           {
        Q* c = Q_alloc();
        
        c->v[0] = a->v[0]*b->v[0] - a->v[1]*b->v[1] - a->v[2]*b->v[2] -
      a->v[3]*b->v[3];
        c->v[1] = a->v[1]*b->v[0] + a->v[0]*b->v[1] - a->v[3]*b->v[2] +
      a->v[2]*b->v[3];
        c->v[2] = a->v[2]*b->v[0] + a->v[3]*b->v[1] + a->v[0]*b->v[2] -
      a->v[1]*b->v[3];
        c->v[3] = a->v[3]*b->v[0] - a->v[2]*b->v[1] + a->v[1]*b->v[2] +
      a->v[0]*b->v[3];
        if(freeA){Q_free(a);}
        if(freeB){Q_free(b);}
        return c;
}
Q* Q_multd (double a, Q * b, int freeB)
Quaternion Multiplication by Double.
Multiplies each one of its terms by the desired double.
Parameters
a The double.
b The Quaternion.
freeA TRUE if you want to free a from memory.
freeB TRUE if you want to free b from memory.
Returns
c = a*b
Definition at line 180 of file quaternion.c.
References Q_create(), Q_free(), and Q::v.
Referenced by DQ_createFromQuaternion(), and DQ_getT().
                                    {
        Q* c = Q_create(b->v[0]*a,b->v[1]*a,b->v[2]*a,b->v[3]*a);
        
        if(freeB){Q_free(b);}
        return c;
}
void Q_print (Q * q)
Prints a Quaternion.
Parameters
q The Quaternion you want to print.
Definition at line 77 of file quaternion.c.
References Q::v.
                  {
        printf("\t[%f %f %f %f]\n",q->v[0],q->v[1],q->v[2],q->v[3]);
}
Q* Q_sub (Q * a, Q * b, int freeA, int freeB)
Quaternion Subtraction.
Subtracts each element of each Quaternion. The result is a newly allocated Quaternion with the result. Quaternion Subtraction is commutative.
Parameters
a The first Quaternion.
b The second Quaternion.
freeA TRUE if you want to free a from memory.
freeB TRUE if you want to free b from memory.
Returns
c = a-b.
Definition at line 124 of file quaternion.c.
References Q_alloc(), Q_free(), and Q::v.
Referenced by Robot_getGJacobian().
                                          {
        Q* c = Q_alloc();
        
        c->v[0] = a->v[0]-b->v[0];
        c->v[1] = a->v[1]-b->v[1];
        c->v[2] = a->v[2]-b->v[2];
        c->v[3] = a->v[3]-b->v[3];
        
        if(freeA){Q_free(a);}
        if(freeB){Q_free(b);}
        return c;
}