André backup conflitos/spi_functions (Cópia em conflito de André Carvalho 2013-04-26).c File Reference
#include `spi_functions.h`
*
Macros
#define SUCCESS 1
#define FAILURE 0
Functions
int pabort (const char *s)
int spi_init (uint8_t mode, uint32_t speed, uint8_t cs)
void spi_end (int spi_dev)
int adc_read (int spi_dev, uint8_t ch, uint8_t sgl, short int *data)
uint8_t dac_write (int spi_dev, uint8_t ch, uint8_t _shdn, unsigned short int data)
Variables
static uint8_t bits = 8
static uint16_t delay
Macro Definition Documentation
#define FAILURE 0
Definition at line 8 of file spi_functions (Cópia em conflito de André Carvalho 2013-04-26).c.
Referenced by adc_read().
#define SUCCESS 1
Definition at line 7 of file spi_functions (Cópia em conflito de André Carvalho 2013-04-26).c.
Referenced by adc_read().
Function Documentation
int adc_read (int spi_dev, uint8_t ch, uint8_t sgl, short int * data)
Definition at line 168 of file spi_functions (Cópia em conflito de André Carvalho 2013-04-26).c.
Referenced by main(), and read_all_data().
{
        int ret;
        if(ch<0 || ch>7) return FAILURE;
        uint8_t tx[] = {(ch>>2)|(sgl<<1)|0x04, ch<<6, 0x00,};
        uint8_t rx[ARRAY_SIZE(tx)] = {0, };
        struct spi_ioc_transfer tr = {
                .tx_buf = (unsigned long)tx,
                .rx_buf = (unsigned long)rx,
                .len = ARRAY_SIZE(tx),
                .delay_usecs = delay,
                .speed_hz = 0,
                .bits_per_word = 0,
        };
        ret = ioctl(spi_dev, SPI_IOC_MESSAGE(1), &tr);
        if (ret == 1) return FAILURE;
//printf("\nRx = 0x%X 0x%X 0x%X\n",rx[0],rx[1],rx[2]);
//printf("\nValor retornado pelo conversor AD:
       %d\n\n",rx[2]+((rx[1]&0x0F)<<8));
        *data=(short int)(rx[2]+((rx[1]&0x0F)<<8));
        return SUCCESS;
}
uint8_t dac_write (int spi_dev, uint8_t ch, uint8_t _shdn, unsigned short int data)
Definition at line 191 of file spi_functions (Cópia em conflito de André Carvalho 2013-04-26).c.
Referenced by actuate().
{
        int ret;
        union txunion{
        unsigned short int data16;
        uint8_t data8[2];
        }txunion;
        if(ch<0 || ch>1) return pabort("Wrong channel value for DAC");
        if(data>4095) return pabort("Value exceeded for DAC");
        txunion.data16 = 0x6000|(ch<<15)|(_shdn<<12)|(data&0x0FFF);
        uint8_t tx[] = {txunion.data8[0], txunion.data8[1]};
        uint8_t rx[ARRAY_SIZE(tx)] = {0, };
        struct spi_ioc_transfer tr = {
                .tx_buf = (unsigned long)tx,
                .rx_buf = (unsigned long)rx,
                .len = ARRAY_SIZE(tx),
                .delay_usecs = delay,
                .speed_hz = 0,
                .bits_per_word = 0,
        };
        ret = ioctl(spi_dev, SPI_IOC_MESSAGE(1), &tr);
        if (ret == 1) return pabort("can't send spi message");
//printf("\nRx = 0x%X 0x%X 0x%X\n",rx[0],rx[1],rx[2]);
//printf("\nValor retornado pelo conversor AD:
       %d\n\n",rx[2]+((rx[1]&0x0F)<<8));
        return 1;
}
int pabort (const char * s)
Definition at line 10 of file spi_functions (Cópia em conflito de André Carvalho 2013-04-26).c.
Referenced by adc_read(), dac_write(), and spi_init().
{
        perror(s);
        return -1;
}
void spi_end (int spi_dev)
Definition at line 162 of file spi_functions (Cópia em conflito de André Carvalho 2013-04-26).c.
{
  close(spi_dev);
  return;
}
int spi_init (uint8_t mode, uint32_t speed, uint8_t cs)
Definition at line 99 of file spi_functions (Cópia em conflito de André Carvalho 2013-04-26).c.
Referenced by devices_init(), and main().
{
        int ret = 0;
        int spi_dev;
        char *device;
        //parse_opts(argc, argv);
        switch(cs){
          case 0:
            device = "/dev/spidev1.0";
            break;
          case 1:
            device = "/dev/spidev1.1";
            break;
          default:
            return pabort("invalid chip select value");
        }
            
        
        spi_dev = open(device, O_RDWR);
        if (spi_dev < 0)
                return pabort("can't open device");
printf("\nspi_dev = %d\n",spi_dev);
        /*
         * spi mode
         */
        ret = ioctl(spi_dev, SPI_IOC_WR_MODE, &mode);
        if (ret == -1)
                return pabort("can't set spi mode");
        ret = ioctl(spi_dev, SPI_IOC_RD_MODE, &mode);
        if (ret == -1)
                return pabort("can't get spi mode");
        /*
         * bits per word
         */
        ret = ioctl(spi_dev, SPI_IOC_WR_BITS_PER_WORD, &bits);
        if (ret == -1)
                return pabort("can't set bits per word");
        ret = ioctl(spi_dev, SPI_IOC_RD_BITS_PER_WORD, &bits);
        if (ret == -1)
                return pabort("can't get bits per word");
        /*
         * max speed hz
         */
        ret = ioctl(spi_dev, SPI_IOC_WR_MAX_SPEED_HZ, &speed);
        if (ret == -1)
                return pabort("can't set max speed hz");
        ret = ioctl(spi_dev, SPI_IOC_RD_MAX_SPEED_HZ, &speed);
        if (ret == -1)
                return pabort("can't get max speed hz");
        //printf("spi mode: %d\n", mode);
        //printf("bits per word: %d\n", bits);
        //printf("max speed: %d Hz (%d KHz)\n", speed, speed/1000);
        return spi_dev;
}
Variable Documentation
uint8_t bits = 8 [static]
Definition at line 17 of file spi_functions (Cópia em conflito de André Carvalho 2013-04-26).c.
Referenced by conv_byte_hex_bin(), and spi_init().
uint16_t delay [static]
Definition at line 19 of file spi_functions (Cópia em conflito de André Carvalho 2013-04-26).c.
Referenced by adc_read(), and dac_write().