threads_linux.c File Reference
#include <stdio.h>
*
#include <stdlib.h>
*
#include <unistd.h>
*
#include <signal.h>
*
#include <string.h>
*
#include <time.h>
*
#include <sys/time.h>
*
#include `gmatrix.h`
*
#include `imu.h`
*
#include `magnetometer.h`
*
#include `gps.h`
*
#include `sonar.h`
*
#include `sensors.h`
*
#include `calibration.h`
*
#include `protocol.h`
*
#include `estimation.h`
*
#include `control.h`
*
#include `datalogger.h`
*
#include `ui.h`
*
#include `mavlink_module.h`
*
#include `threads_linux.h`
*
Macros
#define TASK1_PERIOD_US 20000
#define TASK2_PERIOD_US 100000
Functions
void threads_linux_timer_task_1 (union sigval sigval)
void threads_linux_timer_task_2 (union sigval sigval)
int threads_linux_init (void)
int threads_linux_periodic_task_1 (void)
int threads_linux_periodic_task_2 (void)
void threads_linux_timer_task_1 (union sigval sigval)
void threads_linux_timer_task_2 (union sigval sigval)
void threads_linux_timer_start_task_1 (void)
void threads_linux_timer_start_task_2 (void)
void threads_linux_timer_stop_task_1 (void)
void threads_linux_timer_stop_task_2 (void)
void threads_linux_timer_function_task_1 (void)
void threads_linux_timer_function_task_2 (void)
int threads_reset_timer (void)
int threads_get_time (double *time_control_task_s, double *Ts_control_task_s, double *mean_time_control_task_s, double *t0_control_task_s)
Variables
unsigned char quittask
int total = 0
int failure = 0
timer_t timer_task_1
volatile double t_task_1_global = 0.0
volatile double T_task_1_exec_global = 0.0
volatile double T_task_1_mean_global = 0.0
volatile double T_task_1_min_global = 0.0
volatile double T_task_1_max_global = 0.0
volatile int task_1_period_us = TASK1_PERIOD_US
volatile int flag_task_1_firstexecution = 1
volatile double t0 = 0.0
timer_t timer_task_2
volatile double t_task_2_global = 0.0
volatile double T_task_2_exec_global = 0.0
volatile double T_task_2_mean_global = 0.0
volatile double T_task_2_min_global = 0.0
volatile double T_task_2_max_global = 0.0
volatile int task_2_period_us = TASK2_PERIOD_US
volatile int flag_task_2_firstexecution = 1
unsigned int telemetry_mode = UI_NCURSES_MODE
BATTERY_DATA_STRUCT battery_data
GPS_DATA_STRUCT gps_data
IMU_DATA_STRUCT imu_data
PITOT_DATA_STRUCT pitot_data
PWM_READ_DATA_STRUCT pwm_read_data
PWM_WRITE_DATA_STRUCT pwm_write_data
SCP1000_DATA_STRUCT scp1000_data
SONAR_DATA_STRUCT sonar_data
GPSMEASURE gps_measure
IMUMEASURE imu_measure
MAGNETOMETERMEASURE magnetometer_measure
SONARMEASURE sonar_measure
CALIBRATION_ALTIMETER_STRUCT calibration_altimeter_data
CALIBRATION_LOCAL_COORDINATE_SYSTEM_STRUCT calibration_local_coordinate_system_data
CALIBRATION_LOCAL_FIELDS_STRUCT calibration_local_fields_data
ESTIMATION_DATA_STRUCT estimation_data
CONTROL_DATA_STRUCT control_data
Macro Definition Documentation
#define TASK1_PERIOD_US 20000
Definition at line 32 of file threads_linux.c.
Referenced by threads_linux_init().
#define TASK2_PERIOD_US 100000
Definition at line 33 of file threads_linux.c.
Referenced by threads_linux_init().
Function Documentation
int threads_get_time (double * time_control_task_s, double * Ts_control_task_s, double * mean_time_control_task_s, double * t0_control_task_s)
Definition at line 576 of file threads_linux.c.
References t0, t_task_1_global, T_task_1_mean_global, and task_1_period_us.
{
    *time_control_task_s = t_task_1_global;
    *Ts_control_task_s = task_1_period_us/1e6;
    *mean_time_control_task_s = T_task_1_mean_global;
    *t0_control_task_s = t0;
    return THREADS_LINUX_SUCCESS;
}
int threads_linux_init (void)
Definition at line 94 of file threads_linux.c.
References battery_data, calibration_altimeter_data, calibration_local_coordinate_system_data, calibration_local_fields_data, control_data, datalogger_close(), datalogger_init(), DATALOGGER_RUNNING, datalogger_status(), DATALOGGER_SUCCESS, datalogger_update_IPC(), datalogger_write_file(), estimation_data, gps_data, gps_measure, imu_measure, magnetometer_measure, pitot_data, pwm_read_data, pwm_write_data, quittask, scp1000_data, sonar_data, sonar_measure, status, TASK1_PERIOD_US, TASK2_PERIOD_US, task_1_period_us, threads_linux_timer_start_task_1(), threads_linux_timer_start_task_2(), threads_linux_timer_stop_task_1(), threads_linux_timer_stop_task_2(), ui_close(), and ui_init().
{
    int status = 0;
    int n = 0;
    int return_value = THREADS_LINUX_SUCCESS;
    // Init data
    status = sensors_init(&battery_data, &gps_data, &
      imu_data, &pitot_data, &pwm_read_data, &
      pwm_write_data, &scp1000_data, &sonar_data);
    if(status != SENSORS_SUCCESS)
    {
        return_value = THREADS_LINUX_FAILURE;
    }
    if(return_value != THREADS_LINUX_FAILURE)
    {
        status = calibration_init(&calibration_local_coordinate_system_data
      , &calibration_local_fields_data, &
      calibration_altimeter_data);
        if(status != CALIBRATION_SUCCESS)
        {
            return_value = THREADS_LINUX_FAILURE;
        }
    }
    if(return_value != THREADS_LINUX_FAILURE)
    {
        status = gps_init(&gps_measure);
        if(status != 1)
        {
            return_value = THREADS_LINUX_FAILURE;
        }
    }
    if(return_value != THREADS_LINUX_FAILURE)
    {
        status = imu_init(&imu_measure);
        if(status != 1)
        {
            return_value = THREADS_LINUX_FAILURE;
        }
    }
    if(return_value != THREADS_LINUX_FAILURE)
    {
        status = magnetometer_init(&magnetometer_measure);
        if(status != 1)
        {
            return_value = THREADS_LINUX_FAILURE;
        }
    }
    if(return_value != THREADS_LINUX_FAILURE)
    {
        status = sonar_init(&sonar_measure);
        if(status != 1)
        {
                return_value = THREADS_LINUX_FAILURE;
        }
    }
    if(return_value != THREADS_LINUX_FAILURE)
    {
        status = estimation_init(ESTIMATION_DO_NOT_ESTIMATE_ACCEL_BIAS, &
      estimation_data);
        if(status != ESTIMATION_SUCCESS)
        {
            return_value = THREADS_LINUX_FAILURE;
        }
    }
    if(return_value != THREADS_LINUX_FAILURE)
    {
        status = control_init(&control_data);
        if(status != CONTROL_SUCCESS)
        {
            return_value = THREADS_LINUX_FAILURE;
        }
    }
    if(return_value != THREADS_LINUX_FAILURE)
    {
        status = protocol_init();
        if(status != PROTOCOL_SUCCESS)
        {
            return_value = THREADS_LINUX_FAILURE;
        }
    }
    if(return_value != THREADS_LINUX_FAILURE)
    {
        status = ui_init();
        if(status != UI_SUCCESS)
        {
            return_value = THREADS_LINUX_FAILURE;
        }
    }
    if(return_value != THREADS_LINUX_FAILURE)
    {
        status = datalogger_init();
        if(status != DATALOGGER_SUCCESS)
        {
            return_value = THREADS_LINUX_FAILURE;
        }
    }
    // Main Loop
    if(return_value != THREADS_LINUX_FAILURE)
    {
        threads_linux_timer_start_task_1();
        usleep(0.5*task_1_period_us);
        threads_linux_timer_start_task_2();
        usleep(5*task_1_period_us);
        while(quittask == 0)
        {
            #if ANU_COMPILE_FOR_OVERO
            #else
            if(datalogger_status() == DATALOGGER_RUNNING)
      datalogger_update_IPC();
            #endif
            if(++n>100)
            {
                if(datalogger_status() == DATALOGGER_RUNNING)
      datalogger_write_file();
                n = 0;
            }
            usleep(5*task_1_period_us);
        }
        threads_linux_timer_stop_task_1();
        usleep(TASK1_PERIOD_US);
        threads_linux_timer_stop_task_2();
        usleep(TASK2_PERIOD_US);
    }
    status = datalogger_close();
    if(status != DATALOGGER_SUCCESS)
    {
        return_value = THREADS_LINUX_FAILURE;
    }
    status = ui_close();
    if(status != UI_SUCCESS)
    {
        return_value = THREADS_LINUX_FAILURE;
    }
    status = protocol_close();
    if(status != PROTOCOL_SUCCESS)
    {
        return_value = THREADS_LINUX_FAILURE;
    }
    status = control_close();
    if(status != CONTROL_SUCCESS)
    {
        return_value = THREADS_LINUX_FAILURE;
    }
    status = estimation_close(&estimation_data);
    if(status != ESTIMATION_SUCCESS)
    {
        return_value = THREADS_LINUX_FAILURE;
    }
    status = magnetometer_close(&magnetometer_measure);
    if(status != 1)
    {
        return_value = THREADS_LINUX_FAILURE;
    }
    status = imu_close(&imu_measure);
    if(status != 1)
    {
        return_value = THREADS_LINUX_FAILURE;
    }
    status = gps_close(&gps_measure);
    if(status != 1)
    {
        return_value = THREADS_LINUX_FAILURE;
    }
    status = calibration_close(&calibration_local_coordinate_system_data
      , &calibration_local_fields_data, &
      calibration_altimeter_data);
    if(status != CALIBRATION_SUCCESS)
    {
        return_value = THREADS_LINUX_FAILURE;
    }
    status = sensors_close();
    if(status != SENSORS_SUCCESS)
    {
        return_value = THREADS_LINUX_FAILURE;
    }
    return return_value;
}
int threads_linux_periodic_task_1 (void)
Definition at line 287 of file threads_linux.c.
References battery_data, calibration_altimeter_data, calibration_local_coordinate_system_data, calibration_local_fields_data, control_data, DATALOGGER_NOT_RUNNING, DATALOGGER_RUNNING, datalogger_set_Ts(), datalogger_status(), datalogger_update(), estimation_data, failure, gps_data, gps_measure, imu_measure, magnetometer_measure, pitot_data, pwm_read_data, pwm_write_data, scp1000_data, sonar_data, sonar_measure, t0, T_task_1_exec_global, t_task_1_global, T_task_2_exec_global, task_1_period_us, threads_reset_timer(), and total.
Referenced by threads_linux_timer_function_task_1().
{
    static int previous_calibration_status = CALIBRATION_NOT_RUNNING;
    int current_calibration_status; // Used to detect lowering edge
    static int previous_datalogger_status = DATALOGGER_NOT_RUNNING;
    int current_datalogger_status; // Used to detect rising edge
    // Main communication/control thread
    //Acquire
    total++;
    if(protocol_request_all_data(&battery_data, &gps_data, &
      imu_data, &pitot_data, &pwm_read_data, &
      pwm_write_data, &scp1000_data, &sonar_data) != PROTOCOL_SUCCESS)
    {
        failure++;
    }
    // Calibrate and Estimate
    calibration_calibrate_all(&pwm_read_data, &scp1000_data, &
      battery_data, &gps_data, &imu_data, &pitot_data, &
      sonar_data, &calibration_local_coordinate_system_data, &
      calibration_altimeter_data, &
      calibration_local_fields_data, &gps_measure, &
      imu_measure, &magnetometer_measure);
    estimation_update_state_estimate(&estimation_data, &
      gps_measure, &imu_measure, &magnetometer_measure, &
      sonar_measure, &calibration_local_fields_data,
      task_1_period_us/(double)1e6);
    // Control
    control_main_task(t_task_1_global, &pwm_write_data, &
      pwm_read_data, &control_data, &estimation_data);
    // Actuate
    protocol_send_actuation_data(&pwm_write_data);
    // Log
    current_datalogger_status = datalogger_status();
    if(current_datalogger_status == DATALOGGER_RUNNING)
    {
        if(previous_datalogger_status == DATALOGGER_NOT_RUNNING) // Rising edge
        {
            datalogger_set_Ts(task_1_period_us/1e6);
            datalogger_set_initial_altimeter_parameters(&
      calibration_altimeter_data);
            datalogger_set_local_coordinate_system(&
      calibration_local_coordinate_system_data);
            datalogger_set_local_fields(&calibration_local_fields_data);
            threads_reset_timer();
        }
        datalogger_update(t_task_1_global,
      T_task_1_exec_global, T_task_2_exec_global,
      t0, &battery_data, &gps_data, &imu_data, &
      pitot_data, &pwm_read_data, &pwm_write_data, &
      scp1000_data, &sonar_data, &gps_measure, &
      imu_measure, &magnetometer_measure, &
      estimation_data, &control_data);
    }
    previous_datalogger_status = current_datalogger_status;
    current_calibration_status = calibration_get_status();
    if(current_calibration_status == CALIBRATION_RUNNING)
    {
        calibration_imu_add_sample_bias_estimate(&imu_data);
        calibration_altimeter_add_sample_initial_pressure(&scp1000_data, &
      calibration_altimeter_data);
    }
    else // Calibration not running
    {
        if(previous_calibration_status == CALIBRATION_RUNNING) // Lowering edge
        {
            calibration_imu_finish_bias_estimate(&imu_data);
            calibration_altimeter_finish_initial_pressure_estimate(&
      calibration_altimeter_data);
        }
    }
    previous_calibration_status = current_calibration_status;
    return THREADS_LINUX_SUCCESS;
}
int threads_linux_periodic_task_2 (void)
Definition at line 348 of file threads_linux.c.
References battery_data, calibration_altimeter_data, calibration_local_coordinate_system_data, calibration_local_fields_data, control_data, estimation_data, failure, gps_data, gps_measure, imu_measure, magnetometer_measure, pitot_data, pwm_read_data, pwm_write_data, scp1000_data, sonar_data, t0, t_task_1_global, telemetry_mode, total, UI_NCURSES_MODE, and ui_update().
Referenced by threads_linux_timer_function_task_2().
{
    // UI thread
    if(telemetry_mode == UI_NCURSES_MODE)
    {
        ui_update(&battery_data, &gps_data, &
      imu_data, &pitot_data, &pwm_read_data, &
      pwm_write_data, &scp1000_data, &sonar_data, &
      gps_measure, &imu_measure, &magnetometer_measure, &
      calibration_local_coordinate_system_data, &
      calibration_local_fields_data, &
      calibration_altimeter_data, &estimation_data, &
      control_data, total, failure);
    }
    if(telemetry_mode == UI_MAVLINK_MODE)
    {
        mavlink_module_update(t_task_1_global, t0, &
      battery_data, &gps_data, &imu_data, &pitot_data, &
      pwm_read_data, &pwm_write_data, &scp1000_data, &
      sonar_data, &gps_measure, &imu_measure, &
      magnetometer_measure, &estimation_data, &
      control_data);
    }
    return THREADS_LINUX_SUCCESS;
}
void threads_linux_timer_function_task_1 (void)
Definition at line 457 of file threads_linux.c.
References flag_task_1_firstexecution, status, t0, T_task_1_exec_global, t_task_1_global, T_task_1_max_global, T_task_1_mean_global, T_task_1_min_global, and threads_linux_periodic_task_1().
Referenced by threads_linux_timer_task_1().
{
    int status = 0;
    static struct timeval timereset;
    static struct timeval time;
    static struct timeval time_exec_start;
    static struct timeval time_exec_end;
    static double T_task,t_task,t_task_previous;
    static double T_task_mean,T_task_min,T_task_max,T_task_exec;
    gettimeofday(&time_exec_start, NULL);
    // Time calculation
    if(flag_task_1_firstexecution)
    {
        gettimeofday(&timereset, NULL);
        t_task = 0.0;
        T_task_mean = 0.0;
        T_task_min = 0.0;
        T_task_max = 0.0;
        T_task_exec = 0.0;
    }
    gettimeofday(&time, NULL);
    t_task = ((time.tv_sec - timereset.tv_sec) + (time.tv_usec - timereset.tv_usec)*1e-6);
    T_task = t_task - t_task_previous;
    t_task_previous = t_task;
    if(flag_task_1_firstexecution)
    {
        T_task_mean = T_task;
        T_task_min = 1e200;
        T_task_max = 0.0;
        t0 = t_task;
    }
    else
    {
        T_task_mean = 0.05*T_task + 0.95*T_task_mean;
        if(T_task < T_task_min) T_task_min = T_task;
        if(T_task > T_task_max) T_task_max = T_task;
    }
    // Run the thread
    status = threads_linux_periodic_task_1();
    gettimeofday(&time_exec_end, NULL);
    T_task_exec = ((time_exec_end.tv_sec - time_exec_start.tv_sec) + (time_exec_end.tv_usec -
      time_exec_start.tv_usec)*1e-6);
    t_task_1_global = t_task;
    T_task_1_mean_global = T_task_mean;
    T_task_1_min_global = T_task_min;
    T_task_1_max_global = T_task_max;
    T_task_1_exec_global = T_task_exec;
    flag_task_1_firstexecution = 0;
}
void threads_linux_timer_function_task_2 (void)
Definition at line 514 of file threads_linux.c.
References flag_task_2_firstexecution, status, T_task_2_exec_global, t_task_2_global, T_task_2_max_global, T_task_2_mean_global, T_task_2_min_global, and threads_linux_periodic_task_2().
Referenced by threads_linux_timer_task_2().
{
    int status = 0;
    static struct timeval timereset;
    static struct timeval time;
    static struct timeval time_exec_start;
    static struct timeval time_exec_end;
    static double T_task,t_task,t_task_previous;
    static double T_task_mean,T_task_min,T_task_max,T_task_exec;
    gettimeofday(&time_exec_start, NULL);
    // Time calculation
    if(flag_task_2_firstexecution)
    {
        gettimeofday(&timereset, NULL);
        t_task = 0.0;
        T_task_mean = 0.0;
        T_task_min = 0.0;
        T_task_max = 0.0;
        T_task_exec = 0.0;
    }
    gettimeofday(&time, NULL);
    t_task = ((time.tv_sec - timereset.tv_sec) + (time.tv_usec - timereset.tv_usec)*1e-6);
    T_task = t_task - t_task_previous;
    t_task_previous = t_task;
    if(flag_task_2_firstexecution)
    {
        T_task_mean = T_task;
        T_task_min = 1e200;
        T_task_max = 0.0;
    }
    else
    {
        T_task_mean = 0.05*T_task + 0.95*T_task_mean;
        if(T_task < T_task_min) T_task_min = T_task;
        if(T_task > T_task_max) T_task_max = T_task;
    }
    // Run the thread
    status = threads_linux_periodic_task_2();
    gettimeofday(&time_exec_end, NULL);
    T_task_exec = ((time_exec_end.tv_sec - time_exec_start.tv_sec) + (time_exec_end.tv_usec -
      time_exec_start.tv_usec)*1e-6);
    t_task_2_global = t_task;
    T_task_2_mean_global = T_task_mean;
    T_task_2_min_global = T_task_min;
    T_task_2_max_global = T_task_max;
    T_task_2_exec_global = T_task_exec;
    flag_task_2_firstexecution = 0;
}
void threads_linux_timer_start_task_1 (void)
Definition at line 375 of file threads_linux.c.
References flag_task_1_firstexecution, task_1_period_us, threads_linux_timer_task_1(), and timer_task_1.
Referenced by threads_linux_init().
{
    struct itimerspec itimer;
    struct sigevent sigev;
    int errno = 0;
    flag_task_1_firstexecution = 1;
    itimer.it_interval.tv_sec=0;
    itimer.it_interval.tv_nsec=task_1_period_us * 1000;
    itimer.it_value=itimer.it_interval;
    memset(&sigev, 0, sizeof (struct sigevent));
    sigev.sigev_value.sival_int = 0;
    sigev.sigev_notify = SIGEV_THREAD;
    sigev.sigev_notify_attributes = NULL;
    sigev.sigev_notify_function = threads_linux_timer_task_1;
    if (timer_create(CLOCK_REALTIME, &sigev, &timer_task_1) < 0)
    {
        fprintf(stderr, "[%d]: %s\n", __LINE__, strerror(errno));
        exit(errno);
    }
    if(timer_settime(timer_task_1, 0, &itimer, NULL) < 0)
    {
        fprintf(stderr, "[%d]: %s\n", __LINE__, strerror(errno));
        exit(errno);
    }
}
void threads_linux_timer_start_task_2 (void)
Definition at line 406 of file threads_linux.c.
References flag_task_2_firstexecution, task_2_period_us, threads_linux_timer_task_2(), and timer_task_2.
Referenced by threads_linux_init().
{
    struct itimerspec itimer;
    struct sigevent sigev;
    int errno = 0;
    flag_task_2_firstexecution = 1;
    itimer.it_interval.tv_sec=0;
    itimer.it_interval.tv_nsec=task_2_period_us * 1000;
    itimer.it_value=itimer.it_interval;
    memset (&sigev, 0, sizeof (struct sigevent));
    sigev.sigev_value.sival_int = 0;
    sigev.sigev_notify = SIGEV_THREAD;
    sigev.sigev_notify_attributes = NULL;
    sigev.sigev_notify_function = threads_linux_timer_task_2;
    if(timer_create(CLOCK_REALTIME, &sigev, &timer_task_2) < 0)
    {
        fprintf(stderr, "[%d]: %s\n", __LINE__, strerror(errno));
        exit(errno);
    }
    if(timer_settime(timer_task_2, 0, &itimer, NULL) < 0)
    {
        fprintf(stderr, "[%d]: %s\n", __LINE__, strerror(errno));
        exit(errno);
    }
}
void threads_linux_timer_stop_task_1 (void)
Definition at line 437 of file threads_linux.c.
References timer_task_1.
Referenced by threads_linux_init().
{
    int errno = 0;
    if(timer_delete(timer_task_1) < 0)
    {
        fprintf(stderr, "[%d]: %s\n", __LINE__, strerror(errno));
        exit(errno);
    }
}
void threads_linux_timer_stop_task_2 (void)
Definition at line 447 of file threads_linux.c.
References timer_task_2.
Referenced by threads_linux_init().
{
    int errno = 0;
    if(timer_delete(timer_task_2) < 0)
    {
        fprintf(stderr, "[%d]: %s\n", __LINE__, strerror(errno));
        exit(errno);
    }
}
void threads_linux_timer_task_1 (union sigval sigval)
Definition at line 363 of file threads_linux.c.
References threads_linux_timer_function_task_1().
Referenced by threads_linux_timer_start_task_1().
{
    sigval.sival_int = 0; // Remove warning
    threads_linux_timer_function_task_1();
}
void threads_linux_timer_task_1 (union sigval sigval)
Definition at line 363 of file threads_linux.c.
References threads_linux_timer_function_task_1().
Referenced by threads_linux_timer_start_task_1().
{
    sigval.sival_int = 0; // Remove warning
    threads_linux_timer_function_task_1();
}
void threads_linux_timer_task_2 (union sigval sigval)
Definition at line 369 of file threads_linux.c.
References threads_linux_timer_function_task_2().
Referenced by threads_linux_timer_start_task_2().
{
    sigval.sival_int = 0; // Remove warning
    threads_linux_timer_function_task_2();
}
void threads_linux_timer_task_2 (union sigval sigval)
Definition at line 369 of file threads_linux.c.
References threads_linux_timer_function_task_2().
Referenced by threads_linux_timer_start_task_2().
{
    sigval.sival_int = 0; // Remove warning
    threads_linux_timer_function_task_2();
}
int threads_reset_timer (void)
Definition at line 570 of file threads_linux.c.
References t0, and t_task_1_global.
Referenced by threads_linux_periodic_task_1().
{
    t0 = t_task_1_global;
    return THREADS_LINUX_SUCCESS;
}
Variable Documentation
BATTERY_DATA_STRUCT battery_data
Definition at line 68 of file threads_linux.c.
Referenced by threads_linux_init(), threads_linux_periodic_task_1(), and threads_linux_periodic_task_2().
CALIBRATION_ALTIMETER_STRUCT calibration_altimeter_data
Definition at line 84 of file threads_linux.c.
Referenced by threads_linux_init(), threads_linux_periodic_task_1(), and threads_linux_periodic_task_2().
CALIBRATION_LOCAL_COORDINATE_SYSTEM_STRUCT calibration_local_coordinate_system_data
Definition at line 85 of file threads_linux.c.
Referenced by threads_linux_init(), threads_linux_periodic_task_1(), and threads_linux_periodic_task_2().
CALIBRATION_LOCAL_FIELDS_STRUCT calibration_local_fields_data
Definition at line 86 of file threads_linux.c.
Referenced by threads_linux_init(), threads_linux_periodic_task_1(), and threads_linux_periodic_task_2().
CONTROL_DATA_STRUCT control_data
Definition at line 92 of file threads_linux.c.
Referenced by threads_linux_init(), threads_linux_periodic_task_1(), and threads_linux_periodic_task_2().
ESTIMATION_DATA_STRUCT estimation_data
Definition at line 89 of file threads_linux.c.
Referenced by threads_linux_init(), threads_linux_periodic_task_1(), and threads_linux_periodic_task_2().
int failure = 0
Definition at line 42 of file threads_linux.c.
volatile int flag_task_1_firstexecution = 1
Definition at line 52 of file threads_linux.c.
volatile int flag_task_2_firstexecution = 1
Definition at line 63 of file threads_linux.c.
GPS_DATA_STRUCT gps_data
Definition at line 69 of file threads_linux.c.
Referenced by threads_linux_init(), threads_linux_periodic_task_1(), and threads_linux_periodic_task_2().
GPSMEASURE gps_measure
Definition at line 78 of file threads_linux.c.
Referenced by threads_linux_init(), threads_linux_periodic_task_1(), and threads_linux_periodic_task_2().
IMU_DATA_STRUCT imu_data
Definition at line 70 of file threads_linux.c.
IMUMEASURE imu_measure
Definition at line 79 of file threads_linux.c.
Referenced by threads_linux_init(), threads_linux_periodic_task_1(), and threads_linux_periodic_task_2().
MAGNETOMETERMEASURE magnetometer_measure
Definition at line 80 of file threads_linux.c.
Referenced by threads_linux_init(), threads_linux_periodic_task_1(), and threads_linux_periodic_task_2().
PITOT_DATA_STRUCT pitot_data
Definition at line 71 of file threads_linux.c.
Referenced by threads_linux_init(), threads_linux_periodic_task_1(), and threads_linux_periodic_task_2().
PWM_READ_DATA_STRUCT pwm_read_data
Definition at line 72 of file threads_linux.c.
Referenced by threads_linux_init(), threads_linux_periodic_task_1(), and threads_linux_periodic_task_2().
PWM_WRITE_DATA_STRUCT pwm_write_data
Definition at line 73 of file threads_linux.c.
Referenced by threads_linux_init(), threads_linux_periodic_task_1(), and threads_linux_periodic_task_2().
unsigned char quittask
Definition at line 40 of file main2.c.
Referenced by exit_program(), main(), and threads_linux_init().
SCP1000_DATA_STRUCT scp1000_data
Definition at line 74 of file threads_linux.c.
Referenced by threads_linux_init(), threads_linux_periodic_task_1(), and threads_linux_periodic_task_2().
SONAR_DATA_STRUCT sonar_data
Definition at line 75 of file threads_linux.c.
Referenced by threads_linux_init(), threads_linux_periodic_task_1(), and threads_linux_periodic_task_2().
SONARMEASURE sonar_measure
Definition at line 81 of file threads_linux.c.
Referenced by threads_linux_init(), and threads_linux_periodic_task_1().
volatile double t0 = 0.0
Definition at line 53 of file threads_linux.c.
volatile double T_task_1_exec_global = 0.0
Definition at line 47 of file threads_linux.c.
volatile double t_task_1_global = 0.0
Definition at line 46 of file threads_linux.c.
volatile double T_task_1_max_global = 0.0
Definition at line 50 of file threads_linux.c.
volatile double T_task_1_mean_global = 0.0
Definition at line 48 of file threads_linux.c.
volatile double T_task_1_min_global = 0.0
Definition at line 49 of file threads_linux.c.
volatile double T_task_2_exec_global = 0.0
Definition at line 58 of file threads_linux.c.
volatile double t_task_2_global = 0.0
Definition at line 57 of file threads_linux.c.
volatile double T_task_2_max_global = 0.0
Definition at line 61 of file threads_linux.c.
volatile double T_task_2_mean_global = 0.0
Definition at line 59 of file threads_linux.c.
volatile double T_task_2_min_global = 0.0
Definition at line 60 of file threads_linux.c.
volatile int task_1_period_us = TASK1_PERIOD_US
Definition at line 51 of file threads_linux.c.
volatile int task_2_period_us = TASK2_PERIOD_US
Definition at line 62 of file threads_linux.c.
unsigned int telemetry_mode = UI_NCURSES_MODE
Definition at line 64 of file threads_linux.c.
timer_t timer_task_1
Definition at line 45 of file threads_linux.c.
timer_t timer_task_2
Definition at line 56 of file threads_linux.c.
int total = 0
Definition at line 41 of file threads_linux.c.