ui.h File Reference
Macros
#define UI_NCURSES_MODE 2
#define UI_MODULE_ENABLED 1
#define UI_DEBUG_MODE 0
#define SUCCESS 1
#define FAILURE -1
Functions
int ui_init (void)
Initialize UI.
int ui_close (void)
Close UI.
int ui_update (IMU_DATA_STRUCT *pimu_data, EFF_DATA_STRUCT *peff_data, MRA_DATA_STRUCT *pmra_data, ENC_DATA_STRUCT *enc_data, int total, int failure)
Update Screen with new data of sensors.
int ui_imu_data (IMU_DATA_STRUCT *pimu_data)
Print IMU data.
int ui_eff_data (EFF_DATA_STRUCT *peff_data)
int ui_enc_data (ENC_DATA_STRUCT *enc_data)
Print ENCODER data.
int ui_mra_data (MRA_DATA_STRUCT *pmra_data)
Print MRA data.
int ui_overview_data (int total, int failures, IMU_DATA_STRUCT *pimu_data, EFF_DATA_STRUCT *peff_data, MRA_DATA_STRUCT *pmra_data, ENC_DATA_STRUCT *enc_data)
Print ALL sensors data.
Macro Definition Documentation
#define FAILURE -1
Definition at line 11 of file ui.h.
#define SUCCESS 1
Definition at line 10 of file ui.h.
#define UI_DEBUG_MODE 0
Definition at line 8 of file ui.h.
#define UI_MODULE_ENABLED 1
Definition at line 7 of file ui.h.
#define UI_NCURSES_MODE 2
Definition at line 5 of file ui.h.
Referenced by periodic_task_2(), and threads_linux_periodic_task_2().
Function Documentation
int ui_eff_data (EFF_DATA_STRUCT * peff_data)
Definition at line 158 of file ui.c.
References EFF_DATA_STRUCT::F, EFF_DATA_STRUCT::M, SUCCESS, DATA_XYZ::x, DATA_XYZ::y, and DATA_XYZ::z.
Referenced by ui_update().
{
        mvprintw(2,0,"Fx (bits): %d",peff_data->F.x);
        //mvprintw(2,40,"Fx (N): %lf",peff_data->??);
        mvprintw(3,0,"Fy (bits): %d",peff_data->F.y);
        //mvprintw(3,40,"Fx (N): %lf",peff_data->??);
        mvprintw(4,0,"Fz (bits): %d",peff_data->F.z);
        //mvprintw(4,40,"Fx (N): %lf",peff_data->??);
        mvprintw(5,0,"Mx (bits): %d",peff_data->M.x);
        //mvprintw(5,40,"Mx (Nm): %lf",peff_data->??);
        mvprintw(6,0,"My (bits): %d",peff_data->M.y);
        //mvprintw(6,40,"My (Nm): %lf",peff_data->??);
        mvprintw(7,0,"Mz (bits): %d",peff_data->M.z);
        //mvprintw(7,40,"Mz (Nm): %lf",peff_data->??);
        return SUCCESS;
}
int ui_enc_data (ENC_DATA_STRUCT * enc_data)
Print ENCODER data.
Definition at line 176 of file ui.c.
References ENC_DATA_STRUCT::calib, ENC_DATA_STRUCT::position, ENC_DATA_STRUCT::calibrate::position, and SUCCESS.
Referenced by ui_update().
{
   mvprintw(2,0,"Position (raw): %lf",enc_data->position);
   mvprintw(3,0,"Position (degree): %lf",enc_data->calib.position)
      ;
   return SUCCESS;
}
int ui_overview_data (int total, int failures, IMU_DATA_STRUCT * pimu_data, EFF_DATA_STRUCT * peff_data, MRA_DATA_STRUCT * pmra_data, ENC_DATA_STRUCT * enc_data)
Print ALL sensors data.
Definition at line 192 of file ui.c.
References IMU_DATA_STRUCT::acc, IMU_DATA_STRUCT::calibrated::acc, ENC_DATA_STRUCT::calib, IMU_DATA_STRUCT::calib, IMU_DATA_STRUCT::calib_temp, get_time(), IMU_DATA_STRUCT::gyr, IMU_DATA_STRUCT::calibrated::gyr, IMU_DATA_STRUCT::mag, IMU_DATA_STRUCT::calibrated::mag, ENC_DATA_STRUCT::position, ENC_DATA_STRUCT::calibrate::position, SUCCESS, t0, IMU_DATA_STRUCT::temp, MRA_DATA_STRUCT::v_ctl, MRA_DATA_STRUCT::v_ctl_read, DATA_XYZ::x, DATA_XYZ_DOUBLE::x, DATA_XYZ::y, DATA_XYZ_DOUBLE::y, DATA_XYZ::z, and DATA_XYZ_DOUBLE::z.
Referenced by ui_update().
{
        float error_rate = 0.0;
        double t = 0.0;
        double Ts = 0.0;
        double mean_exec_time = 0.0;
        double t0 = 0.0;
        get_time(&t, &Ts, &mean_exec_time, &t0);
        error_rate = (float)(((float)failures/(float)total)*100.0);
        mvprintw(2, 0, "Communication Statistics: Total = %d Failures = %d
       Error Rate = %3.3f",total, failures, error_rate);
        mvprintw(4, 0, "IMU Accelerometer (bits):\tX:%4d\tY:%4d\tZ:%4d",
      pimu_data->acc.x, pimu_data->acc.y, pimu_data->acc.z);
        mvprintw(5, 0, "IMU Gyrometer (bits):\t\tX:%4d\tY:%4d\tZ:%4d",
      pimu_data->gyr.x, pimu_data->gyr.y, pimu_data->gyr.z);
        mvprintw(6, 0, "IMU Magnetometer (bits):\tX:%4d\tY:%4d\tZ:%4d",
      pimu_data->mag.x, pimu_data->mag.y, pimu_data->mag.z);
        
        mvprintw(8, 0, "IMU Accelerometer (g):\t\tX:%8.5lf\tY:%8.5lf\tZ:%8.5lf
      ", pimu_data->calib.acc.x, pimu_data->calib.acc.y, pimu_data->
      calib.acc.z);
        mvprintw(9, 0, "IMU Gyrometer (rad/s):\t\tX:%8.5lf\tY:%8.5lf\tZ:%8.5lf"
      , pimu_data->calib.gyr.x, pimu_data->calib.gyr.y, pimu_data->
      calib.gyr.z);
        mvprintw(10, 0, "IMU Magnetometer (B):\t\tX:%8.5lf\tY:%8.5lf\tZ:%8.5lf"
      , pimu_data->calib.mag.x, pimu_data->calib.mag.y, pimu_data->
      calib.mag.z);
        mvprintw(12, 0, "Temp (bits):\t%d", pimu_data->temp);
        mvprintw(12,40, "Temp (ºC):\t%lf", pimu_data->calib_temp);
        mvprintw(13,0, "Encoder (bits):\t%d",enc_data->position);
        mvprintw(13,40, "Encoder (degree):\t%d",enc_data->calib.position
      );
        //mvprintw(15,0,"Fx (bits): %d",peff_data->F.x);
        //mvprintw(2,40,"Fx (N): %lf",peff_data->??);
        //mvprintw(15,0,"Fy (bits): %d",peff_data->F.y);
        //mvprintw(3,40,"Fx (N): %lf",peff_data->??);
        //mvprintw(16,0,"Fz (bits): %d",peff_data->F.z);
        //mvprintw(4,40,"Fx (N): %lf",peff_data->??);
        //mvprintw(17,0,"Mx (bits): %d",peff_data->M.x);
        //mvprintw(5,40,"Mx (Nm): %lf",peff_data->??);
        //mvprintw(18,0,"My (bits): %d",peff_data->M.y);
        //mvprintw(6,40,"My (Nm): %lf",peff_data->??);
        //mvprintw(19,0,"Mz (bits): %d",peff_data->M.z);
        //mvprintw(7,40,"Mz (Nm): %lf",peff_data->??);
        
        mvprintw(15, 0, "Voltage Control Written (bits):\t%4d", pmra_data->
      v_ctl);
        mvprintw(16, 0, "Voltage Control Read (bits):\t%4d", pmra_data->
      v_ctl_read);
    mvprintw(18, 0, "Runtime: %4.2lf", t);
    //removed datalogger:
    if(1)//if(datalogger_status() == DATALOGGER_NOT_RUNNING)
    {
        mvprintw(18, 40, "Datalogger stopped");
    }
    else
    {
        mvprintw(18, 40, "Datalogger runtime: %4.2lf", (t-t0));
    }
/*
    if(calibration_get_status() == CALIBRATION_NOT_RUNNING)
    {
        mvprintw(15, 0, "Calibration stopped");
    }
    else
    {
        mvprintw(15, 0, "Calibration running");
    }
*/
        mvprintw(20, 0, "I: IMU");
        mvprintw(20, 20, "F: Efforts");
        mvprintw(20, 40, "M: Magneto-rheological Actuator");
        mvprintw(21, 0, "E: Encoder");
        mvprintw(21, 20, "O: Overview");
        //mvprintw(21, 40, "D: Datalogger Start/Stop");
        mvprintw(22, 0, "Q: Quit\n");
        return SUCCESS;
}